/*
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ArtifactLinksResponseLinksInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * ArtifactLinksResponse
 */
@JsonPropertyOrder({
  ArtifactLinksResponse.JSON_PROPERTY_ARTIFACT_ID,
  ArtifactLinksResponse.JSON_PROPERTY_LINKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class ArtifactLinksResponse {
  public static final String JSON_PROPERTY_ARTIFACT_ID = "artifact_id";
  @javax.annotation.Nullable
  private String artifactId;

  public static final String JSON_PROPERTY_LINKS = "links";
  @javax.annotation.Nullable
  private List<ArtifactLinksResponseLinksInner> links = new ArrayList<>();

  public ArtifactLinksResponse() { 
  }

  public ArtifactLinksResponse artifactId(@javax.annotation.Nullable String artifactId) {
    this.artifactId = artifactId;
    return this;
  }

  /**
   * Get artifactId
   * @return artifactId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARTIFACT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getArtifactId() {
    return artifactId;
  }


  @JsonProperty(value = JSON_PROPERTY_ARTIFACT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArtifactId(@javax.annotation.Nullable String artifactId) {
    this.artifactId = artifactId;
  }


  public ArtifactLinksResponse links(@javax.annotation.Nullable List<ArtifactLinksResponseLinksInner> links) {
    this.links = links;
    return this;
  }

  public ArtifactLinksResponse addLinksItem(ArtifactLinksResponseLinksInner linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ArtifactLinksResponseLinksInner> getLinks() {
    return links;
  }


  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@javax.annotation.Nullable List<ArtifactLinksResponseLinksInner> links) {
    this.links = links;
  }


  /**
   * Return true if this ArtifactLinksResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArtifactLinksResponse artifactLinksResponse = (ArtifactLinksResponse) o;
    return Objects.equals(this.artifactId, artifactLinksResponse.artifactId) &&
        Objects.equals(this.links, artifactLinksResponse.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(artifactId, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArtifactLinksResponse {\n");
    sb.append("    artifactId: ").append(toIndentedString(artifactId)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `artifact_id` to the URL query string
    if (getArtifactId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sartifact_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getArtifactId()))));
    }

    // add `links` to the URL query string
    if (getLinks() != null) {
      for (int i = 0; i < getLinks().size(); i++) {
        if (getLinks().get(i) != null) {
          joiner.add(getLinks().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%slinks%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

