/*
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * BlastRadiusResponse
 */
@JsonPropertyOrder({
  BlastRadiusResponse.JSON_PROPERTY_FILE,
  BlastRadiusResponse.JSON_PROPERTY_DEPENDENTS,
  BlastRadiusResponse.JSON_PROPERTY_DEPENDENT_COUNT,
  BlastRadiusResponse.JSON_PROPERTY_DEPENDENCIES,
  BlastRadiusResponse.JSON_PROPERTY_DEPENDENCY_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class BlastRadiusResponse {
  public static final String JSON_PROPERTY_FILE = "file";
  @javax.annotation.Nullable
  private String _file;

  public static final String JSON_PROPERTY_DEPENDENTS = "dependents";
  @javax.annotation.Nullable
  private List<String> dependents = new ArrayList<>();

  public static final String JSON_PROPERTY_DEPENDENT_COUNT = "dependent_count";
  @javax.annotation.Nullable
  private Integer dependentCount;

  public static final String JSON_PROPERTY_DEPENDENCIES = "dependencies";
  @javax.annotation.Nullable
  private List<String> dependencies = new ArrayList<>();

  public static final String JSON_PROPERTY_DEPENDENCY_COUNT = "dependency_count";
  @javax.annotation.Nullable
  private Integer dependencyCount;

  public BlastRadiusResponse() { 
  }

  public BlastRadiusResponse _file(@javax.annotation.Nullable String _file) {
    this._file = _file;
    return this;
  }

  /**
   * Get _file
   * @return _file
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFile() {
    return _file;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFile(@javax.annotation.Nullable String _file) {
    this._file = _file;
  }


  public BlastRadiusResponse dependents(@javax.annotation.Nullable List<String> dependents) {
    this.dependents = dependents;
    return this;
  }

  public BlastRadiusResponse addDependentsItem(String dependentsItem) {
    if (this.dependents == null) {
      this.dependents = new ArrayList<>();
    }
    this.dependents.add(dependentsItem);
    return this;
  }

  /**
   * Get dependents
   * @return dependents
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEPENDENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getDependents() {
    return dependents;
  }


  @JsonProperty(value = JSON_PROPERTY_DEPENDENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDependents(@javax.annotation.Nullable List<String> dependents) {
    this.dependents = dependents;
  }


  public BlastRadiusResponse dependentCount(@javax.annotation.Nullable Integer dependentCount) {
    this.dependentCount = dependentCount;
    return this;
  }

  /**
   * Get dependentCount
   * @return dependentCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEPENDENT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDependentCount() {
    return dependentCount;
  }


  @JsonProperty(value = JSON_PROPERTY_DEPENDENT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDependentCount(@javax.annotation.Nullable Integer dependentCount) {
    this.dependentCount = dependentCount;
  }


  public BlastRadiusResponse dependencies(@javax.annotation.Nullable List<String> dependencies) {
    this.dependencies = dependencies;
    return this;
  }

  public BlastRadiusResponse addDependenciesItem(String dependenciesItem) {
    if (this.dependencies == null) {
      this.dependencies = new ArrayList<>();
    }
    this.dependencies.add(dependenciesItem);
    return this;
  }

  /**
   * Get dependencies
   * @return dependencies
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEPENDENCIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getDependencies() {
    return dependencies;
  }


  @JsonProperty(value = JSON_PROPERTY_DEPENDENCIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDependencies(@javax.annotation.Nullable List<String> dependencies) {
    this.dependencies = dependencies;
  }


  public BlastRadiusResponse dependencyCount(@javax.annotation.Nullable Integer dependencyCount) {
    this.dependencyCount = dependencyCount;
    return this;
  }

  /**
   * Get dependencyCount
   * @return dependencyCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEPENDENCY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDependencyCount() {
    return dependencyCount;
  }


  @JsonProperty(value = JSON_PROPERTY_DEPENDENCY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDependencyCount(@javax.annotation.Nullable Integer dependencyCount) {
    this.dependencyCount = dependencyCount;
  }


  /**
   * Return true if this BlastRadiusResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlastRadiusResponse blastRadiusResponse = (BlastRadiusResponse) o;
    return Objects.equals(this._file, blastRadiusResponse._file) &&
        Objects.equals(this.dependents, blastRadiusResponse.dependents) &&
        Objects.equals(this.dependentCount, blastRadiusResponse.dependentCount) &&
        Objects.equals(this.dependencies, blastRadiusResponse.dependencies) &&
        Objects.equals(this.dependencyCount, blastRadiusResponse.dependencyCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_file, dependents, dependentCount, dependencies, dependencyCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlastRadiusResponse {\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    dependents: ").append(toIndentedString(dependents)).append("\n");
    sb.append("    dependentCount: ").append(toIndentedString(dependentCount)).append("\n");
    sb.append("    dependencies: ").append(toIndentedString(dependencies)).append("\n");
    sb.append("    dependencyCount: ").append(toIndentedString(dependencyCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `file` to the URL query string
    if (getFile() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfile%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFile()))));
    }

    // add `dependents` to the URL query string
    if (getDependents() != null) {
      for (int i = 0; i < getDependents().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdependents%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getDependents().get(i)))));
      }
    }

    // add `dependent_count` to the URL query string
    if (getDependentCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdependent_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDependentCount()))));
    }

    // add `dependencies` to the URL query string
    if (getDependencies() != null) {
      for (int i = 0; i < getDependencies().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdependencies%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getDependencies().get(i)))));
      }
    }

    // add `dependency_count` to the URL query string
    if (getDependencyCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdependency_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDependencyCount()))));
    }

    return joiner.toString();
  }
}

