/*
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * CodeUpdateRequest
 */
@JsonPropertyOrder({
  CodeUpdateRequest.JSON_PROPERTY_PATH,
  CodeUpdateRequest.JSON_PROPERTY_PROJECT,
  CodeUpdateRequest.JSON_PROPERTY_EMBEDDING_COMMAND
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class CodeUpdateRequest {
  public static final String JSON_PROPERTY_PATH = "path";
  @javax.annotation.Nonnull
  private String path;

  public static final String JSON_PROPERTY_PROJECT = "project";
  @javax.annotation.Nonnull
  private String project;

  public static final String JSON_PROPERTY_EMBEDDING_COMMAND = "embedding_command";
  @javax.annotation.Nullable
  private String embeddingCommand;

  public CodeUpdateRequest() { 
  }

  public CodeUpdateRequest path(@javax.annotation.Nonnull String path) {
    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPath(@javax.annotation.Nonnull String path) {
    this.path = path;
  }


  public CodeUpdateRequest project(@javax.annotation.Nonnull String project) {
    this.project = project;
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProject() {
    return project;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProject(@javax.annotation.Nonnull String project) {
    this.project = project;
  }


  public CodeUpdateRequest embeddingCommand(@javax.annotation.Nullable String embeddingCommand) {
    this.embeddingCommand = embeddingCommand;
    return this;
  }

  /**
   * Get embeddingCommand
   * @return embeddingCommand
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMBEDDING_COMMAND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmbeddingCommand() {
    return embeddingCommand;
  }


  @JsonProperty(value = JSON_PROPERTY_EMBEDDING_COMMAND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmbeddingCommand(@javax.annotation.Nullable String embeddingCommand) {
    this.embeddingCommand = embeddingCommand;
  }


  /**
   * Return true if this CodeUpdateRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodeUpdateRequest codeUpdateRequest = (CodeUpdateRequest) o;
    return Objects.equals(this.path, codeUpdateRequest.path) &&
        Objects.equals(this.project, codeUpdateRequest.project) &&
        Objects.equals(this.embeddingCommand, codeUpdateRequest.embeddingCommand);
  }

  @Override
  public int hashCode() {
    return Objects.hash(path, project, embeddingCommand);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodeUpdateRequest {\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    embeddingCommand: ").append(toIndentedString(embeddingCommand)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `path` to the URL query string
    if (getPath() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPath()))));
    }

    // add `project` to the URL query string
    if (getProject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProject()))));
    }

    // add `embedding_command` to the URL query string
    if (getEmbeddingCommand() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sembedding_command%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmbeddingCommand()))));
    }

    return joiner.toString();
  }
}

