/*
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * IngestRequest
 */
@JsonPropertyOrder({
  IngestRequest.JSON_PROPERTY_WORKSPACE,
  IngestRequest.JSON_PROPERTY_EMBEDDING_COMMAND,
  IngestRequest.JSON_PROPERTY_FORCE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class IngestRequest {
  public static final String JSON_PROPERTY_WORKSPACE = "workspace";
  @javax.annotation.Nullable
  private String workspace;

  public static final String JSON_PROPERTY_EMBEDDING_COMMAND = "embedding_command";
  @javax.annotation.Nullable
  private String embeddingCommand;

  public static final String JSON_PROPERTY_FORCE = "force";
  @javax.annotation.Nullable
  private Boolean force = false;

  public IngestRequest() { 
  }

  public IngestRequest workspace(@javax.annotation.Nullable String workspace) {
    this.workspace = workspace;
    return this;
  }

  /**
   * Workspace root, workspace name, or \&quot;all\&quot;.
   * @return workspace
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WORKSPACE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getWorkspace() {
    return workspace;
  }


  @JsonProperty(value = JSON_PROPERTY_WORKSPACE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkspace(@javax.annotation.Nullable String workspace) {
    this.workspace = workspace;
  }


  public IngestRequest embeddingCommand(@javax.annotation.Nullable String embeddingCommand) {
    this.embeddingCommand = embeddingCommand;
    return this;
  }

  /**
   * Get embeddingCommand
   * @return embeddingCommand
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMBEDDING_COMMAND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmbeddingCommand() {
    return embeddingCommand;
  }


  @JsonProperty(value = JSON_PROPERTY_EMBEDDING_COMMAND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmbeddingCommand(@javax.annotation.Nullable String embeddingCommand) {
    this.embeddingCommand = embeddingCommand;
  }


  public IngestRequest force(@javax.annotation.Nullable Boolean force) {
    this.force = force;
    return this;
  }

  /**
   * Get force
   * @return force
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FORCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getForce() {
    return force;
  }


  @JsonProperty(value = JSON_PROPERTY_FORCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForce(@javax.annotation.Nullable Boolean force) {
    this.force = force;
  }


  /**
   * Return true if this IngestRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IngestRequest ingestRequest = (IngestRequest) o;
    return Objects.equals(this.workspace, ingestRequest.workspace) &&
        Objects.equals(this.embeddingCommand, ingestRequest.embeddingCommand) &&
        Objects.equals(this.force, ingestRequest.force);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workspace, embeddingCommand, force);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IngestRequest {\n");
    sb.append("    workspace: ").append(toIndentedString(workspace)).append("\n");
    sb.append("    embeddingCommand: ").append(toIndentedString(embeddingCommand)).append("\n");
    sb.append("    force: ").append(toIndentedString(force)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `workspace` to the URL query string
    if (getWorkspace() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sworkspace%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWorkspace()))));
    }

    // add `embedding_command` to the URL query string
    if (getEmbeddingCommand() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sembedding_command%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmbeddingCommand()))));
    }

    // add `force` to the URL query string
    if (getForce() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sforce%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getForce()))));
    }

    return joiner.toString();
  }
}

