/*
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * MaintenanceClearResponse
 */
@JsonPropertyOrder({
  MaintenanceClearResponse.JSON_PROPERTY_STATUS,
  MaintenanceClearResponse.JSON_PROPERTY_PROJECT,
  MaintenanceClearResponse.JSON_PROPERTY_CHUNKS_DELETED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class MaintenanceClearResponse {
  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_PROJECT = "project";
  @javax.annotation.Nullable
  private String project;

  public static final String JSON_PROPERTY_CHUNKS_DELETED = "chunks_deleted";
  @javax.annotation.Nullable
  private Integer chunksDeleted;

  public MaintenanceClearResponse() { 
  }

  public MaintenanceClearResponse status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public MaintenanceClearResponse project(@javax.annotation.Nullable String project) {
    this.project = project;
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProject() {
    return project;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProject(@javax.annotation.Nullable String project) {
    this.project = project;
  }


  public MaintenanceClearResponse chunksDeleted(@javax.annotation.Nullable Integer chunksDeleted) {
    this.chunksDeleted = chunksDeleted;
    return this;
  }

  /**
   * Get chunksDeleted
   * @return chunksDeleted
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHUNKS_DELETED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getChunksDeleted() {
    return chunksDeleted;
  }


  @JsonProperty(value = JSON_PROPERTY_CHUNKS_DELETED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChunksDeleted(@javax.annotation.Nullable Integer chunksDeleted) {
    this.chunksDeleted = chunksDeleted;
  }


  /**
   * Return true if this MaintenanceClearResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaintenanceClearResponse maintenanceClearResponse = (MaintenanceClearResponse) o;
    return Objects.equals(this.status, maintenanceClearResponse.status) &&
        Objects.equals(this.project, maintenanceClearResponse.project) &&
        Objects.equals(this.chunksDeleted, maintenanceClearResponse.chunksDeleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, project, chunksDeleted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaintenanceClearResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    chunksDeleted: ").append(toIndentedString(chunksDeleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `project` to the URL query string
    if (getProject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProject()))));
    }

    // add `chunks_deleted` to the URL query string
    if (getChunksDeleted() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schunks_deleted%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChunksDeleted()))));
    }

    return joiner.toString();
  }
}

