/*
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * RollbackRequest
 */
@JsonPropertyOrder({
  RollbackRequest.JSON_PROPERTY_TARGET_RELEASE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class RollbackRequest {
  public static final String JSON_PROPERTY_TARGET_RELEASE_ID = "target_release_id";
  @javax.annotation.Nullable
  private Long targetReleaseId;

  public RollbackRequest() { 
  }

  public RollbackRequest targetReleaseId(@javax.annotation.Nullable Long targetReleaseId) {
    this.targetReleaseId = targetReleaseId;
    return this;
  }

  /**
   * Get targetReleaseId
   * @return targetReleaseId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TARGET_RELEASE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getTargetReleaseId() {
    return targetReleaseId;
  }


  @JsonProperty(value = JSON_PROPERTY_TARGET_RELEASE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetReleaseId(@javax.annotation.Nullable Long targetReleaseId) {
    this.targetReleaseId = targetReleaseId;
  }


  /**
   * Return true if this RollbackRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RollbackRequest rollbackRequest = (RollbackRequest) o;
    return Objects.equals(this.targetReleaseId, rollbackRequest.targetReleaseId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetReleaseId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RollbackRequest {\n");
    sb.append("    targetReleaseId: ").append(toIndentedString(targetReleaseId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `target_release_id` to the URL query string
    if (getTargetReleaseId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%starget_release_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTargetReleaseId()))));
    }

    return joiner.toString();
  }
}

