// <auto-generated>
/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AimeeKb.Client;

namespace AimeeKb.Model
{
    /// <summary>
    /// ArtifactLinksResponseLinksInner
    /// </summary>
    public partial class ArtifactLinksResponseLinksInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArtifactLinksResponseLinksInner" /> class.
        /// </summary>
        /// <param name="toId">toId</param>
        /// <param name="linkKind">linkKind</param>
        [JsonConstructor]
        public ArtifactLinksResponseLinksInner(Option<string?> toId = default, Option<string?> linkKind = default)
        {
            ToIdOption = toId;
            LinkKindOption = linkKind;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ToId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ToIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ToId
        /// </summary>
        [JsonPropertyName("to_id")]
        public string? ToId { get { return this.ToIdOption.Value; } set { this.ToIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of LinkKind
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LinkKindOption { get; private set; }

        /// <summary>
        /// Gets or Sets LinkKind
        /// </summary>
        [JsonPropertyName("link_kind")]
        public string? LinkKind { get { return this.LinkKindOption.Value; } set { this.LinkKindOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ArtifactLinksResponseLinksInner {\n");
            sb.Append("  ToId: ").Append(ToId).Append("\n");
            sb.Append("  LinkKind: ").Append(LinkKind).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ArtifactLinksResponseLinksInner" />
    /// </summary>
    public class ArtifactLinksResponseLinksInnerJsonConverter : JsonConverter<ArtifactLinksResponseLinksInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="ArtifactLinksResponseLinksInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ArtifactLinksResponseLinksInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> toId = default;
            Option<string?> linkKind = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "to_id":
                            toId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "link_kind":
                            linkKind = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (toId.IsSet && toId.Value == null)
                throw new ArgumentNullException(nameof(toId), "Property is not nullable for class ArtifactLinksResponseLinksInner.");

            if (linkKind.IsSet && linkKind.Value == null)
                throw new ArgumentNullException(nameof(linkKind), "Property is not nullable for class ArtifactLinksResponseLinksInner.");

            return new ArtifactLinksResponseLinksInner(toId, linkKind);
        }

        /// <summary>
        /// Serializes a <see cref="ArtifactLinksResponseLinksInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="artifactLinksResponseLinksInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ArtifactLinksResponseLinksInner artifactLinksResponseLinksInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, artifactLinksResponseLinksInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ArtifactLinksResponseLinksInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="artifactLinksResponseLinksInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ArtifactLinksResponseLinksInner artifactLinksResponseLinksInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (artifactLinksResponseLinksInner.ToIdOption.IsSet && artifactLinksResponseLinksInner.ToId == null)
                throw new ArgumentNullException(nameof(artifactLinksResponseLinksInner.ToId), "Property is required for class ArtifactLinksResponseLinksInner.");

            if (artifactLinksResponseLinksInner.LinkKindOption.IsSet && artifactLinksResponseLinksInner.LinkKind == null)
                throw new ArgumentNullException(nameof(artifactLinksResponseLinksInner.LinkKind), "Property is required for class ArtifactLinksResponseLinksInner.");

            if (artifactLinksResponseLinksInner.ToIdOption.IsSet)
                writer.WriteString("to_id", artifactLinksResponseLinksInner.ToId);

            if (artifactLinksResponseLinksInner.LinkKindOption.IsSet)
                writer.WriteString("link_kind", artifactLinksResponseLinksInner.LinkKind);
        }
    }
}
