// <auto-generated>
/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AimeeKb.Client;

namespace AimeeKb.Model
{
    /// <summary>
    /// CodeCallerHit
    /// </summary>
    public partial class CodeCallerHit : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CodeCallerHit" /> class.
        /// </summary>
        /// <param name="project">project</param>
        /// <param name="filePath">filePath</param>
        /// <param name="caller">caller</param>
        /// <param name="line">line</param>
        [JsonConstructor]
        public CodeCallerHit(Option<string?> project = default, Option<string?> filePath = default, Option<string?> caller = default, Option<int?> line = default)
        {
            ProjectOption = project;
            FilePathOption = filePath;
            CallerOption = caller;
            LineOption = line;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Project
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets Project
        /// </summary>
        [JsonPropertyName("project")]
        public string? Project { get { return this.ProjectOption.Value; } set { this.ProjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of FilePath
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FilePathOption { get; private set; }

        /// <summary>
        /// Gets or Sets FilePath
        /// </summary>
        [JsonPropertyName("file_path")]
        public string? FilePath { get { return this.FilePathOption.Value; } set { this.FilePathOption = new(value); } }

        /// <summary>
        /// Used to track the state of Caller
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CallerOption { get; private set; }

        /// <summary>
        /// Gets or Sets Caller
        /// </summary>
        [JsonPropertyName("caller")]
        public string? Caller { get { return this.CallerOption.Value; } set { this.CallerOption = new(value); } }

        /// <summary>
        /// Used to track the state of Line
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> LineOption { get; private set; }

        /// <summary>
        /// Gets or Sets Line
        /// </summary>
        [JsonPropertyName("line")]
        public int? Line { get { return this.LineOption.Value; } set { this.LineOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CodeCallerHit {\n");
            sb.Append("  Project: ").Append(Project).Append("\n");
            sb.Append("  FilePath: ").Append(FilePath).Append("\n");
            sb.Append("  Caller: ").Append(Caller).Append("\n");
            sb.Append("  Line: ").Append(Line).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CodeCallerHit" />
    /// </summary>
    public class CodeCallerHitJsonConverter : JsonConverter<CodeCallerHit>
    {
        /// <summary>
        /// Deserializes json to <see cref="CodeCallerHit" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CodeCallerHit Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> project = default;
            Option<string?> filePath = default;
            Option<string?> caller = default;
            Option<int?> line = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "project":
                            project = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "file_path":
                            filePath = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "caller":
                            caller = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "line":
                            line = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (project.IsSet && project.Value == null)
                throw new ArgumentNullException(nameof(project), "Property is not nullable for class CodeCallerHit.");

            if (filePath.IsSet && filePath.Value == null)
                throw new ArgumentNullException(nameof(filePath), "Property is not nullable for class CodeCallerHit.");

            if (caller.IsSet && caller.Value == null)
                throw new ArgumentNullException(nameof(caller), "Property is not nullable for class CodeCallerHit.");

            if (line.IsSet && line.Value == null)
                throw new ArgumentNullException(nameof(line), "Property is not nullable for class CodeCallerHit.");

            return new CodeCallerHit(project, filePath, caller, line);
        }

        /// <summary>
        /// Serializes a <see cref="CodeCallerHit" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="codeCallerHit"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CodeCallerHit codeCallerHit, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, codeCallerHit, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CodeCallerHit" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="codeCallerHit"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CodeCallerHit codeCallerHit, JsonSerializerOptions jsonSerializerOptions)
        {
            if (codeCallerHit.ProjectOption.IsSet && codeCallerHit.Project == null)
                throw new ArgumentNullException(nameof(codeCallerHit.Project), "Property is required for class CodeCallerHit.");

            if (codeCallerHit.FilePathOption.IsSet && codeCallerHit.FilePath == null)
                throw new ArgumentNullException(nameof(codeCallerHit.FilePath), "Property is required for class CodeCallerHit.");

            if (codeCallerHit.CallerOption.IsSet && codeCallerHit.Caller == null)
                throw new ArgumentNullException(nameof(codeCallerHit.Caller), "Property is required for class CodeCallerHit.");

            if (codeCallerHit.ProjectOption.IsSet)
                writer.WriteString("project", codeCallerHit.Project);

            if (codeCallerHit.FilePathOption.IsSet)
                writer.WriteString("file_path", codeCallerHit.FilePath);

            if (codeCallerHit.CallerOption.IsSet)
                writer.WriteString("caller", codeCallerHit.Caller);

            if (codeCallerHit.LineOption.IsSet)
                writer.WriteNumber("line", codeCallerHit.LineOption.Value!.Value);
        }
    }
}
