// <auto-generated>
/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AimeeKb.Client;

namespace AimeeKb.Model
{
    /// <summary>
    /// CodeCallersResponse
    /// </summary>
    public partial class CodeCallersResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CodeCallersResponse" /> class.
        /// </summary>
        /// <param name="status">status</param>
        /// <param name="hits">hits</param>
        /// <param name="nextCursor">nextCursor</param>
        [JsonConstructor]
        public CodeCallersResponse(Option<string?> status = default, Option<List<CodeCallerHit>?> hits = default, Option<string?> nextCursor = default)
        {
            StatusOption = status;
            HitsOption = hits;
            NextCursorOption = nextCursor;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Hits
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CodeCallerHit>?> HitsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Hits
        /// </summary>
        [JsonPropertyName("hits")]
        public List<CodeCallerHit>? Hits { get { return this.HitsOption.Value; } set { this.HitsOption = new(value); } }

        /// <summary>
        /// Used to track the state of NextCursor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NextCursorOption { get; private set; }

        /// <summary>
        /// Gets or Sets NextCursor
        /// </summary>
        [JsonPropertyName("next_cursor")]
        public string? NextCursor { get { return this.NextCursorOption.Value; } set { this.NextCursorOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CodeCallersResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Hits: ").Append(Hits).Append("\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CodeCallersResponse" />
    /// </summary>
    public class CodeCallersResponseJsonConverter : JsonConverter<CodeCallersResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="CodeCallersResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CodeCallersResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> status = default;
            Option<List<CodeCallerHit>?> hits = default;
            Option<string?> nextCursor = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "hits":
                            hits = new Option<List<CodeCallerHit>?>(JsonSerializer.Deserialize<List<CodeCallerHit>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "next_cursor":
                            nextCursor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class CodeCallersResponse.");

            if (hits.IsSet && hits.Value == null)
                throw new ArgumentNullException(nameof(hits), "Property is not nullable for class CodeCallersResponse.");

            if (nextCursor.IsSet && nextCursor.Value == null)
                throw new ArgumentNullException(nameof(nextCursor), "Property is not nullable for class CodeCallersResponse.");

            return new CodeCallersResponse(status, hits, nextCursor);
        }

        /// <summary>
        /// Serializes a <see cref="CodeCallersResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="codeCallersResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CodeCallersResponse codeCallersResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, codeCallersResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CodeCallersResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="codeCallersResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CodeCallersResponse codeCallersResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (codeCallersResponse.StatusOption.IsSet && codeCallersResponse.Status == null)
                throw new ArgumentNullException(nameof(codeCallersResponse.Status), "Property is required for class CodeCallersResponse.");

            if (codeCallersResponse.HitsOption.IsSet && codeCallersResponse.Hits == null)
                throw new ArgumentNullException(nameof(codeCallersResponse.Hits), "Property is required for class CodeCallersResponse.");

            if (codeCallersResponse.NextCursorOption.IsSet && codeCallersResponse.NextCursor == null)
                throw new ArgumentNullException(nameof(codeCallersResponse.NextCursor), "Property is required for class CodeCallersResponse.");

            if (codeCallersResponse.StatusOption.IsSet)
                writer.WriteString("status", codeCallersResponse.Status);

            if (codeCallersResponse.HitsOption.IsSet)
            {
                writer.WritePropertyName("hits");
                JsonSerializer.Serialize(writer, codeCallersResponse.Hits, jsonSerializerOptions);
            }
            if (codeCallersResponse.NextCursorOption.IsSet)
                writer.WriteString("next_cursor", codeCallersResponse.NextCursor);
        }
    }
}
