// <auto-generated>
/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AimeeKb.Client;

namespace AimeeKb.Model
{
    /// <summary>
    /// CodeDefinition
    /// </summary>
    public partial class CodeDefinition : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CodeDefinition" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="kind">kind</param>
        /// <param name="line">line</param>
        [JsonConstructor]
        public CodeDefinition(Option<string?> name = default, Option<string?> kind = default, Option<int?> line = default)
        {
            NameOption = name;
            KindOption = kind;
            LineOption = line;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Kind
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> KindOption { get; private set; }

        /// <summary>
        /// Gets or Sets Kind
        /// </summary>
        [JsonPropertyName("kind")]
        public string? Kind { get { return this.KindOption.Value; } set { this.KindOption = new(value); } }

        /// <summary>
        /// Used to track the state of Line
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> LineOption { get; private set; }

        /// <summary>
        /// Gets or Sets Line
        /// </summary>
        [JsonPropertyName("line")]
        public int? Line { get { return this.LineOption.Value; } set { this.LineOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CodeDefinition {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Line: ").Append(Line).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CodeDefinition" />
    /// </summary>
    public class CodeDefinitionJsonConverter : JsonConverter<CodeDefinition>
    {
        /// <summary>
        /// Deserializes json to <see cref="CodeDefinition" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CodeDefinition Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> kind = default;
            Option<int?> line = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "kind":
                            kind = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "line":
                            line = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CodeDefinition.");

            if (kind.IsSet && kind.Value == null)
                throw new ArgumentNullException(nameof(kind), "Property is not nullable for class CodeDefinition.");

            if (line.IsSet && line.Value == null)
                throw new ArgumentNullException(nameof(line), "Property is not nullable for class CodeDefinition.");

            return new CodeDefinition(name, kind, line);
        }

        /// <summary>
        /// Serializes a <see cref="CodeDefinition" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="codeDefinition"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CodeDefinition codeDefinition, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, codeDefinition, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CodeDefinition" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="codeDefinition"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CodeDefinition codeDefinition, JsonSerializerOptions jsonSerializerOptions)
        {
            if (codeDefinition.NameOption.IsSet && codeDefinition.Name == null)
                throw new ArgumentNullException(nameof(codeDefinition.Name), "Property is required for class CodeDefinition.");

            if (codeDefinition.KindOption.IsSet && codeDefinition.Kind == null)
                throw new ArgumentNullException(nameof(codeDefinition.Kind), "Property is required for class CodeDefinition.");

            if (codeDefinition.NameOption.IsSet)
                writer.WriteString("name", codeDefinition.Name);

            if (codeDefinition.KindOption.IsSet)
                writer.WriteString("kind", codeDefinition.Kind);

            if (codeDefinition.LineOption.IsSet)
                writer.WriteNumber("line", codeDefinition.LineOption.Value!.Value);
        }
    }
}
