// <auto-generated>
/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AimeeKb.Client;

namespace AimeeKb.Model
{
    /// <summary>
    /// CodeSearchHit
    /// </summary>
    public partial class CodeSearchHit : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CodeSearchHit" /> class.
        /// </summary>
        /// <param name="project">project</param>
        /// <param name="filePath">filePath</param>
        /// <param name="snippet">snippet</param>
        /// <param name="rank">rank</param>
        [JsonConstructor]
        public CodeSearchHit(Option<string?> project = default, Option<string?> filePath = default, Option<string?> snippet = default, Option<double?> rank = default)
        {
            ProjectOption = project;
            FilePathOption = filePath;
            SnippetOption = snippet;
            RankOption = rank;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Project
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets Project
        /// </summary>
        [JsonPropertyName("project")]
        public string? Project { get { return this.ProjectOption.Value; } set { this.ProjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of FilePath
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FilePathOption { get; private set; }

        /// <summary>
        /// Gets or Sets FilePath
        /// </summary>
        [JsonPropertyName("file_path")]
        public string? FilePath { get { return this.FilePathOption.Value; } set { this.FilePathOption = new(value); } }

        /// <summary>
        /// Used to track the state of Snippet
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SnippetOption { get; private set; }

        /// <summary>
        /// Gets or Sets Snippet
        /// </summary>
        [JsonPropertyName("snippet")]
        public string? Snippet { get { return this.SnippetOption.Value; } set { this.SnippetOption = new(value); } }

        /// <summary>
        /// Used to track the state of Rank
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> RankOption { get; private set; }

        /// <summary>
        /// Gets or Sets Rank
        /// </summary>
        [JsonPropertyName("rank")]
        public double? Rank { get { return this.RankOption.Value; } set { this.RankOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CodeSearchHit {\n");
            sb.Append("  Project: ").Append(Project).Append("\n");
            sb.Append("  FilePath: ").Append(FilePath).Append("\n");
            sb.Append("  Snippet: ").Append(Snippet).Append("\n");
            sb.Append("  Rank: ").Append(Rank).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CodeSearchHit" />
    /// </summary>
    public class CodeSearchHitJsonConverter : JsonConverter<CodeSearchHit>
    {
        /// <summary>
        /// Deserializes json to <see cref="CodeSearchHit" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CodeSearchHit Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> project = default;
            Option<string?> filePath = default;
            Option<string?> snippet = default;
            Option<double?> rank = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "project":
                            project = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "file_path":
                            filePath = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "snippet":
                            snippet = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "rank":
                            rank = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (project.IsSet && project.Value == null)
                throw new ArgumentNullException(nameof(project), "Property is not nullable for class CodeSearchHit.");

            if (filePath.IsSet && filePath.Value == null)
                throw new ArgumentNullException(nameof(filePath), "Property is not nullable for class CodeSearchHit.");

            if (snippet.IsSet && snippet.Value == null)
                throw new ArgumentNullException(nameof(snippet), "Property is not nullable for class CodeSearchHit.");

            if (rank.IsSet && rank.Value == null)
                throw new ArgumentNullException(nameof(rank), "Property is not nullable for class CodeSearchHit.");

            return new CodeSearchHit(project, filePath, snippet, rank);
        }

        /// <summary>
        /// Serializes a <see cref="CodeSearchHit" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="codeSearchHit"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CodeSearchHit codeSearchHit, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, codeSearchHit, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CodeSearchHit" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="codeSearchHit"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CodeSearchHit codeSearchHit, JsonSerializerOptions jsonSerializerOptions)
        {
            if (codeSearchHit.ProjectOption.IsSet && codeSearchHit.Project == null)
                throw new ArgumentNullException(nameof(codeSearchHit.Project), "Property is required for class CodeSearchHit.");

            if (codeSearchHit.FilePathOption.IsSet && codeSearchHit.FilePath == null)
                throw new ArgumentNullException(nameof(codeSearchHit.FilePath), "Property is required for class CodeSearchHit.");

            if (codeSearchHit.SnippetOption.IsSet && codeSearchHit.Snippet == null)
                throw new ArgumentNullException(nameof(codeSearchHit.Snippet), "Property is required for class CodeSearchHit.");

            if (codeSearchHit.ProjectOption.IsSet)
                writer.WriteString("project", codeSearchHit.Project);

            if (codeSearchHit.FilePathOption.IsSet)
                writer.WriteString("file_path", codeSearchHit.FilePath);

            if (codeSearchHit.SnippetOption.IsSet)
                writer.WriteString("snippet", codeSearchHit.Snippet);

            if (codeSearchHit.RankOption.IsSet)
                writer.WriteNumber("rank", codeSearchHit.RankOption.Value!.Value);
        }
    }
}
