// <auto-generated>
/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AimeeKb.Client;

namespace AimeeKb.Model
{
    /// <summary>
    /// DocsManifestResponse
    /// </summary>
    public partial class DocsManifestResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocsManifestResponse" /> class.
        /// </summary>
        /// <param name="missing">missing</param>
        /// <param name="total">total</param>
        /// <param name="present">present</param>
        /// <param name="missingCount">missingCount</param>
        [JsonConstructor]
        public DocsManifestResponse(List<DocsManifestResponseMissingInner> missing, int total, int present, int missingCount)
        {
            Missing = missing;
            Total = total;
            Present = present;
            MissingCount = missingCount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Missing
        /// </summary>
        [JsonPropertyName("missing")]
        public List<DocsManifestResponseMissingInner> Missing { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [JsonPropertyName("total")]
        public int Total { get; set; }

        /// <summary>
        /// Gets or Sets Present
        /// </summary>
        [JsonPropertyName("present")]
        public int Present { get; set; }

        /// <summary>
        /// Gets or Sets MissingCount
        /// </summary>
        [JsonPropertyName("missing_count")]
        public int MissingCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocsManifestResponse {\n");
            sb.Append("  Missing: ").Append(Missing).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Present: ").Append(Present).Append("\n");
            sb.Append("  MissingCount: ").Append(MissingCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DocsManifestResponse" />
    /// </summary>
    public class DocsManifestResponseJsonConverter : JsonConverter<DocsManifestResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="DocsManifestResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DocsManifestResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<DocsManifestResponseMissingInner>?> missing = default;
            Option<int?> total = default;
            Option<int?> present = default;
            Option<int?> missingCount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "missing":
                            missing = new Option<List<DocsManifestResponseMissingInner>?>(JsonSerializer.Deserialize<List<DocsManifestResponseMissingInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "total":
                            total = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "present":
                            present = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "missing_count":
                            missingCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!missing.IsSet)
                throw new ArgumentException("Property is required for class DocsManifestResponse.", nameof(missing));

            if (!total.IsSet)
                throw new ArgumentException("Property is required for class DocsManifestResponse.", nameof(total));

            if (!present.IsSet)
                throw new ArgumentException("Property is required for class DocsManifestResponse.", nameof(present));

            if (!missingCount.IsSet)
                throw new ArgumentException("Property is required for class DocsManifestResponse.", nameof(missingCount));

            if (missing.IsSet && missing.Value == null)
                throw new ArgumentNullException(nameof(missing), "Property is not nullable for class DocsManifestResponse.");

            if (total.IsSet && total.Value == null)
                throw new ArgumentNullException(nameof(total), "Property is not nullable for class DocsManifestResponse.");

            if (present.IsSet && present.Value == null)
                throw new ArgumentNullException(nameof(present), "Property is not nullable for class DocsManifestResponse.");

            if (missingCount.IsSet && missingCount.Value == null)
                throw new ArgumentNullException(nameof(missingCount), "Property is not nullable for class DocsManifestResponse.");

            return new DocsManifestResponse(missing.Value!, total.Value!.Value!, present.Value!.Value!, missingCount.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="DocsManifestResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="docsManifestResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DocsManifestResponse docsManifestResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, docsManifestResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DocsManifestResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="docsManifestResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DocsManifestResponse docsManifestResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (docsManifestResponse.Missing == null)
                throw new ArgumentNullException(nameof(docsManifestResponse.Missing), "Property is required for class DocsManifestResponse.");

            writer.WritePropertyName("missing");
            JsonSerializer.Serialize(writer, docsManifestResponse.Missing, jsonSerializerOptions);
            writer.WriteNumber("total", docsManifestResponse.Total);

            writer.WriteNumber("present", docsManifestResponse.Present);

            writer.WriteNumber("missing_count", docsManifestResponse.MissingCount);
        }
    }
}
