// <auto-generated>
/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AimeeKb.Client;

namespace AimeeKb.Model
{
    /// <summary>
    /// DocsManifestRequest
    /// </summary>
    public partial class DocsManifestRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocsManifestRequest" /> class.
        /// </summary>
        /// <param name="docs">docs</param>
        /// <param name="scope">scope (default to &quot;global&quot;)</param>
        [JsonConstructor]
        public DocsManifestRequest(List<DocsManifestRequestDocsInner> docs, Option<string?> scope = default)
        {
            Docs = docs;
            ScopeOption = scope;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Docs
        /// </summary>
        [JsonPropertyName("docs")]
        public List<DocsManifestRequestDocsInner> Docs { get; set; }

        /// <summary>
        /// Used to track the state of Scope
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ScopeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Scope
        /// </summary>
        [JsonPropertyName("scope")]
        public string? Scope { get { return this.ScopeOption.Value; } set { this.ScopeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocsManifestRequest {\n");
            sb.Append("  Docs: ").Append(Docs).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DocsManifestRequest" />
    /// </summary>
    public class DocsManifestRequestJsonConverter : JsonConverter<DocsManifestRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="DocsManifestRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DocsManifestRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<DocsManifestRequestDocsInner>?> docs = default;
            Option<string?> scope = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "docs":
                            docs = new Option<List<DocsManifestRequestDocsInner>?>(JsonSerializer.Deserialize<List<DocsManifestRequestDocsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "scope":
                            scope = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!docs.IsSet)
                throw new ArgumentException("Property is required for class DocsManifestRequest.", nameof(docs));

            if (docs.IsSet && docs.Value == null)
                throw new ArgumentNullException(nameof(docs), "Property is not nullable for class DocsManifestRequest.");

            if (scope.IsSet && scope.Value == null)
                throw new ArgumentNullException(nameof(scope), "Property is not nullable for class DocsManifestRequest.");

            return new DocsManifestRequest(docs.Value!, scope);
        }

        /// <summary>
        /// Serializes a <see cref="DocsManifestRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="docsManifestRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DocsManifestRequest docsManifestRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, docsManifestRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DocsManifestRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="docsManifestRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DocsManifestRequest docsManifestRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (docsManifestRequest.Docs == null)
                throw new ArgumentNullException(nameof(docsManifestRequest.Docs), "Property is required for class DocsManifestRequest.");

            if (docsManifestRequest.ScopeOption.IsSet && docsManifestRequest.Scope == null)
                throw new ArgumentNullException(nameof(docsManifestRequest.Scope), "Property is required for class DocsManifestRequest.");

            writer.WritePropertyName("docs");
            JsonSerializer.Serialize(writer, docsManifestRequest.Docs, jsonSerializerOptions);
            if (docsManifestRequest.ScopeOption.IsSet)
                writer.WriteString("scope", docsManifestRequest.Scope);
        }
    }
}
