// <auto-generated>
/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AimeeKb.Client;

namespace AimeeKb.Model
{
    /// <summary>
    /// EntityProfileResponse
    /// </summary>
    public partial class EntityProfileResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EntityProfileResponse" /> class.
        /// </summary>
        /// <param name="entity">entity</param>
        /// <param name="kind">kind</param>
        /// <param name="summary">summary</param>
        /// <param name="facts">facts</param>
        /// <param name="tags">tags</param>
        /// <param name="updatedAt">updatedAt</param>
        [JsonConstructor]
        public EntityProfileResponse(Option<string?> entity = default, Option<string?> kind = default, Option<string?> summary = default, Option<List<string>?> facts = default, Option<List<string>?> tags = default, Option<string?> updatedAt = default)
        {
            EntityOption = entity;
            KindOption = kind;
            SummaryOption = summary;
            FactsOption = facts;
            TagsOption = tags;
            UpdatedAtOption = updatedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Entity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EntityOption { get; private set; }

        /// <summary>
        /// Gets or Sets Entity
        /// </summary>
        [JsonPropertyName("entity")]
        public string? Entity { get { return this.EntityOption.Value; } set { this.EntityOption = new(value); } }

        /// <summary>
        /// Used to track the state of Kind
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> KindOption { get; private set; }

        /// <summary>
        /// Gets or Sets Kind
        /// </summary>
        [JsonPropertyName("kind")]
        public string? Kind { get { return this.KindOption.Value; } set { this.KindOption = new(value); } }

        /// <summary>
        /// Used to track the state of Summary
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SummaryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Summary
        /// </summary>
        [JsonPropertyName("summary")]
        public string? Summary { get { return this.SummaryOption.Value; } set { this.SummaryOption = new(value); } }

        /// <summary>
        /// Used to track the state of Facts
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> FactsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Facts
        /// </summary>
        [JsonPropertyName("facts")]
        public List<string>? Facts { get { return this.FactsOption.Value; } set { this.FactsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<string>? Tags { get { return this.TagsOption.Value; } set { this.TagsOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UpdatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updated_at")]
        public string? UpdatedAt { get { return this.UpdatedAtOption.Value; } set { this.UpdatedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EntityProfileResponse {\n");
            sb.Append("  Entity: ").Append(Entity).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Summary: ").Append(Summary).Append("\n");
            sb.Append("  Facts: ").Append(Facts).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EntityProfileResponse" />
    /// </summary>
    public class EntityProfileResponseJsonConverter : JsonConverter<EntityProfileResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="EntityProfileResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EntityProfileResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> entity = default;
            Option<string?> kind = default;
            Option<string?> summary = default;
            Option<List<string>?> facts = default;
            Option<List<string>?> tags = default;
            Option<string?> updatedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "entity":
                            entity = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "kind":
                            kind = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "summary":
                            summary = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "facts":
                            facts = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "tags":
                            tags = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "updated_at":
                            updatedAt = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (entity.IsSet && entity.Value == null)
                throw new ArgumentNullException(nameof(entity), "Property is not nullable for class EntityProfileResponse.");

            if (kind.IsSet && kind.Value == null)
                throw new ArgumentNullException(nameof(kind), "Property is not nullable for class EntityProfileResponse.");

            if (summary.IsSet && summary.Value == null)
                throw new ArgumentNullException(nameof(summary), "Property is not nullable for class EntityProfileResponse.");

            if (facts.IsSet && facts.Value == null)
                throw new ArgumentNullException(nameof(facts), "Property is not nullable for class EntityProfileResponse.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class EntityProfileResponse.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class EntityProfileResponse.");

            return new EntityProfileResponse(entity, kind, summary, facts, tags, updatedAt);
        }

        /// <summary>
        /// Serializes a <see cref="EntityProfileResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="entityProfileResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EntityProfileResponse entityProfileResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, entityProfileResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EntityProfileResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="entityProfileResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EntityProfileResponse entityProfileResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (entityProfileResponse.EntityOption.IsSet && entityProfileResponse.Entity == null)
                throw new ArgumentNullException(nameof(entityProfileResponse.Entity), "Property is required for class EntityProfileResponse.");

            if (entityProfileResponse.KindOption.IsSet && entityProfileResponse.Kind == null)
                throw new ArgumentNullException(nameof(entityProfileResponse.Kind), "Property is required for class EntityProfileResponse.");

            if (entityProfileResponse.SummaryOption.IsSet && entityProfileResponse.Summary == null)
                throw new ArgumentNullException(nameof(entityProfileResponse.Summary), "Property is required for class EntityProfileResponse.");

            if (entityProfileResponse.FactsOption.IsSet && entityProfileResponse.Facts == null)
                throw new ArgumentNullException(nameof(entityProfileResponse.Facts), "Property is required for class EntityProfileResponse.");

            if (entityProfileResponse.TagsOption.IsSet && entityProfileResponse.Tags == null)
                throw new ArgumentNullException(nameof(entityProfileResponse.Tags), "Property is required for class EntityProfileResponse.");

            if (entityProfileResponse.UpdatedAtOption.IsSet && entityProfileResponse.UpdatedAt == null)
                throw new ArgumentNullException(nameof(entityProfileResponse.UpdatedAt), "Property is required for class EntityProfileResponse.");

            if (entityProfileResponse.EntityOption.IsSet)
                writer.WriteString("entity", entityProfileResponse.Entity);

            if (entityProfileResponse.KindOption.IsSet)
                writer.WriteString("kind", entityProfileResponse.Kind);

            if (entityProfileResponse.SummaryOption.IsSet)
                writer.WriteString("summary", entityProfileResponse.Summary);

            if (entityProfileResponse.FactsOption.IsSet)
            {
                writer.WritePropertyName("facts");
                JsonSerializer.Serialize(writer, entityProfileResponse.Facts, jsonSerializerOptions);
            }
            if (entityProfileResponse.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, entityProfileResponse.Tags, jsonSerializerOptions);
            }
            if (entityProfileResponse.UpdatedAtOption.IsSet)
                writer.WriteString("updated_at", entityProfileResponse.UpdatedAt);
        }
    }
}
