// <auto-generated>
/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AimeeKb.Client;

namespace AimeeKb.Model
{
    /// <summary>
    /// IngestStatusResponseQueue
    /// </summary>
    public partial class IngestStatusResponseQueue : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IngestStatusResponseQueue" /> class.
        /// </summary>
        /// <param name="pending">pending</param>
        /// <param name="running">running</param>
        /// <param name="doneLast24h">doneLast24h</param>
        /// <param name="failedLast24h">failedLast24h</param>
        [JsonConstructor]
        public IngestStatusResponseQueue(Option<int?> pending = default, Option<int?> running = default, Option<int?> doneLast24h = default, Option<int?> failedLast24h = default)
        {
            PendingOption = pending;
            RunningOption = running;
            DoneLast24hOption = doneLast24h;
            FailedLast24hOption = failedLast24h;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Pending
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PendingOption { get; private set; }

        /// <summary>
        /// Gets or Sets Pending
        /// </summary>
        [JsonPropertyName("pending")]
        public int? Pending { get { return this.PendingOption.Value; } set { this.PendingOption = new(value); } }

        /// <summary>
        /// Used to track the state of Running
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> RunningOption { get; private set; }

        /// <summary>
        /// Gets or Sets Running
        /// </summary>
        [JsonPropertyName("running")]
        public int? Running { get { return this.RunningOption.Value; } set { this.RunningOption = new(value); } }

        /// <summary>
        /// Used to track the state of DoneLast24h
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> DoneLast24hOption { get; private set; }

        /// <summary>
        /// Gets or Sets DoneLast24h
        /// </summary>
        [JsonPropertyName("done_last_24h")]
        public int? DoneLast24h { get { return this.DoneLast24hOption.Value; } set { this.DoneLast24hOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailedLast24h
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FailedLast24hOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailedLast24h
        /// </summary>
        [JsonPropertyName("failed_last_24h")]
        public int? FailedLast24h { get { return this.FailedLast24hOption.Value; } set { this.FailedLast24hOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IngestStatusResponseQueue {\n");
            sb.Append("  Pending: ").Append(Pending).Append("\n");
            sb.Append("  Running: ").Append(Running).Append("\n");
            sb.Append("  DoneLast24h: ").Append(DoneLast24h).Append("\n");
            sb.Append("  FailedLast24h: ").Append(FailedLast24h).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IngestStatusResponseQueue" />
    /// </summary>
    public class IngestStatusResponseQueueJsonConverter : JsonConverter<IngestStatusResponseQueue>
    {
        /// <summary>
        /// Deserializes json to <see cref="IngestStatusResponseQueue" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override IngestStatusResponseQueue Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> pending = default;
            Option<int?> running = default;
            Option<int?> doneLast24h = default;
            Option<int?> failedLast24h = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "pending":
                            pending = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "running":
                            running = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "done_last_24h":
                            doneLast24h = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "failed_last_24h":
                            failedLast24h = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (pending.IsSet && pending.Value == null)
                throw new ArgumentNullException(nameof(pending), "Property is not nullable for class IngestStatusResponseQueue.");

            if (running.IsSet && running.Value == null)
                throw new ArgumentNullException(nameof(running), "Property is not nullable for class IngestStatusResponseQueue.");

            if (doneLast24h.IsSet && doneLast24h.Value == null)
                throw new ArgumentNullException(nameof(doneLast24h), "Property is not nullable for class IngestStatusResponseQueue.");

            if (failedLast24h.IsSet && failedLast24h.Value == null)
                throw new ArgumentNullException(nameof(failedLast24h), "Property is not nullable for class IngestStatusResponseQueue.");

            return new IngestStatusResponseQueue(pending, running, doneLast24h, failedLast24h);
        }

        /// <summary>
        /// Serializes a <see cref="IngestStatusResponseQueue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ingestStatusResponseQueue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, IngestStatusResponseQueue ingestStatusResponseQueue, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ingestStatusResponseQueue, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="IngestStatusResponseQueue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ingestStatusResponseQueue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, IngestStatusResponseQueue ingestStatusResponseQueue, JsonSerializerOptions jsonSerializerOptions)
        {
            if (ingestStatusResponseQueue.PendingOption.IsSet)
                writer.WriteNumber("pending", ingestStatusResponseQueue.PendingOption.Value!.Value);

            if (ingestStatusResponseQueue.RunningOption.IsSet)
                writer.WriteNumber("running", ingestStatusResponseQueue.RunningOption.Value!.Value);

            if (ingestStatusResponseQueue.DoneLast24hOption.IsSet)
                writer.WriteNumber("done_last_24h", ingestStatusResponseQueue.DoneLast24hOption.Value!.Value);

            if (ingestStatusResponseQueue.FailedLast24hOption.IsSet)
                writer.WriteNumber("failed_last_24h", ingestStatusResponseQueue.FailedLast24hOption.Value!.Value);
        }
    }
}
