// <auto-generated>
/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AimeeKb.Client;

namespace AimeeKb.Model
{
    /// <summary>
    /// SearchHit
    /// </summary>
    public partial class SearchHit : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchHit" /> class.
        /// </summary>
        /// <param name="artifactId">artifactId</param>
        /// <param name="score">score</param>
        /// <param name="kind">kind</param>
        /// <param name="excerpt">excerpt</param>
        /// <param name="citations">citations</param>
        [JsonConstructor]
        public SearchHit(Option<string?> artifactId = default, Option<double?> score = default, Option<string?> kind = default, Option<string?> excerpt = default, Option<List<SearchHitCitationsInner>?> citations = default)
        {
            ArtifactIdOption = artifactId;
            ScoreOption = score;
            KindOption = kind;
            ExcerptOption = excerpt;
            CitationsOption = citations;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ArtifactId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ArtifactIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ArtifactId
        /// </summary>
        [JsonPropertyName("artifact_id")]
        public string? ArtifactId { get { return this.ArtifactIdOption.Value; } set { this.ArtifactIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Score
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> ScoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets Score
        /// </summary>
        [JsonPropertyName("score")]
        public double? Score { get { return this.ScoreOption.Value; } set { this.ScoreOption = new(value); } }

        /// <summary>
        /// Used to track the state of Kind
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> KindOption { get; private set; }

        /// <summary>
        /// Gets or Sets Kind
        /// </summary>
        [JsonPropertyName("kind")]
        public string? Kind { get { return this.KindOption.Value; } set { this.KindOption = new(value); } }

        /// <summary>
        /// Used to track the state of Excerpt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExcerptOption { get; private set; }

        /// <summary>
        /// Gets or Sets Excerpt
        /// </summary>
        [JsonPropertyName("excerpt")]
        public string? Excerpt { get { return this.ExcerptOption.Value; } set { this.ExcerptOption = new(value); } }

        /// <summary>
        /// Used to track the state of Citations
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<SearchHitCitationsInner>?> CitationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Citations
        /// </summary>
        [JsonPropertyName("citations")]
        public List<SearchHitCitationsInner>? Citations { get { return this.CitationsOption.Value; } set { this.CitationsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchHit {\n");
            sb.Append("  ArtifactId: ").Append(ArtifactId).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Excerpt: ").Append(Excerpt).Append("\n");
            sb.Append("  Citations: ").Append(Citations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchHit" />
    /// </summary>
    public class SearchHitJsonConverter : JsonConverter<SearchHit>
    {
        /// <summary>
        /// Deserializes json to <see cref="SearchHit" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SearchHit Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> artifactId = default;
            Option<double?> score = default;
            Option<string?> kind = default;
            Option<string?> excerpt = default;
            Option<List<SearchHitCitationsInner>?> citations = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "artifact_id":
                            artifactId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "score":
                            score = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "kind":
                            kind = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "excerpt":
                            excerpt = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "citations":
                            citations = new Option<List<SearchHitCitationsInner>?>(JsonSerializer.Deserialize<List<SearchHitCitationsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (artifactId.IsSet && artifactId.Value == null)
                throw new ArgumentNullException(nameof(artifactId), "Property is not nullable for class SearchHit.");

            if (score.IsSet && score.Value == null)
                throw new ArgumentNullException(nameof(score), "Property is not nullable for class SearchHit.");

            if (kind.IsSet && kind.Value == null)
                throw new ArgumentNullException(nameof(kind), "Property is not nullable for class SearchHit.");

            if (excerpt.IsSet && excerpt.Value == null)
                throw new ArgumentNullException(nameof(excerpt), "Property is not nullable for class SearchHit.");

            if (citations.IsSet && citations.Value == null)
                throw new ArgumentNullException(nameof(citations), "Property is not nullable for class SearchHit.");

            return new SearchHit(artifactId, score, kind, excerpt, citations);
        }

        /// <summary>
        /// Serializes a <see cref="SearchHit" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchHit"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SearchHit searchHit, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, searchHit, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SearchHit" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchHit"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SearchHit searchHit, JsonSerializerOptions jsonSerializerOptions)
        {
            if (searchHit.ArtifactIdOption.IsSet && searchHit.ArtifactId == null)
                throw new ArgumentNullException(nameof(searchHit.ArtifactId), "Property is required for class SearchHit.");

            if (searchHit.KindOption.IsSet && searchHit.Kind == null)
                throw new ArgumentNullException(nameof(searchHit.Kind), "Property is required for class SearchHit.");

            if (searchHit.ExcerptOption.IsSet && searchHit.Excerpt == null)
                throw new ArgumentNullException(nameof(searchHit.Excerpt), "Property is required for class SearchHit.");

            if (searchHit.CitationsOption.IsSet && searchHit.Citations == null)
                throw new ArgumentNullException(nameof(searchHit.Citations), "Property is required for class SearchHit.");

            if (searchHit.ArtifactIdOption.IsSet)
                writer.WriteString("artifact_id", searchHit.ArtifactId);

            if (searchHit.ScoreOption.IsSet)
                writer.WriteNumber("score", searchHit.ScoreOption.Value!.Value);

            if (searchHit.KindOption.IsSet)
                writer.WriteString("kind", searchHit.Kind);

            if (searchHit.ExcerptOption.IsSet)
                writer.WriteString("excerpt", searchHit.Excerpt);

            if (searchHit.CitationsOption.IsSet)
            {
                writer.WritePropertyName("citations");
                JsonSerializer.Serialize(writer, searchHit.Citations, jsonSerializerOptions);
            }
        }
    }
}
