/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "aimee_kb/model/CodeBuildRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CodeBuildRequest::CodeBuildRequest()
{
    m_Path = utility::conversions::to_string_t("");
    m_PathIsSet = false;
    m_Project = utility::conversions::to_string_t("");
    m_ProjectIsSet = false;
    m_Embedding_command = utility::conversions::to_string_t("");
    m_Embedding_commandIsSet = false;
    m_Force = false;
    m_ForceIsSet = false;
}

CodeBuildRequest::~CodeBuildRequest()
{
}

void CodeBuildRequest::validate()
{
    // TODO: implement validation
}

web::json::value CodeBuildRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PathIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("path"))] = ModelBase::toJson(m_Path);
    }
    if(m_ProjectIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("project"))] = ModelBase::toJson(m_Project);
    }
    if(m_Embedding_commandIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("embedding_command"))] = ModelBase::toJson(m_Embedding_command);
    }
    if(m_ForceIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("force"))] = ModelBase::toJson(m_Force);
    }

    return val;
}

bool CodeBuildRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("path"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("path")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPath;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPath);
            setPath(refVal_setPath);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("project"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("project")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProject;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProject);
            setProject(refVal_setProject);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("embedding_command"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("embedding_command")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmbeddingCommand;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmbeddingCommand);
            setEmbeddingCommand(refVal_setEmbeddingCommand);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("force"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("force")));
        if(!fieldValue.is_null())
        {
            bool refVal_setForce;
            ok &= ModelBase::fromJson(fieldValue, refVal_setForce);
            setForce(refVal_setForce);
            
        }
    }
    return ok;
}

void CodeBuildRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PathIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("path")), m_Path));
    }
    if(m_ProjectIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("project")), m_Project));
    }
    if(m_Embedding_commandIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("embedding_command")), m_Embedding_command));
    }
    if(m_ForceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("force")), m_Force));
    }
}

bool CodeBuildRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("path"))))
    {
        utility::string_t refVal_setPath;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("path"))), refVal_setPath );
        setPath(refVal_setPath);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("project"))))
    {
        utility::string_t refVal_setProject;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("project"))), refVal_setProject );
        setProject(refVal_setProject);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("embedding_command"))))
    {
        utility::string_t refVal_setEmbeddingCommand;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("embedding_command"))), refVal_setEmbeddingCommand );
        setEmbeddingCommand(refVal_setEmbeddingCommand);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("force"))))
    {
        bool refVal_setForce;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("force"))), refVal_setForce );
        setForce(refVal_setForce);
    }
    return ok;
}


utility::string_t CodeBuildRequest::getPath() const
{
    return m_Path;
}


void CodeBuildRequest::setPath(const utility::string_t& value)
{
    m_Path = value;
    m_PathIsSet = true;
}

bool CodeBuildRequest::pathIsSet() const
{
    return m_PathIsSet;
}

void CodeBuildRequest::unsetPath()
{
    m_PathIsSet = false;
}
utility::string_t CodeBuildRequest::getProject() const
{
    return m_Project;
}


void CodeBuildRequest::setProject(const utility::string_t& value)
{
    m_Project = value;
    m_ProjectIsSet = true;
}

bool CodeBuildRequest::projectIsSet() const
{
    return m_ProjectIsSet;
}

void CodeBuildRequest::unsetProject()
{
    m_ProjectIsSet = false;
}
utility::string_t CodeBuildRequest::getEmbeddingCommand() const
{
    return m_Embedding_command;
}


void CodeBuildRequest::setEmbeddingCommand(const utility::string_t& value)
{
    m_Embedding_command = value;
    m_Embedding_commandIsSet = true;
}

bool CodeBuildRequest::embeddingCommandIsSet() const
{
    return m_Embedding_commandIsSet;
}

void CodeBuildRequest::unsetEmbedding_command()
{
    m_Embedding_commandIsSet = false;
}
bool CodeBuildRequest::isForce() const
{
    return m_Force;
}

void CodeBuildRequest::setForce(bool value)
{
    m_Force = value;
    m_ForceIsSet = true;
}

bool CodeBuildRequest::forceIsSet() const
{
    return m_ForceIsSet;
}

void CodeBuildRequest::unsetForce()
{
    m_ForceIsSet = false;
}

}
}
}
}


