/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "aimee_kb/model/DrainResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

DrainResponse::DrainResponse()
{
    m_StateIsSet = false;
    m_Processed = 0;
    m_ProcessedIsSet = false;
    m_Pending = 0;
    m_PendingIsSet = false;
    m_Running = 0;
    m_RunningIsSet = false;
    m_Done = 0;
    m_DoneIsSet = false;
    m_Failed = 0;
    m_FailedIsSet = false;
    m_Total = 0;
    m_TotalIsSet = false;
}

DrainResponse::~DrainResponse()
{
}

void DrainResponse::validate()
{
    // TODO: implement validation
}

web::json::value DrainResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StateIsSet)
    {
        
        utility::string_t refVal = fromStateEnum(m_State);
        val[utility::conversions::to_string_t(_XPLATSTR("state"))] = ModelBase::toJson(refVal);
        
    }
    if(m_ProcessedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("processed"))] = ModelBase::toJson(m_Processed);
    }
    if(m_PendingIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("pending"))] = ModelBase::toJson(m_Pending);
    }
    if(m_RunningIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("running"))] = ModelBase::toJson(m_Running);
    }
    if(m_DoneIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("done"))] = ModelBase::toJson(m_Done);
    }
    if(m_FailedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("failed"))] = ModelBase::toJson(m_Failed);
    }
    if(m_TotalIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("total"))] = ModelBase::toJson(m_Total);
    }

    return val;
}

bool DrainResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("state"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("state")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setState;
            ok &= ModelBase::fromJson(fieldValue, refVal_setState);
            
            setState(toStateEnum(refVal_setState));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("processed"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("processed")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setProcessed;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProcessed);
            setProcessed(refVal_setProcessed);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("pending"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("pending")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPending;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPending);
            setPending(refVal_setPending);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("running"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("running")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setRunning;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRunning);
            setRunning(refVal_setRunning);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("done"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("done")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setDone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDone);
            setDone(refVal_setDone);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("failed"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("failed")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setFailed;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFailed);
            setFailed(refVal_setFailed);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("total"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("total")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotal);
            setTotal(refVal_setTotal);
            
        }
    }
    return ok;
}

void DrainResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("state")), fromStateEnum(m_State)));
    }
    if(m_ProcessedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("processed")), m_Processed));
    }
    if(m_PendingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("pending")), m_Pending));
    }
    if(m_RunningIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("running")), m_Running));
    }
    if(m_DoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("done")), m_Done));
    }
    if(m_FailedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("failed")), m_Failed));
    }
    if(m_TotalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("total")), m_Total));
    }
}

bool DrainResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("state"))))
    {
        utility::string_t refVal_setState;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("state"))), refVal_setState );
        setState(toStateEnum(refVal_setState));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("processed"))))
    {
        int32_t refVal_setProcessed;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("processed"))), refVal_setProcessed );
        setProcessed(refVal_setProcessed);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("pending"))))
    {
        int32_t refVal_setPending;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("pending"))), refVal_setPending );
        setPending(refVal_setPending);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("running"))))
    {
        int32_t refVal_setRunning;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("running"))), refVal_setRunning );
        setRunning(refVal_setRunning);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("done"))))
    {
        int32_t refVal_setDone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("done"))), refVal_setDone );
        setDone(refVal_setDone);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("failed"))))
    {
        int32_t refVal_setFailed;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("failed"))), refVal_setFailed );
        setFailed(refVal_setFailed);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("total"))))
    {
        int32_t refVal_setTotal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("total"))), refVal_setTotal );
        setTotal(refVal_setTotal);
    }
    return ok;
}

DrainResponse::StateEnum DrainResponse::toStateEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("idle")) {
        return StateEnum::IDLE;
    }
    
    if (value == utility::conversions::to_string_t("running")) {
        return StateEnum::RUNNING;
    }
    
    if (value == utility::conversions::to_string_t("failed")) {
        return StateEnum::FAILED;
    }
    
    throw std::invalid_argument("Invalid value for conversion to StateEnum");
}


const utility::string_t DrainResponse::fromStateEnum(const StateEnum value) const
{
    switch(value)
    {
        
        case StateEnum::IDLE: return utility::conversions::to_string_t("idle");
        
        case StateEnum::RUNNING: return utility::conversions::to_string_t("running");
        
        case StateEnum::FAILED: return utility::conversions::to_string_t("failed");
        
    }
}


DrainResponse::StateEnum DrainResponse::getState() const
{
    return m_State;
}


void DrainResponse::setState(const StateEnum value)
{
    m_State = value;
    m_StateIsSet = true;
}

bool DrainResponse::stateIsSet() const
{
    return m_StateIsSet;
}

void DrainResponse::unsetState()
{
    m_StateIsSet = false;
}
int32_t DrainResponse::getProcessed() const
{
    return m_Processed;
}

void DrainResponse::setProcessed(int32_t value)
{
    m_Processed = value;
    m_ProcessedIsSet = true;
}

bool DrainResponse::processedIsSet() const
{
    return m_ProcessedIsSet;
}

void DrainResponse::unsetProcessed()
{
    m_ProcessedIsSet = false;
}
int32_t DrainResponse::getPending() const
{
    return m_Pending;
}

void DrainResponse::setPending(int32_t value)
{
    m_Pending = value;
    m_PendingIsSet = true;
}

bool DrainResponse::pendingIsSet() const
{
    return m_PendingIsSet;
}

void DrainResponse::unsetPending()
{
    m_PendingIsSet = false;
}
int32_t DrainResponse::getRunning() const
{
    return m_Running;
}

void DrainResponse::setRunning(int32_t value)
{
    m_Running = value;
    m_RunningIsSet = true;
}

bool DrainResponse::runningIsSet() const
{
    return m_RunningIsSet;
}

void DrainResponse::unsetRunning()
{
    m_RunningIsSet = false;
}
int32_t DrainResponse::getDone() const
{
    return m_Done;
}

void DrainResponse::setDone(int32_t value)
{
    m_Done = value;
    m_DoneIsSet = true;
}

bool DrainResponse::doneIsSet() const
{
    return m_DoneIsSet;
}

void DrainResponse::unsetDone()
{
    m_DoneIsSet = false;
}
int32_t DrainResponse::getFailed() const
{
    return m_Failed;
}

void DrainResponse::setFailed(int32_t value)
{
    m_Failed = value;
    m_FailedIsSet = true;
}

bool DrainResponse::failedIsSet() const
{
    return m_FailedIsSet;
}

void DrainResponse::unsetFailed()
{
    m_FailedIsSet = false;
}
int32_t DrainResponse::getTotal() const
{
    return m_Total;
}

void DrainResponse::setTotal(int32_t value)
{
    m_Total = value;
    m_TotalIsSet = true;
}

bool DrainResponse::totalIsSet() const
{
    return m_TotalIsSet;
}

void DrainResponse::unsetTotal()
{
    m_TotalIsSet = false;
}

}
}
}
}


