/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "aimee_kb/model/DrainRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

DrainRequest::DrainRequest()
{
    m_Embedding_command = utility::conversions::to_string_t("");
    m_Embedding_commandIsSet = false;
    m_Timeout = 0;
    m_TimeoutIsSet = false;
}

DrainRequest::~DrainRequest()
{
}

void DrainRequest::validate()
{
    // TODO: implement validation
}

web::json::value DrainRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Embedding_commandIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("embedding_command"))] = ModelBase::toJson(m_Embedding_command);
    }
    if(m_TimeoutIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("timeout"))] = ModelBase::toJson(m_Timeout);
    }

    return val;
}

bool DrainRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("embedding_command"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("embedding_command")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmbeddingCommand;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmbeddingCommand);
            setEmbeddingCommand(refVal_setEmbeddingCommand);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("timeout"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("timeout")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTimeout;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimeout);
            setTimeout(refVal_setTimeout);
            
        }
    }
    return ok;
}

void DrainRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Embedding_commandIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("embedding_command")), m_Embedding_command));
    }
    if(m_TimeoutIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("timeout")), m_Timeout));
    }
}

bool DrainRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("embedding_command"))))
    {
        utility::string_t refVal_setEmbeddingCommand;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("embedding_command"))), refVal_setEmbeddingCommand );
        setEmbeddingCommand(refVal_setEmbeddingCommand);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("timeout"))))
    {
        int32_t refVal_setTimeout;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("timeout"))), refVal_setTimeout );
        setTimeout(refVal_setTimeout);
    }
    return ok;
}


utility::string_t DrainRequest::getEmbeddingCommand() const
{
    return m_Embedding_command;
}


void DrainRequest::setEmbeddingCommand(const utility::string_t& value)
{
    m_Embedding_command = value;
    m_Embedding_commandIsSet = true;
}

bool DrainRequest::embeddingCommandIsSet() const
{
    return m_Embedding_commandIsSet;
}

void DrainRequest::unsetEmbedding_command()
{
    m_Embedding_commandIsSet = false;
}
int32_t DrainRequest::getTimeout() const
{
    return m_Timeout;
}

void DrainRequest::setTimeout(int32_t value)
{
    m_Timeout = value;
    m_TimeoutIsSet = true;
}

bool DrainRequest::timeoutIsSet() const
{
    return m_TimeoutIsSet;
}

void DrainRequest::unsetTimeout()
{
    m_TimeoutIsSet = false;
}

}
}
}
}


