/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "aimee_kb/model/EntityProfileResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

EntityProfileResponse::EntityProfileResponse()
{
    m_Entity = utility::conversions::to_string_t("");
    m_EntityIsSet = false;
    m_Kind = utility::conversions::to_string_t("");
    m_KindIsSet = false;
    m_Summary = utility::conversions::to_string_t("");
    m_SummaryIsSet = false;
    m_FactsIsSet = false;
    m_TagsIsSet = false;
    m_Updated_at = utility::conversions::to_string_t("");
    m_Updated_atIsSet = false;
}

EntityProfileResponse::~EntityProfileResponse()
{
}

void EntityProfileResponse::validate()
{
    // TODO: implement validation
}

web::json::value EntityProfileResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_EntityIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("entity"))] = ModelBase::toJson(m_Entity);
    }
    if(m_KindIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("kind"))] = ModelBase::toJson(m_Kind);
    }
    if(m_SummaryIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("summary"))] = ModelBase::toJson(m_Summary);
    }
    if(m_FactsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("facts"))] = ModelBase::toJson(m_Facts);
    }
    if(m_TagsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tags"))] = ModelBase::toJson(m_Tags);
    }
    if(m_Updated_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updated_at"))] = ModelBase::toJson(m_Updated_at);
    }

    return val;
}

bool EntityProfileResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("entity"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("entity")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEntity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEntity);
            setEntity(refVal_setEntity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("kind"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("kind")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setKind;
            ok &= ModelBase::fromJson(fieldValue, refVal_setKind);
            setKind(refVal_setKind);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("summary"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("summary")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSummary;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSummary);
            setSummary(refVal_setSummary);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("facts"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("facts")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setFacts;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFacts);
            setFacts(refVal_setFacts);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tags")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setTags;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTags);
            setTags(refVal_setTags);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updated_at")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    return ok;
}

void EntityProfileResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_EntityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("entity")), m_Entity));
    }
    if(m_KindIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("kind")), m_Kind));
    }
    if(m_SummaryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("summary")), m_Summary));
    }
    if(m_FactsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("facts")), m_Facts));
    }
    if(m_TagsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tags")), m_Tags));
    }
    if(m_Updated_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updated_at")), m_Updated_at));
    }
}

bool EntityProfileResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("entity"))))
    {
        utility::string_t refVal_setEntity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("entity"))), refVal_setEntity );
        setEntity(refVal_setEntity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("kind"))))
    {
        utility::string_t refVal_setKind;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("kind"))), refVal_setKind );
        setKind(refVal_setKind);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("summary"))))
    {
        utility::string_t refVal_setSummary;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("summary"))), refVal_setSummary );
        setSummary(refVal_setSummary);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("facts"))))
    {
        std::vector<utility::string_t> refVal_setFacts;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("facts"))), refVal_setFacts );
        setFacts(refVal_setFacts);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        std::vector<utility::string_t> refVal_setTags;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tags"))), refVal_setTags );
        setTags(refVal_setTags);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        utility::string_t refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    return ok;
}


utility::string_t EntityProfileResponse::getEntity() const
{
    return m_Entity;
}


void EntityProfileResponse::setEntity(const utility::string_t& value)
{
    m_Entity = value;
    m_EntityIsSet = true;
}

bool EntityProfileResponse::entityIsSet() const
{
    return m_EntityIsSet;
}

void EntityProfileResponse::unsetEntity()
{
    m_EntityIsSet = false;
}
utility::string_t EntityProfileResponse::getKind() const
{
    return m_Kind;
}


void EntityProfileResponse::setKind(const utility::string_t& value)
{
    m_Kind = value;
    m_KindIsSet = true;
}

bool EntityProfileResponse::kindIsSet() const
{
    return m_KindIsSet;
}

void EntityProfileResponse::unsetKind()
{
    m_KindIsSet = false;
}
utility::string_t EntityProfileResponse::getSummary() const
{
    return m_Summary;
}


void EntityProfileResponse::setSummary(const utility::string_t& value)
{
    m_Summary = value;
    m_SummaryIsSet = true;
}

bool EntityProfileResponse::summaryIsSet() const
{
    return m_SummaryIsSet;
}

void EntityProfileResponse::unsetSummary()
{
    m_SummaryIsSet = false;
}
std::vector<utility::string_t> EntityProfileResponse::getFacts() const
{
    return m_Facts;
}


void EntityProfileResponse::setFacts(const std::vector<utility::string_t>& value)
{
    m_Facts = value;
    m_FactsIsSet = true;
}

bool EntityProfileResponse::factsIsSet() const
{
    return m_FactsIsSet;
}

void EntityProfileResponse::unsetFacts()
{
    m_FactsIsSet = false;
}
std::vector<utility::string_t> EntityProfileResponse::getTags() const
{
    return m_Tags;
}


void EntityProfileResponse::setTags(const std::vector<utility::string_t>& value)
{
    m_Tags = value;
    m_TagsIsSet = true;
}

bool EntityProfileResponse::tagsIsSet() const
{
    return m_TagsIsSet;
}

void EntityProfileResponse::unsetTags()
{
    m_TagsIsSet = false;
}
utility::string_t EntityProfileResponse::getUpdatedAt() const
{
    return m_Updated_at;
}


void EntityProfileResponse::setUpdatedAt(const utility::string_t& value)
{
    m_Updated_at = value;
    m_Updated_atIsSet = true;
}

bool EntityProfileResponse::updatedAtIsSet() const
{
    return m_Updated_atIsSet;
}

void EntityProfileResponse::unsetUpdated_at()
{
    m_Updated_atIsSet = false;
}

}
}
}
}


