/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "aimee_kb/model/EntitySearchRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

EntitySearchRequest::EntitySearchRequest()
{
    m_Query = utility::conversions::to_string_t("");
    m_QueryIsSet = false;
    m_Limit = 0;
    m_LimitIsSet = false;
    m_Cursor = utility::conversions::to_string_t("");
    m_CursorIsSet = false;
}

EntitySearchRequest::~EntitySearchRequest()
{
}

void EntitySearchRequest::validate()
{
    // TODO: implement validation
}

web::json::value EntitySearchRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_QueryIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("query"))] = ModelBase::toJson(m_Query);
    }
    if(m_LimitIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("limit"))] = ModelBase::toJson(m_Limit);
    }
    if(m_CursorIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("cursor"))] = ModelBase::toJson(m_Cursor);
    }

    return val;
}

bool EntitySearchRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("query"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("query")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setQuery;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQuery);
            setQuery(refVal_setQuery);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("limit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("limit")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setLimit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLimit);
            setLimit(refVal_setLimit);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("cursor"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("cursor")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCursor;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCursor);
            setCursor(refVal_setCursor);
            
        }
    }
    return ok;
}

void EntitySearchRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_QueryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("query")), m_Query));
    }
    if(m_LimitIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("limit")), m_Limit));
    }
    if(m_CursorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("cursor")), m_Cursor));
    }
}

bool EntitySearchRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("query"))))
    {
        utility::string_t refVal_setQuery;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("query"))), refVal_setQuery );
        setQuery(refVal_setQuery);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("limit"))))
    {
        int32_t refVal_setLimit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("limit"))), refVal_setLimit );
        setLimit(refVal_setLimit);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("cursor"))))
    {
        utility::string_t refVal_setCursor;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("cursor"))), refVal_setCursor );
        setCursor(refVal_setCursor);
    }
    return ok;
}


utility::string_t EntitySearchRequest::getQuery() const
{
    return m_Query;
}


void EntitySearchRequest::setQuery(const utility::string_t& value)
{
    m_Query = value;
    m_QueryIsSet = true;
}

bool EntitySearchRequest::queryIsSet() const
{
    return m_QueryIsSet;
}

void EntitySearchRequest::unsetQuery()
{
    m_QueryIsSet = false;
}
int32_t EntitySearchRequest::getLimit() const
{
    return m_Limit;
}

void EntitySearchRequest::setLimit(int32_t value)
{
    m_Limit = value;
    m_LimitIsSet = true;
}

bool EntitySearchRequest::limitIsSet() const
{
    return m_LimitIsSet;
}

void EntitySearchRequest::unsetLimit()
{
    m_LimitIsSet = false;
}
utility::string_t EntitySearchRequest::getCursor() const
{
    return m_Cursor;
}


void EntitySearchRequest::setCursor(const utility::string_t& value)
{
    m_Cursor = value;
    m_CursorIsSet = true;
}

bool EntitySearchRequest::cursorIsSet() const
{
    return m_CursorIsSet;
}

void EntitySearchRequest::unsetCursor()
{
    m_CursorIsSet = false;
}

}
}
}
}


