/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "aimee_kb/model/IngestStatusResponse_queue.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

IngestStatusResponse_queue::IngestStatusResponse_queue()
{
    m_Pending = 0;
    m_PendingIsSet = false;
    m_Running = 0;
    m_RunningIsSet = false;
    m_Done_last_24h = 0;
    m_Done_last_24hIsSet = false;
    m_Failed_last_24h = 0;
    m_Failed_last_24hIsSet = false;
}

IngestStatusResponse_queue::~IngestStatusResponse_queue()
{
}

void IngestStatusResponse_queue::validate()
{
    // TODO: implement validation
}

web::json::value IngestStatusResponse_queue::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PendingIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("pending"))] = ModelBase::toJson(m_Pending);
    }
    if(m_RunningIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("running"))] = ModelBase::toJson(m_Running);
    }
    if(m_Done_last_24hIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("done_last_24h"))] = ModelBase::toJson(m_Done_last_24h);
    }
    if(m_Failed_last_24hIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("failed_last_24h"))] = ModelBase::toJson(m_Failed_last_24h);
    }

    return val;
}

bool IngestStatusResponse_queue::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("pending"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("pending")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPending;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPending);
            setPending(refVal_setPending);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("running"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("running")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setRunning;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRunning);
            setRunning(refVal_setRunning);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("done_last_24h"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("done_last_24h")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setDoneLast24h;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDoneLast24h);
            setDoneLast24h(refVal_setDoneLast24h);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("failed_last_24h"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("failed_last_24h")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setFailedLast24h;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFailedLast24h);
            setFailedLast24h(refVal_setFailedLast24h);
            
        }
    }
    return ok;
}

void IngestStatusResponse_queue::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PendingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("pending")), m_Pending));
    }
    if(m_RunningIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("running")), m_Running));
    }
    if(m_Done_last_24hIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("done_last_24h")), m_Done_last_24h));
    }
    if(m_Failed_last_24hIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("failed_last_24h")), m_Failed_last_24h));
    }
}

bool IngestStatusResponse_queue::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("pending"))))
    {
        int32_t refVal_setPending;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("pending"))), refVal_setPending );
        setPending(refVal_setPending);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("running"))))
    {
        int32_t refVal_setRunning;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("running"))), refVal_setRunning );
        setRunning(refVal_setRunning);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("done_last_24h"))))
    {
        int32_t refVal_setDoneLast24h;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("done_last_24h"))), refVal_setDoneLast24h );
        setDoneLast24h(refVal_setDoneLast24h);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("failed_last_24h"))))
    {
        int32_t refVal_setFailedLast24h;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("failed_last_24h"))), refVal_setFailedLast24h );
        setFailedLast24h(refVal_setFailedLast24h);
    }
    return ok;
}


int32_t IngestStatusResponse_queue::getPending() const
{
    return m_Pending;
}

void IngestStatusResponse_queue::setPending(int32_t value)
{
    m_Pending = value;
    m_PendingIsSet = true;
}

bool IngestStatusResponse_queue::pendingIsSet() const
{
    return m_PendingIsSet;
}

void IngestStatusResponse_queue::unsetPending()
{
    m_PendingIsSet = false;
}
int32_t IngestStatusResponse_queue::getRunning() const
{
    return m_Running;
}

void IngestStatusResponse_queue::setRunning(int32_t value)
{
    m_Running = value;
    m_RunningIsSet = true;
}

bool IngestStatusResponse_queue::runningIsSet() const
{
    return m_RunningIsSet;
}

void IngestStatusResponse_queue::unsetRunning()
{
    m_RunningIsSet = false;
}
int32_t IngestStatusResponse_queue::getDoneLast24h() const
{
    return m_Done_last_24h;
}

void IngestStatusResponse_queue::setDoneLast24h(int32_t value)
{
    m_Done_last_24h = value;
    m_Done_last_24hIsSet = true;
}

bool IngestStatusResponse_queue::doneLast24hIsSet() const
{
    return m_Done_last_24hIsSet;
}

void IngestStatusResponse_queue::unsetDone_last_24h()
{
    m_Done_last_24hIsSet = false;
}
int32_t IngestStatusResponse_queue::getFailedLast24h() const
{
    return m_Failed_last_24h;
}

void IngestStatusResponse_queue::setFailedLast24h(int32_t value)
{
    m_Failed_last_24h = value;
    m_Failed_last_24hIsSet = true;
}

bool IngestStatusResponse_queue::failedLast24hIsSet() const
{
    return m_Failed_last_24hIsSet;
}

void IngestStatusResponse_queue::unsetFailed_last_24h()
{
    m_Failed_last_24hIsSet = false;
}

}
}
}
}


