/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "aimee_kb/model/IngestStatusResponse_recent_inner.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

IngestStatusResponse_recent_inner::IngestStatusResponse_recent_inner()
{
    m_Project = utility::conversions::to_string_t("");
    m_ProjectIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
    m_Completed_at = utility::conversions::to_string_t("");
    m_Completed_atIsSet = false;
    m_Files_indexed = 0;
    m_Files_indexedIsSet = false;
    m_Chunks_added = 0;
    m_Chunks_addedIsSet = false;
    m_Error = utility::conversions::to_string_t("");
    m_ErrorIsSet = false;
}

IngestStatusResponse_recent_inner::~IngestStatusResponse_recent_inner()
{
}

void IngestStatusResponse_recent_inner::validate()
{
    // TODO: implement validation
}

web::json::value IngestStatusResponse_recent_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ProjectIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("project"))] = ModelBase::toJson(m_Project);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_Completed_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("completed_at"))] = ModelBase::toJson(m_Completed_at);
    }
    if(m_Files_indexedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("files_indexed"))] = ModelBase::toJson(m_Files_indexed);
    }
    if(m_Chunks_addedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("chunks_added"))] = ModelBase::toJson(m_Chunks_added);
    }
    if(m_ErrorIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("error"))] = ModelBase::toJson(m_Error);
    }

    return val;
}

bool IngestStatusResponse_recent_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("project"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("project")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProject;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProject);
            setProject(refVal_setProject);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("completed_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("completed_at")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCompletedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCompletedAt);
            setCompletedAt(refVal_setCompletedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("files_indexed"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("files_indexed")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setFilesIndexed;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFilesIndexed);
            setFilesIndexed(refVal_setFilesIndexed);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("chunks_added"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("chunks_added")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setChunksAdded;
            ok &= ModelBase::fromJson(fieldValue, refVal_setChunksAdded);
            setChunksAdded(refVal_setChunksAdded);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("error"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("error")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setError;
            ok &= ModelBase::fromJson(fieldValue, refVal_setError);
            setError(refVal_setError);
            
        }
    }
    return ok;
}

void IngestStatusResponse_recent_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ProjectIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("project")), m_Project));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_Completed_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("completed_at")), m_Completed_at));
    }
    if(m_Files_indexedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("files_indexed")), m_Files_indexed));
    }
    if(m_Chunks_addedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("chunks_added")), m_Chunks_added));
    }
    if(m_ErrorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("error")), m_Error));
    }
}

bool IngestStatusResponse_recent_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("project"))))
    {
        utility::string_t refVal_setProject;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("project"))), refVal_setProject );
        setProject(refVal_setProject);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("completed_at"))))
    {
        utility::string_t refVal_setCompletedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("completed_at"))), refVal_setCompletedAt );
        setCompletedAt(refVal_setCompletedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("files_indexed"))))
    {
        int32_t refVal_setFilesIndexed;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("files_indexed"))), refVal_setFilesIndexed );
        setFilesIndexed(refVal_setFilesIndexed);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("chunks_added"))))
    {
        int32_t refVal_setChunksAdded;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("chunks_added"))), refVal_setChunksAdded );
        setChunksAdded(refVal_setChunksAdded);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("error"))))
    {
        utility::string_t refVal_setError;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("error"))), refVal_setError );
        setError(refVal_setError);
    }
    return ok;
}


utility::string_t IngestStatusResponse_recent_inner::getProject() const
{
    return m_Project;
}


void IngestStatusResponse_recent_inner::setProject(const utility::string_t& value)
{
    m_Project = value;
    m_ProjectIsSet = true;
}

bool IngestStatusResponse_recent_inner::projectIsSet() const
{
    return m_ProjectIsSet;
}

void IngestStatusResponse_recent_inner::unsetProject()
{
    m_ProjectIsSet = false;
}
utility::string_t IngestStatusResponse_recent_inner::getStatus() const
{
    return m_Status;
}


void IngestStatusResponse_recent_inner::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool IngestStatusResponse_recent_inner::statusIsSet() const
{
    return m_StatusIsSet;
}

void IngestStatusResponse_recent_inner::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t IngestStatusResponse_recent_inner::getCompletedAt() const
{
    return m_Completed_at;
}


void IngestStatusResponse_recent_inner::setCompletedAt(const utility::string_t& value)
{
    m_Completed_at = value;
    m_Completed_atIsSet = true;
}

bool IngestStatusResponse_recent_inner::completedAtIsSet() const
{
    return m_Completed_atIsSet;
}

void IngestStatusResponse_recent_inner::unsetCompleted_at()
{
    m_Completed_atIsSet = false;
}
int32_t IngestStatusResponse_recent_inner::getFilesIndexed() const
{
    return m_Files_indexed;
}

void IngestStatusResponse_recent_inner::setFilesIndexed(int32_t value)
{
    m_Files_indexed = value;
    m_Files_indexedIsSet = true;
}

bool IngestStatusResponse_recent_inner::filesIndexedIsSet() const
{
    return m_Files_indexedIsSet;
}

void IngestStatusResponse_recent_inner::unsetFiles_indexed()
{
    m_Files_indexedIsSet = false;
}
int32_t IngestStatusResponse_recent_inner::getChunksAdded() const
{
    return m_Chunks_added;
}

void IngestStatusResponse_recent_inner::setChunksAdded(int32_t value)
{
    m_Chunks_added = value;
    m_Chunks_addedIsSet = true;
}

bool IngestStatusResponse_recent_inner::chunksAddedIsSet() const
{
    return m_Chunks_addedIsSet;
}

void IngestStatusResponse_recent_inner::unsetChunks_added()
{
    m_Chunks_addedIsSet = false;
}
utility::string_t IngestStatusResponse_recent_inner::getError() const
{
    return m_Error;
}


void IngestStatusResponse_recent_inner::setError(const utility::string_t& value)
{
    m_Error = value;
    m_ErrorIsSet = true;
}

bool IngestStatusResponse_recent_inner::errorIsSet() const
{
    return m_ErrorIsSet;
}

void IngestStatusResponse_recent_inner::unsetError()
{
    m_ErrorIsSet = false;
}

}
}
}
}


