/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "aimee_kb/model/MaintenanceClearRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

MaintenanceClearRequest::MaintenanceClearRequest()
{
    m_Project = utility::conversions::to_string_t("");
    m_ProjectIsSet = false;
}

MaintenanceClearRequest::~MaintenanceClearRequest()
{
}

void MaintenanceClearRequest::validate()
{
    // TODO: implement validation
}

web::json::value MaintenanceClearRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ProjectIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("project"))] = ModelBase::toJson(m_Project);
    }

    return val;
}

bool MaintenanceClearRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("project"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("project")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProject;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProject);
            setProject(refVal_setProject);
            
        }
    }
    return ok;
}

void MaintenanceClearRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ProjectIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("project")), m_Project));
    }
}

bool MaintenanceClearRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("project"))))
    {
        utility::string_t refVal_setProject;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("project"))), refVal_setProject );
        setProject(refVal_setProject);
    }
    return ok;
}


utility::string_t MaintenanceClearRequest::getProject() const
{
    return m_Project;
}


void MaintenanceClearRequest::setProject(const utility::string_t& value)
{
    m_Project = value;
    m_ProjectIsSet = true;
}

bool MaintenanceClearRequest::projectIsSet() const
{
    return m_ProjectIsSet;
}

void MaintenanceClearRequest::unsetProject()
{
    m_ProjectIsSet = false;
}

}
}
}
}


