/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "aimee_kb/model/PipelineStatusResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

PipelineStatusResponse::PipelineStatusResponse()
{
    m_StateIsSet = false;
    m_Queue_depth = 0;
    m_Queue_depthIsSet = false;
    m_Active_jobsIsSet = false;
    m_QueueIsSet = false;
}

PipelineStatusResponse::~PipelineStatusResponse()
{
}

void PipelineStatusResponse::validate()
{
    // TODO: implement validation
}

web::json::value PipelineStatusResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StateIsSet)
    {
        
        utility::string_t refVal = fromStateEnum(m_State);
        val[utility::conversions::to_string_t(_XPLATSTR("state"))] = ModelBase::toJson(refVal);
        
    }
    if(m_Queue_depthIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("queue_depth"))] = ModelBase::toJson(m_Queue_depth);
    }
    if(m_Active_jobsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("active_jobs"))] = ModelBase::toJson(m_Active_jobs);
    }
    if(m_QueueIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("queue"))] = ModelBase::toJson(m_Queue);
    }

    return val;
}

bool PipelineStatusResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("state"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("state")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setState;
            ok &= ModelBase::fromJson(fieldValue, refVal_setState);
            
            setState(toStateEnum(refVal_setState));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("queue_depth"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("queue_depth")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setQueueDepth;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQueueDepth);
            setQueueDepth(refVal_setQueueDepth);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("active_jobs"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("active_jobs")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Object>> refVal_setActiveJobs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setActiveJobs);
            setActiveJobs(refVal_setActiveJobs);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("queue"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("queue")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<PipelineStatusResponse_queue> refVal_setQueue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQueue);
            setQueue(refVal_setQueue);
            
        }
    }
    return ok;
}

void PipelineStatusResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("state")), fromStateEnum(m_State)));
    }
    if(m_Queue_depthIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("queue_depth")), m_Queue_depth));
    }
    if(m_Active_jobsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("active_jobs")), m_Active_jobs));
    }
    if(m_QueueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("queue")), m_Queue));
    }
}

bool PipelineStatusResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("state"))))
    {
        utility::string_t refVal_setState;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("state"))), refVal_setState );
        setState(toStateEnum(refVal_setState));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("queue_depth"))))
    {
        int32_t refVal_setQueueDepth;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("queue_depth"))), refVal_setQueueDepth );
        setQueueDepth(refVal_setQueueDepth);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("active_jobs"))))
    {
        std::vector<std::shared_ptr<Object>> refVal_setActiveJobs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("active_jobs"))), refVal_setActiveJobs );
        setActiveJobs(refVal_setActiveJobs);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("queue"))))
    {
        std::shared_ptr<PipelineStatusResponse_queue> refVal_setQueue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("queue"))), refVal_setQueue );
        setQueue(refVal_setQueue);
    }
    return ok;
}

PipelineStatusResponse::StateEnum PipelineStatusResponse::toStateEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("idle")) {
        return StateEnum::IDLE;
    }
    
    if (value == utility::conversions::to_string_t("running")) {
        return StateEnum::RUNNING;
    }
    
    if (value == utility::conversions::to_string_t("failed")) {
        return StateEnum::FAILED;
    }
    
    throw std::invalid_argument("Invalid value for conversion to StateEnum");
}


const utility::string_t PipelineStatusResponse::fromStateEnum(const StateEnum value) const
{
    switch(value)
    {
        
        case StateEnum::IDLE: return utility::conversions::to_string_t("idle");
        
        case StateEnum::RUNNING: return utility::conversions::to_string_t("running");
        
        case StateEnum::FAILED: return utility::conversions::to_string_t("failed");
        
    }
}


PipelineStatusResponse::StateEnum PipelineStatusResponse::getState() const
{
    return m_State;
}


void PipelineStatusResponse::setState(const StateEnum value)
{
    m_State = value;
    m_StateIsSet = true;
}

bool PipelineStatusResponse::stateIsSet() const
{
    return m_StateIsSet;
}

void PipelineStatusResponse::unsetState()
{
    m_StateIsSet = false;
}
int32_t PipelineStatusResponse::getQueueDepth() const
{
    return m_Queue_depth;
}

void PipelineStatusResponse::setQueueDepth(int32_t value)
{
    m_Queue_depth = value;
    m_Queue_depthIsSet = true;
}

bool PipelineStatusResponse::queueDepthIsSet() const
{
    return m_Queue_depthIsSet;
}

void PipelineStatusResponse::unsetQueue_depth()
{
    m_Queue_depthIsSet = false;
}
std::vector<std::shared_ptr<Object>> PipelineStatusResponse::getActiveJobs() const
{
    return m_Active_jobs;
}


void PipelineStatusResponse::setActiveJobs(const std::vector<std::shared_ptr<Object>>& value)
{
    m_Active_jobs = value;
    m_Active_jobsIsSet = true;
}

bool PipelineStatusResponse::activeJobsIsSet() const
{
    return m_Active_jobsIsSet;
}

void PipelineStatusResponse::unsetActive_jobs()
{
    m_Active_jobsIsSet = false;
}
std::shared_ptr<PipelineStatusResponse_queue> PipelineStatusResponse::getQueue() const
{
    return m_Queue;
}


void PipelineStatusResponse::setQueue(const std::shared_ptr<PipelineStatusResponse_queue>& value)
{
    m_Queue = value;
    m_QueueIsSet = true;
}

bool PipelineStatusResponse::queueIsSet() const
{
    return m_QueueIsSet;
}

void PipelineStatusResponse::unsetQueue()
{
    m_QueueIsSet = false;
}

}
}
}
}


