/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "aimee_kb/model/ReviewAcceptRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ReviewAcceptRequest::ReviewAcceptRequest()
{
    m_Release_id = 0L;
    m_Release_idIsSet = false;
}

ReviewAcceptRequest::~ReviewAcceptRequest()
{
}

void ReviewAcceptRequest::validate()
{
    // TODO: implement validation
}

web::json::value ReviewAcceptRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Release_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("release_id"))] = ModelBase::toJson(m_Release_id);
    }

    return val;
}

bool ReviewAcceptRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("release_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("release_id")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setReleaseId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReleaseId);
            setReleaseId(refVal_setReleaseId);
            
        }
    }
    return ok;
}

void ReviewAcceptRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Release_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("release_id")), m_Release_id));
    }
}

bool ReviewAcceptRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("release_id"))))
    {
        int64_t refVal_setReleaseId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("release_id"))), refVal_setReleaseId );
        setReleaseId(refVal_setReleaseId);
    }
    return ok;
}


int64_t ReviewAcceptRequest::getReleaseId() const
{
    return m_Release_id;
}

void ReviewAcceptRequest::setReleaseId(int64_t value)
{
    m_Release_id = value;
    m_Release_idIsSet = true;
}

bool ReviewAcceptRequest::releaseIdIsSet() const
{
    return m_Release_idIsSet;
}

void ReviewAcceptRequest::unsetRelease_id()
{
    m_Release_idIsSet = false;
}

}
}
}
}


