/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "aimee_kb/model/RollbackRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RollbackRequest::RollbackRequest()
{
    m_Target_release_id = 0L;
    m_Target_release_idIsSet = false;
}

RollbackRequest::~RollbackRequest()
{
}

void RollbackRequest::validate()
{
    // TODO: implement validation
}

web::json::value RollbackRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Target_release_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("target_release_id"))] = ModelBase::toJson(m_Target_release_id);
    }

    return val;
}

bool RollbackRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("target_release_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("target_release_id")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setTargetReleaseId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTargetReleaseId);
            setTargetReleaseId(refVal_setTargetReleaseId);
            
        }
    }
    return ok;
}

void RollbackRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Target_release_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("target_release_id")), m_Target_release_id));
    }
}

bool RollbackRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("target_release_id"))))
    {
        int64_t refVal_setTargetReleaseId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("target_release_id"))), refVal_setTargetReleaseId );
        setTargetReleaseId(refVal_setTargetReleaseId);
    }
    return ok;
}


int64_t RollbackRequest::getTargetReleaseId() const
{
    return m_Target_release_id;
}

void RollbackRequest::setTargetReleaseId(int64_t value)
{
    m_Target_release_id = value;
    m_Target_release_idIsSet = true;
}

bool RollbackRequest::targetReleaseIdIsSet() const
{
    return m_Target_release_idIsSet;
}

void RollbackRequest::unsetTarget_release_id()
{
    m_Target_release_idIsSet = false;
}

}
}
}
}


