// <auto-generated>
/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System.Linq;
using System.Collections.Generic;

namespace AimeeKb.Client
{
    /// <summary>
    /// A class containing a CookieContainer
    /// </summary>
    public sealed class CookieContainer
    {
        /// <summary>
        /// The collection of tokens
        /// </summary>
        public System.Net.CookieContainer Value { get; } = new System.Net.CookieContainer();
    }
}
