# coding: utf-8

"""
    aimee-kb API

    Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CodeUpdateResponse(BaseModel):
    """
    CodeUpdateResponse
    """ # noqa: E501
    status: Optional[StrictStr] = None
    project: Optional[StrictStr] = None
    files_scanned: Optional[StrictInt] = None
    files_indexed: Optional[StrictInt] = None
    files_skipped: Optional[StrictInt] = None
    files_removed: Optional[StrictInt] = None
    chunks_added: Optional[StrictInt] = None
    chunks_removed: Optional[StrictInt] = None
    embeddings_added: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["status", "project", "files_scanned", "files_indexed", "files_skipped", "files_removed", "chunks_added", "chunks_removed", "embeddings_added"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CodeUpdateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CodeUpdateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "project": obj.get("project"),
            "files_scanned": obj.get("files_scanned"),
            "files_indexed": obj.get("files_indexed"),
            "files_skipped": obj.get("files_skipped"),
            "files_removed": obj.get("files_removed"),
            "chunks_added": obj.get("chunks_added"),
            "chunks_removed": obj.get("chunks_removed"),
            "embeddings_added": obj.get("embeddings_added")
        })
        return _obj


