/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BlastRadiusResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_BlastRadiusResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_BlastRadiusResponse_H_

#include <boost/optional.hpp>

#include "aimee_kb/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  BlastRadiusResponse
    : public ModelBase
{
public:
    BlastRadiusResponse();
    virtual ~BlastRadiusResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// BlastRadiusResponse members


    utility::string_t getFile() const;
    bool fileIsSet() const;
    void unsetfile();
    void setFile(const utility::string_t& value);

    std::vector<utility::string_t> getDependents() const;
    bool dependentsIsSet() const;
    void unsetDependents();
    void setDependents(const std::vector<utility::string_t>& value);

    int32_t getDependentCount() const;
    bool dependentCountIsSet() const;
    void unsetDependent_count();
    void setDependentCount(int32_t value);

    std::vector<utility::string_t> getDependencies() const;
    bool dependenciesIsSet() const;
    void unsetDependencies();
    void setDependencies(const std::vector<utility::string_t>& value);

    int32_t getDependencyCount() const;
    bool dependencyCountIsSet() const;
    void unsetDependency_count();
    void setDependencyCount(int32_t value);


protected:
    utility::string_t m_file;
    bool m_fileIsSet;

    std::vector<utility::string_t> m_Dependents;
    bool m_DependentsIsSet;

    int32_t m_Dependent_count;
    bool m_Dependent_countIsSet;

    std::vector<utility::string_t> m_Dependencies;
    bool m_DependenciesIsSet;

    int32_t m_Dependency_count;
    bool m_Dependency_countIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_BlastRadiusResponse_H_ */
