/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CodeSearchHit.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_CodeSearchHit_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_CodeSearchHit_H_

#include <boost/optional.hpp>

#include "aimee_kb/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  CodeSearchHit
    : public ModelBase
{
public:
    CodeSearchHit();
    virtual ~CodeSearchHit();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// CodeSearchHit members


    utility::string_t getProject() const;
    bool projectIsSet() const;
    void unsetProject();
    void setProject(const utility::string_t& value);

    utility::string_t getFilePath() const;
    bool filePathIsSet() const;
    void unsetFile_path();
    void setFilePath(const utility::string_t& value);

    utility::string_t getSnippet() const;
    bool snippetIsSet() const;
    void unsetSnippet();
    void setSnippet(const utility::string_t& value);

    double getRank() const;
    bool rankIsSet() const;
    void unsetRank();
    void setRank(double value);


protected:
    utility::string_t m_Project;
    bool m_ProjectIsSet;

    utility::string_t m_File_path;
    bool m_File_pathIsSet;

    utility::string_t m_Snippet;
    bool m_SnippetIsSet;

    double m_Rank;
    bool m_RankIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_CodeSearchHit_H_ */
