/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CodeProjectsResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_CodeProjectsResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_CodeProjectsResponse_H_

#include <boost/optional.hpp>

#include "aimee_kb/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "aimee_kb/model/CodeProject.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class CodeProject;


class  CodeProjectsResponse
    : public ModelBase
{
public:
    CodeProjectsResponse();
    virtual ~CodeProjectsResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// CodeProjectsResponse members


    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const utility::string_t& value);

    std::vector<std::shared_ptr<CodeProject>> getProjects() const;
    bool projectsIsSet() const;
    void unsetProjects();
    void setProjects(const std::vector<std::shared_ptr<CodeProject>>& value);

    utility::string_t getNextCursor() const;
    bool nextCursorIsSet() const;
    void unsetNext_cursor();
    void setNextCursor(const utility::string_t& value);


protected:
    utility::string_t m_Status;
    bool m_StatusIsSet;

    std::vector<std::shared_ptr<CodeProject>> m_Projects;
    bool m_ProjectsIsSet;

    utility::string_t m_Next_cursor;
    bool m_Next_cursorIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_CodeProjectsResponse_H_ */
