/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DocsManifestRequest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DocsManifestRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DocsManifestRequest_H_

#include <boost/optional.hpp>

#include "aimee_kb/ModelBase.h"

#include "aimee_kb/model/DocsManifestRequest_docs_inner.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class DocsManifestRequest_docs_inner;


class  DocsManifestRequest
    : public ModelBase
{
public:
    DocsManifestRequest();
    virtual ~DocsManifestRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DocsManifestRequest members


    utility::string_t getScope() const;
    bool scopeIsSet() const;
    void unsetScope();
    void setScope(const utility::string_t& value);

    std::vector<std::shared_ptr<DocsManifestRequest_docs_inner>> getDocs() const;
    bool docsIsSet() const;
    void unsetDocs();
    void setDocs(const std::vector<std::shared_ptr<DocsManifestRequest_docs_inner>>& value);


protected:
    utility::string_t m_Scope;
    bool m_ScopeIsSet;

    std::vector<std::shared_ptr<DocsManifestRequest_docs_inner>> m_Docs;
    bool m_DocsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DocsManifestRequest_H_ */
