/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DocsManifestResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DocsManifestResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DocsManifestResponse_H_

#include <boost/optional.hpp>

#include "aimee_kb/ModelBase.h"

#include <vector>
#include "aimee_kb/model/DocsManifestResponse_missing_inner.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class DocsManifestResponse_missing_inner;


class  DocsManifestResponse
    : public ModelBase
{
public:
    DocsManifestResponse();
    virtual ~DocsManifestResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DocsManifestResponse members


    std::vector<std::shared_ptr<DocsManifestResponse_missing_inner>> getMissing() const;
    bool missingIsSet() const;
    void unsetMissing();
    void setMissing(const std::vector<std::shared_ptr<DocsManifestResponse_missing_inner>>& value);

    int32_t getTotal() const;
    bool totalIsSet() const;
    void unsetTotal();
    void setTotal(int32_t value);

    int32_t getPresent() const;
    bool presentIsSet() const;
    void unsetPresent();
    void setPresent(int32_t value);

    int32_t getMissingCount() const;
    bool missingCountIsSet() const;
    void unsetMissing_count();
    void setMissingCount(int32_t value);


protected:
    std::vector<std::shared_ptr<DocsManifestResponse_missing_inner>> m_Missing;
    bool m_MissingIsSet;

    int32_t m_Total;
    bool m_TotalIsSet;

    int32_t m_Present;
    bool m_PresentIsSet;

    int32_t m_Missing_count;
    bool m_Missing_countIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DocsManifestResponse_H_ */
