/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DrainRequest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DrainRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DrainRequest_H_

#include <boost/optional.hpp>

#include "aimee_kb/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  DrainRequest
    : public ModelBase
{
public:
    DrainRequest();
    virtual ~DrainRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DrainRequest members


    utility::string_t getEmbeddingCommand() const;
    bool embeddingCommandIsSet() const;
    void unsetEmbedding_command();
    void setEmbeddingCommand(const utility::string_t& value);

    int32_t getTimeout() const;
    bool timeoutIsSet() const;
    void unsetTimeout();
    void setTimeout(int32_t value);


protected:
    utility::string_t m_Embedding_command;
    bool m_Embedding_commandIsSet;

    int32_t m_Timeout;
    bool m_TimeoutIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DrainRequest_H_ */
