/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * HealthResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_HealthResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_HealthResponse_H_

#include <boost/optional.hpp>

#include "aimee_kb/ModelBase.h"

#include "aimee_kb/AnyType.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <cpprest/json.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  HealthResponse
    : public ModelBase
{
public:
    HealthResponse();
    virtual ~HealthResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// HealthResponse members


    /// <summary>
    /// ok when healthy; a non-ok string when degraded
    /// </summary>
    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const utility::string_t& value);

    /// <summary>
    /// DB2 (Postgres) reachable
    /// </summary>
    bool isDb2Ok() const;
    bool db2OkIsSet() const;
    void unsetDb2_ok();
    void setDb2Ok(bool value);

    /// <summary>
    /// required kb tables present
    /// </summary>
    bool isDb2KbTablesOk() const;
    bool db2KbTablesOkIsSet() const;
    void unsetDb2_kb_tables_ok();
    void setDb2KbTablesOk(bool value);

    /// <summary>
    /// pgvector extension available
    /// </summary>
    bool isPgvecOk() const;
    bool pgvecOkIsSet() const;
    void unsetPgvec_ok();
    void setPgvecOk(bool value);

    bool isPgvecCollectionOk() const;
    bool pgvecCollectionOkIsSet() const;
    void unsetPgvec_collection_ok();
    void setPgvecCollectionOk(bool value);

    bool isEmbedOk() const;
    bool embedOkIsSet() const;
    void unsetEmbed_ok();
    void setEmbedOk(bool value);

    utility::string_t getEmbedCommand() const;
    bool embedCommandIsSet() const;
    void unsetEmbed_command();
    void setEmbedCommand(const utility::string_t& value);

    int32_t getChunkCount() const;
    bool chunkCountIsSet() const;
    void unsetChunk_count();
    void setChunkCount(int32_t value);

    int32_t getEmbeddingCount() const;
    bool embeddingCountIsSet() const;
    void unsetEmbedding_count();
    void setEmbeddingCount(int32_t value);

    std::vector<utility::string_t> getWarnings() const;
    bool warningsIsSet() const;
    void unsetWarnings();
    void setWarnings(const std::vector<utility::string_t>& value);


    /// <summary>
    /// Get additional properties (properties not defined in the schema)
    /// </summary>
    std::map<utility::string_t, web::json::value> getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();
    /// <summary>
    /// Set additional properties
    /// </summary>
    void setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value);
    /// <summary>
    /// Add a single additional property
    /// </summary>
    void addAdditionalProperty(const utility::string_t& key, const web::json::value& value);

protected:
    utility::string_t m_Status;
    bool m_StatusIsSet;

    bool m_Db2_ok;
    bool m_Db2_okIsSet;

    bool m_Db2_kb_tables_ok;
    bool m_Db2_kb_tables_okIsSet;

    bool m_Pgvec_ok;
    bool m_Pgvec_okIsSet;

    bool m_Pgvec_collection_ok;
    bool m_Pgvec_collection_okIsSet;

    bool m_Embed_ok;
    bool m_Embed_okIsSet;

    utility::string_t m_Embed_command;
    bool m_Embed_commandIsSet;

    int32_t m_Chunk_count;
    bool m_Chunk_countIsSet;

    int32_t m_Embedding_count;
    bool m_Embedding_countIsSet;

    std::vector<utility::string_t> m_Warnings;
    bool m_WarningsIsSet;

    std::map<utility::string_t, web::json::value> m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_HealthResponse_H_ */
