/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IngestStatusResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_IngestStatusResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_IngestStatusResponse_H_

#include <boost/optional.hpp>

#include "aimee_kb/ModelBase.h"

#include "aimee_kb/model/IngestStatusResponse_queue.h"
#include <cpprest/details/basic_types.h>
#include "aimee_kb/model/IngestStatusResponse_recent_inner.h"
#include "aimee_kb/model/IngestStatusResponse_workers.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class IngestStatusResponse_queue;
class IngestStatusResponse_workers;
class IngestStatusResponse_recent_inner;


class  IngestStatusResponse
    : public ModelBase
{
public:
    IngestStatusResponse();
    virtual ~IngestStatusResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// IngestStatusResponse members


    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const utility::string_t& value);

    std::shared_ptr<IngestStatusResponse_queue> getQueue() const;
    bool queueIsSet() const;
    void unsetQueue();
    void setQueue(const std::shared_ptr<IngestStatusResponse_queue>& value);

    std::shared_ptr<IngestStatusResponse_workers> getWorkers() const;
    bool workersIsSet() const;
    void unsetWorkers();
    void setWorkers(const std::shared_ptr<IngestStatusResponse_workers>& value);

    std::vector<std::shared_ptr<IngestStatusResponse_recent_inner>> getRecent() const;
    bool recentIsSet() const;
    void unsetRecent();
    void setRecent(const std::vector<std::shared_ptr<IngestStatusResponse_recent_inner>>& value);


protected:
    utility::string_t m_Status;
    bool m_StatusIsSet;

    std::shared_ptr<IngestStatusResponse_queue> m_Queue;
    bool m_QueueIsSet;

    std::shared_ptr<IngestStatusResponse_workers> m_Workers;
    bool m_WorkersIsSet;

    std::vector<std::shared_ptr<IngestStatusResponse_recent_inner>> m_Recent;
    bool m_RecentIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_IngestStatusResponse_H_ */
