/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IngestStatusResponse_recent_inner.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_IngestStatusResponse_recent_inner_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_IngestStatusResponse_recent_inner_H_

#include <boost/optional.hpp>

#include "aimee_kb/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  IngestStatusResponse_recent_inner
    : public ModelBase
{
public:
    IngestStatusResponse_recent_inner();
    virtual ~IngestStatusResponse_recent_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// IngestStatusResponse_recent_inner members


    utility::string_t getProject() const;
    bool projectIsSet() const;
    void unsetProject();
    void setProject(const utility::string_t& value);

    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const utility::string_t& value);

    utility::string_t getCompletedAt() const;
    bool completedAtIsSet() const;
    void unsetCompleted_at();
    void setCompletedAt(const utility::string_t& value);

    int32_t getFilesIndexed() const;
    bool filesIndexedIsSet() const;
    void unsetFiles_indexed();
    void setFilesIndexed(int32_t value);

    int32_t getChunksAdded() const;
    bool chunksAddedIsSet() const;
    void unsetChunks_added();
    void setChunksAdded(int32_t value);

    utility::string_t getError() const;
    bool errorIsSet() const;
    void unsetError();
    void setError(const utility::string_t& value);


protected:
    utility::string_t m_Project;
    bool m_ProjectIsSet;

    utility::string_t m_Status;
    bool m_StatusIsSet;

    utility::string_t m_Completed_at;
    bool m_Completed_atIsSet;

    int32_t m_Files_indexed;
    bool m_Files_indexedIsSet;

    int32_t m_Chunks_added;
    bool m_Chunks_addedIsSet;

    utility::string_t m_Error;
    bool m_ErrorIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_IngestStatusResponse_recent_inner_H_ */
