/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MaintenanceClearResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MaintenanceClearResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MaintenanceClearResponse_H_

#include <boost/optional.hpp>

#include "aimee_kb/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  MaintenanceClearResponse
    : public ModelBase
{
public:
    MaintenanceClearResponse();
    virtual ~MaintenanceClearResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// MaintenanceClearResponse members


    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const utility::string_t& value);

    utility::string_t getProject() const;
    bool projectIsSet() const;
    void unsetProject();
    void setProject(const utility::string_t& value);

    int32_t getChunksDeleted() const;
    bool chunksDeletedIsSet() const;
    void unsetChunks_deleted();
    void setChunksDeleted(int32_t value);


protected:
    utility::string_t m_Status;
    bool m_StatusIsSet;

    utility::string_t m_Project;
    bool m_ProjectIsSet;

    int32_t m_Chunks_deleted;
    bool m_Chunks_deletedIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MaintenanceClearResponse_H_ */
