/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SearchRequest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SearchRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SearchRequest_H_

#include <boost/optional.hpp>

#include "aimee_kb/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  SearchRequest
    : public ModelBase
{
public:
    SearchRequest();
    virtual ~SearchRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SearchRequest members


    utility::string_t getQuery() const;
    bool queryIsSet() const;
    void unsetQuery();
    void setQuery(const utility::string_t& value);

    utility::string_t getProject() const;
    bool projectIsSet() const;
    void unsetProject();
    void setProject(const utility::string_t& value);

    utility::string_t getScopeKind() const;
    bool scopeKindIsSet() const;
    void unsetScope_kind();
    void setScopeKind(const utility::string_t& value);

    utility::string_t getScopeId() const;
    bool scopeIdIsSet() const;
    void unsetScope_id();
    void setScopeId(const utility::string_t& value);

    int32_t getMaxResults() const;
    bool maxResultsIsSet() const;
    void unsetMax_results();
    void setMaxResults(int32_t value);

    utility::string_t getFusionMode() const;
    bool fusionModeIsSet() const;
    void unsetFusion_mode();
    void setFusionMode(const utility::string_t& value);

    utility::string_t getCursor() const;
    bool cursorIsSet() const;
    void unsetCursor();
    void setCursor(const utility::string_t& value);


protected:
    utility::string_t m_Query;
    bool m_QueryIsSet;

    utility::string_t m_Project;
    bool m_ProjectIsSet;

    utility::string_t m_Scope_kind;
    bool m_Scope_kindIsSet;

    utility::string_t m_Scope_id;
    bool m_Scope_idIsSet;

    int32_t m_Max_results;
    bool m_Max_resultsIsSet;

    utility::string_t m_Fusion_mode;
    bool m_Fusion_modeIsSet;

    utility::string_t m_Cursor;
    bool m_CursorIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SearchRequest_H_ */
