/* tslint:disable */
/* eslint-disable */
/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CodeSearchHit } from './CodeSearchHit';
import {
    CodeSearchHitFromJSON,
    CodeSearchHitFromJSONTyped,
    CodeSearchHitToJSON,
    CodeSearchHitToJSONTyped,
} from './CodeSearchHit';

/**
 * 
 * @export
 * @interface CodeSearchResponse
 */
export interface CodeSearchResponse {
    /**
     * 
     * @type {string}
     * @memberof CodeSearchResponse
     */
    status?: string;
    /**
     * 
     * @type {Array<CodeSearchHit>}
     * @memberof CodeSearchResponse
     */
    hits?: Array<CodeSearchHit>;
    /**
     * 
     * @type {string}
     * @memberof CodeSearchResponse
     */
    nextCursor?: string;
}

/**
 * Check if a given object implements the CodeSearchResponse interface.
 */
export function instanceOfCodeSearchResponse(value: object): value is CodeSearchResponse {
    return true;
}

export function CodeSearchResponseFromJSON(json: any): CodeSearchResponse {
    return CodeSearchResponseFromJSONTyped(json, false);
}

export function CodeSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'hits': json['hits'] == null ? undefined : ((json['hits'] as Array<any>).map(CodeSearchHitFromJSON)),
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function CodeSearchResponseToJSON(json: any): CodeSearchResponse {
    return CodeSearchResponseToJSONTyped(json, false);
}

export function CodeSearchResponseToJSONTyped(value?: CodeSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'hits': value['hits'] == null ? undefined : ((value['hits'] as Array<any>).map(CodeSearchHitToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

