/* tslint:disable */
/* eslint-disable */
/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CodeScanRequest
 */
export interface CodeScanRequest {
    /**
     * 
     * @type {string}
     * @memberof CodeScanRequest
     */
    project: string;
    /**
     * 
     * @type {string}
     * @memberof CodeScanRequest
     */
    rootPath: string;
    /**
     * 
     * @type {boolean}
     * @memberof CodeScanRequest
     */
    force?: boolean;
}

/**
 * Check if a given object implements the CodeScanRequest interface.
 */
export function instanceOfCodeScanRequest(value: object): value is CodeScanRequest {
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('rootPath' in value) || value['rootPath'] === undefined) return false;
    return true;
}

export function CodeScanRequestFromJSON(json: any): CodeScanRequest {
    return CodeScanRequestFromJSONTyped(json, false);
}

export function CodeScanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeScanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'project': json['project'],
        'rootPath': json['root_path'],
        'force': json['force'] == null ? undefined : json['force'],
    };
}

export function CodeScanRequestToJSON(json: any): CodeScanRequest {
    return CodeScanRequestToJSONTyped(json, false);
}

export function CodeScanRequestToJSONTyped(value?: CodeScanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project': value['project'],
        'root_path': value['rootPath'],
        'force': value['force'],
    };
}

