/* tslint:disable */
/* eslint-disable */
/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CodeProject
 */
export interface CodeProject {
    /**
     * 
     * @type {string}
     * @memberof CodeProject
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeProject
     */
    root?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeProject
     */
    scannedAt?: string;
}

/**
 * Check if a given object implements the CodeProject interface.
 */
export function instanceOfCodeProject(value: object): value is CodeProject {
    return true;
}

export function CodeProjectFromJSON(json: any): CodeProject {
    return CodeProjectFromJSONTyped(json, false);
}

export function CodeProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeProject {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'root': json['root'] == null ? undefined : json['root'],
        'scannedAt': json['scanned_at'] == null ? undefined : json['scanned_at'],
    };
}

export function CodeProjectToJSON(json: any): CodeProject {
    return CodeProjectToJSONTyped(json, false);
}

export function CodeProjectToJSONTyped(value?: CodeProject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'root': value['root'],
        'scanned_at': value['scannedAt'],
    };
}

