/* tslint:disable */
/* eslint-disable */
/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntitySearchRequest
 */
export interface EntitySearchRequest {
    /**
     * 
     * @type {string}
     * @memberof EntitySearchRequest
     */
    query: string;
    /**
     * 
     * @type {number}
     * @memberof EntitySearchRequest
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof EntitySearchRequest
     */
    cursor?: string;
}

/**
 * Check if a given object implements the EntitySearchRequest interface.
 */
export function instanceOfEntitySearchRequest(value: object): value is EntitySearchRequest {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function EntitySearchRequestFromJSON(json: any): EntitySearchRequest {
    return EntitySearchRequestFromJSONTyped(json, false);
}

export function EntitySearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntitySearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
    };
}

export function EntitySearchRequestToJSON(json: any): EntitySearchRequest {
    return EntitySearchRequestToJSONTyped(json, false);
}

export function EntitySearchRequestToJSONTyped(value?: EntitySearchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'limit': value['limit'],
        'cursor': value['cursor'],
    };
}

