/* tslint:disable */
/* eslint-disable */
/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestStatusResponseQueue
 */
export interface IngestStatusResponseQueue {
    /**
     * 
     * @type {number}
     * @memberof IngestStatusResponseQueue
     */
    pending?: number;
    /**
     * 
     * @type {number}
     * @memberof IngestStatusResponseQueue
     */
    running?: number;
    /**
     * 
     * @type {number}
     * @memberof IngestStatusResponseQueue
     */
    doneLast24h?: number;
    /**
     * 
     * @type {number}
     * @memberof IngestStatusResponseQueue
     */
    failedLast24h?: number;
}

/**
 * Check if a given object implements the IngestStatusResponseQueue interface.
 */
export function instanceOfIngestStatusResponseQueue(value: object): value is IngestStatusResponseQueue {
    return true;
}

export function IngestStatusResponseQueueFromJSON(json: any): IngestStatusResponseQueue {
    return IngestStatusResponseQueueFromJSONTyped(json, false);
}

export function IngestStatusResponseQueueFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestStatusResponseQueue {
    if (json == null) {
        return json;
    }
    return {
        
        'pending': json['pending'] == null ? undefined : json['pending'],
        'running': json['running'] == null ? undefined : json['running'],
        'doneLast24h': json['done_last_24h'] == null ? undefined : json['done_last_24h'],
        'failedLast24h': json['failed_last_24h'] == null ? undefined : json['failed_last_24h'],
    };
}

export function IngestStatusResponseQueueToJSON(json: any): IngestStatusResponseQueue {
    return IngestStatusResponseQueueToJSONTyped(json, false);
}

export function IngestStatusResponseQueueToJSONTyped(value?: IngestStatusResponseQueue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pending': value['pending'],
        'running': value['running'],
        'done_last_24h': value['doneLast24h'],
        'failed_last_24h': value['failedLast24h'],
    };
}

