/* tslint:disable */
/* eslint-disable */
/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestRequest
 */
export interface IngestRequest {
    /**
     * Workspace root, workspace name, or "all".
     * @type {string}
     * @memberof IngestRequest
     */
    workspace?: string;
    /**
     * 
     * @type {string}
     * @memberof IngestRequest
     */
    embeddingCommand?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IngestRequest
     */
    force?: boolean;
}

/**
 * Check if a given object implements the IngestRequest interface.
 */
export function instanceOfIngestRequest(value: object): value is IngestRequest {
    return true;
}

export function IngestRequestFromJSON(json: any): IngestRequest {
    return IngestRequestFromJSONTyped(json, false);
}

export function IngestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
        'embeddingCommand': json['embedding_command'] == null ? undefined : json['embedding_command'],
        'force': json['force'] == null ? undefined : json['force'],
    };
}

export function IngestRequestToJSON(json: any): IngestRequest {
    return IngestRequestToJSONTyped(json, false);
}

export function IngestRequestToJSONTyped(value?: IngestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workspace': value['workspace'],
        'embedding_command': value['embeddingCommand'],
        'force': value['force'],
    };
}

