/* tslint:disable */
/* eslint-disable */
/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaintenanceClearResponse
 */
export interface MaintenanceClearResponse {
    /**
     * 
     * @type {string}
     * @memberof MaintenanceClearResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof MaintenanceClearResponse
     */
    project?: string;
    /**
     * 
     * @type {number}
     * @memberof MaintenanceClearResponse
     */
    chunksDeleted?: number;
}

/**
 * Check if a given object implements the MaintenanceClearResponse interface.
 */
export function instanceOfMaintenanceClearResponse(value: object): value is MaintenanceClearResponse {
    return true;
}

export function MaintenanceClearResponseFromJSON(json: any): MaintenanceClearResponse {
    return MaintenanceClearResponseFromJSONTyped(json, false);
}

export function MaintenanceClearResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaintenanceClearResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'project': json['project'] == null ? undefined : json['project'],
        'chunksDeleted': json['chunks_deleted'] == null ? undefined : json['chunks_deleted'],
    };
}

export function MaintenanceClearResponseToJSON(json: any): MaintenanceClearResponse {
    return MaintenanceClearResponseToJSONTyped(json, false);
}

export function MaintenanceClearResponseToJSONTyped(value?: MaintenanceClearResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'project': value['project'],
        'chunks_deleted': value['chunksDeleted'],
    };
}

