/* tslint:disable */
/* eslint-disable */
/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaintenanceRepairResponse
 */
export interface MaintenanceRepairResponse {
    /**
     * 
     * @type {string}
     * @memberof MaintenanceRepairResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof MaintenanceRepairResponse
     */
    project?: string;
    /**
     * 
     * @type {number}
     * @memberof MaintenanceRepairResponse
     */
    filesScanned?: number;
    /**
     * 
     * @type {number}
     * @memberof MaintenanceRepairResponse
     */
    filesIndexed?: number;
    /**
     * 
     * @type {number}
     * @memberof MaintenanceRepairResponse
     */
    filesSkipped?: number;
    /**
     * 
     * @type {number}
     * @memberof MaintenanceRepairResponse
     */
    filesRemoved?: number;
    /**
     * 
     * @type {number}
     * @memberof MaintenanceRepairResponse
     */
    chunksAdded?: number;
    /**
     * 
     * @type {number}
     * @memberof MaintenanceRepairResponse
     */
    chunksRemoved?: number;
    /**
     * 
     * @type {number}
     * @memberof MaintenanceRepairResponse
     */
    embeddingsAdded?: number;
}

/**
 * Check if a given object implements the MaintenanceRepairResponse interface.
 */
export function instanceOfMaintenanceRepairResponse(value: object): value is MaintenanceRepairResponse {
    return true;
}

export function MaintenanceRepairResponseFromJSON(json: any): MaintenanceRepairResponse {
    return MaintenanceRepairResponseFromJSONTyped(json, false);
}

export function MaintenanceRepairResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaintenanceRepairResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'project': json['project'] == null ? undefined : json['project'],
        'filesScanned': json['files_scanned'] == null ? undefined : json['files_scanned'],
        'filesIndexed': json['files_indexed'] == null ? undefined : json['files_indexed'],
        'filesSkipped': json['files_skipped'] == null ? undefined : json['files_skipped'],
        'filesRemoved': json['files_removed'] == null ? undefined : json['files_removed'],
        'chunksAdded': json['chunks_added'] == null ? undefined : json['chunks_added'],
        'chunksRemoved': json['chunks_removed'] == null ? undefined : json['chunks_removed'],
        'embeddingsAdded': json['embeddings_added'] == null ? undefined : json['embeddings_added'],
    };
}

export function MaintenanceRepairResponseToJSON(json: any): MaintenanceRepairResponse {
    return MaintenanceRepairResponseToJSONTyped(json, false);
}

export function MaintenanceRepairResponseToJSONTyped(value?: MaintenanceRepairResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'project': value['project'],
        'files_scanned': value['filesScanned'],
        'files_indexed': value['filesIndexed'],
        'files_skipped': value['filesSkipped'],
        'files_removed': value['filesRemoved'],
        'chunks_added': value['chunksAdded'],
        'chunks_removed': value['chunksRemoved'],
        'embeddings_added': value['embeddingsAdded'],
    };
}

