/* tslint:disable */
/* eslint-disable */
/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PipelineStatusResponseQueue
 */
export interface PipelineStatusResponseQueue {
    /**
     * 
     * @type {number}
     * @memberof PipelineStatusResponseQueue
     */
    pending?: number;
    /**
     * 
     * @type {number}
     * @memberof PipelineStatusResponseQueue
     */
    running?: number;
    /**
     * 
     * @type {number}
     * @memberof PipelineStatusResponseQueue
     */
    done?: number;
    /**
     * 
     * @type {number}
     * @memberof PipelineStatusResponseQueue
     */
    failed?: number;
    /**
     * 
     * @type {number}
     * @memberof PipelineStatusResponseQueue
     */
    total?: number;
}

/**
 * Check if a given object implements the PipelineStatusResponseQueue interface.
 */
export function instanceOfPipelineStatusResponseQueue(value: object): value is PipelineStatusResponseQueue {
    return true;
}

export function PipelineStatusResponseQueueFromJSON(json: any): PipelineStatusResponseQueue {
    return PipelineStatusResponseQueueFromJSONTyped(json, false);
}

export function PipelineStatusResponseQueueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineStatusResponseQueue {
    if (json == null) {
        return json;
    }
    return {
        
        'pending': json['pending'] == null ? undefined : json['pending'],
        'running': json['running'] == null ? undefined : json['running'],
        'done': json['done'] == null ? undefined : json['done'],
        'failed': json['failed'] == null ? undefined : json['failed'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function PipelineStatusResponseQueueToJSON(json: any): PipelineStatusResponseQueue {
    return PipelineStatusResponseQueueToJSONTyped(json, false);
}

export function PipelineStatusResponseQueueToJSONTyped(value?: PipelineStatusResponseQueue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pending': value['pending'],
        'running': value['running'],
        'done': value['done'],
        'failed': value['failed'],
        'total': value['total'],
    };
}

