/* tslint:disable */
/* eslint-disable */
/**
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewRejectRequest
 */
export interface ReviewRejectRequest {
    /**
     * 
     * @type {string}
     * @memberof ReviewRejectRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the ReviewRejectRequest interface.
 */
export function instanceOfReviewRejectRequest(value: object): value is ReviewRejectRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function ReviewRejectRequestFromJSON(json: any): ReviewRejectRequest {
    return ReviewRejectRequestFromJSONTyped(json, false);
}

export function ReviewRejectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewRejectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
    };
}

export function ReviewRejectRequestToJSON(json: any): ReviewRejectRequest {
    return ReviewRejectRequestToJSONTyped(json, false);
}

export function ReviewRejectRequestToJSONTyped(value?: ReviewRejectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

