/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AimeeKb.Model;
using AimeeKb.Client;
using System.Reflection;

namespace AimeeKb.Test.Model
{
    /// <summary>
    ///  Class for testing CodeCallersResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CodeCallersResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CodeCallersResponse
        //private CodeCallersResponse instance;

        public CodeCallersResponseTests()
        {
            // TODO uncomment below to create an instance of CodeCallersResponse
            //instance = new CodeCallersResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CodeCallersResponse
        /// </summary>
        [Fact]
        public void CodeCallersResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CodeCallersResponse
            //Assert.IsType<CodeCallersResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Hits'
        /// </summary>
        [Fact]
        public void HitsTest()
        {
            // TODO unit test for the property 'Hits'
        }

        /// <summary>
        /// Test the property 'NextCursor'
        /// </summary>
        [Fact]
        public void NextCursorTest()
        {
            // TODO unit test for the property 'NextCursor'
        }
    }
}
