/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AimeeKb.Model;
using AimeeKb.Client;
using System.Reflection;

namespace AimeeKb.Test.Model
{
    /// <summary>
    ///  Class for testing CodeScanRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CodeScanRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CodeScanRequest
        //private CodeScanRequest instance;

        public CodeScanRequestTests()
        {
            // TODO uncomment below to create an instance of CodeScanRequest
            //instance = new CodeScanRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CodeScanRequest
        /// </summary>
        [Fact]
        public void CodeScanRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CodeScanRequest
            //Assert.IsType<CodeScanRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Project'
        /// </summary>
        [Fact]
        public void ProjectTest()
        {
            // TODO unit test for the property 'Project'
        }

        /// <summary>
        /// Test the property 'RootPath'
        /// </summary>
        [Fact]
        public void RootPathTest()
        {
            // TODO unit test for the property 'RootPath'
        }

        /// <summary>
        /// Test the property 'Force'
        /// </summary>
        [Fact]
        public void ForceTest()
        {
            // TODO unit test for the property 'Force'
        }
    }
}
