/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AimeeKb.Model;
using AimeeKb.Client;
using System.Reflection;

namespace AimeeKb.Test.Model
{
    /// <summary>
    ///  Class for testing DocsManifestRequestDocsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocsManifestRequestDocsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocsManifestRequestDocsInner
        //private DocsManifestRequestDocsInner instance;

        public DocsManifestRequestDocsInnerTests()
        {
            // TODO uncomment below to create an instance of DocsManifestRequestDocsInner
            //instance = new DocsManifestRequestDocsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocsManifestRequestDocsInner
        /// </summary>
        [Fact]
        public void DocsManifestRequestDocsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocsManifestRequestDocsInner
            //Assert.IsType<DocsManifestRequestDocsInner>(instance);
        }

        /// <summary>
        /// Test the property 'ContentHash'
        /// </summary>
        [Fact]
        public void ContentHashTest()
        {
            // TODO unit test for the property 'ContentHash'
        }

        /// <summary>
        /// Test the property 'DocKey'
        /// </summary>
        [Fact]
        public void DocKeyTest()
        {
            // TODO unit test for the property 'DocKey'
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Fact]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }
    }
}
