/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AimeeKb.Model;
using AimeeKb.Client;
using System.Reflection;

namespace AimeeKb.Test.Model
{
    /// <summary>
    ///  Class for testing EntitySearchResponseEntitiesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitySearchResponseEntitiesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitySearchResponseEntitiesInner
        //private EntitySearchResponseEntitiesInner instance;

        public EntitySearchResponseEntitiesInnerTests()
        {
            // TODO uncomment below to create an instance of EntitySearchResponseEntitiesInner
            //instance = new EntitySearchResponseEntitiesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitySearchResponseEntitiesInner
        /// </summary>
        [Fact]
        public void EntitySearchResponseEntitiesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitySearchResponseEntitiesInner
            //Assert.IsType<EntitySearchResponseEntitiesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Entity'
        /// </summary>
        [Fact]
        public void EntityTest()
        {
            // TODO unit test for the property 'Entity'
        }

        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Fact]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }

        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
    }
}
