/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AimeeKb.Model;
using AimeeKb.Client;
using System.Reflection;

namespace AimeeKb.Test.Model
{
    /// <summary>
    ///  Class for testing IngestStatusResponseWorkers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IngestStatusResponseWorkersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IngestStatusResponseWorkers
        //private IngestStatusResponseWorkers instance;

        public IngestStatusResponseWorkersTests()
        {
            // TODO uncomment below to create an instance of IngestStatusResponseWorkers
            //instance = new IngestStatusResponseWorkers();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IngestStatusResponseWorkers
        /// </summary>
        [Fact]
        public void IngestStatusResponseWorkersInstanceTest()
        {
            // TODO uncomment below to test "IsType" IngestStatusResponseWorkers
            //Assert.IsType<IngestStatusResponseWorkers>(instance);
        }

        /// <summary>
        /// Test the property 'Configured'
        /// </summary>
        [Fact]
        public void ConfiguredTest()
        {
            // TODO unit test for the property 'Configured'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
    }
}
