/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AimeeKb.Model;
using AimeeKb.Client;
using System.Reflection;

namespace AimeeKb.Test.Model
{
    /// <summary>
    ///  Class for testing IngestStatusResponseRecentInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IngestStatusResponseRecentInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IngestStatusResponseRecentInner
        //private IngestStatusResponseRecentInner instance;

        public IngestStatusResponseRecentInnerTests()
        {
            // TODO uncomment below to create an instance of IngestStatusResponseRecentInner
            //instance = new IngestStatusResponseRecentInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IngestStatusResponseRecentInner
        /// </summary>
        [Fact]
        public void IngestStatusResponseRecentInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" IngestStatusResponseRecentInner
            //Assert.IsType<IngestStatusResponseRecentInner>(instance);
        }

        /// <summary>
        /// Test the property 'Project'
        /// </summary>
        [Fact]
        public void ProjectTest()
        {
            // TODO unit test for the property 'Project'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }

        /// <summary>
        /// Test the property 'FilesIndexed'
        /// </summary>
        [Fact]
        public void FilesIndexedTest()
        {
            // TODO unit test for the property 'FilesIndexed'
        }

        /// <summary>
        /// Test the property 'ChunksAdded'
        /// </summary>
        [Fact]
        public void ChunksAddedTest()
        {
            // TODO unit test for the property 'ChunksAdded'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
