/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AimeeKb.Model;
using AimeeKb.Client;
using System.Reflection;

namespace AimeeKb.Test.Model
{
    /// <summary>
    ///  Class for testing IngestStatusResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IngestStatusResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IngestStatusResponse
        //private IngestStatusResponse instance;

        public IngestStatusResponseTests()
        {
            // TODO uncomment below to create an instance of IngestStatusResponse
            //instance = new IngestStatusResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IngestStatusResponse
        /// </summary>
        [Fact]
        public void IngestStatusResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IngestStatusResponse
            //Assert.IsType<IngestStatusResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Queue'
        /// </summary>
        [Fact]
        public void QueueTest()
        {
            // TODO unit test for the property 'Queue'
        }

        /// <summary>
        /// Test the property 'Workers'
        /// </summary>
        [Fact]
        public void WorkersTest()
        {
            // TODO unit test for the property 'Workers'
        }

        /// <summary>
        /// Test the property 'Recent'
        /// </summary>
        [Fact]
        public void RecentTest()
        {
            // TODO unit test for the property 'Recent'
        }
    }
}
