/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AimeeKb.Model;
using AimeeKb.Client;
using System.Reflection;

namespace AimeeKb.Test.Model
{
    /// <summary>
    ///  Class for testing MaintenanceReconcileResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MaintenanceReconcileResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MaintenanceReconcileResponse
        //private MaintenanceReconcileResponse instance;

        public MaintenanceReconcileResponseTests()
        {
            // TODO uncomment below to create an instance of MaintenanceReconcileResponse
            //instance = new MaintenanceReconcileResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MaintenanceReconcileResponse
        /// </summary>
        [Fact]
        public void MaintenanceReconcileResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MaintenanceReconcileResponse
            //Assert.IsType<MaintenanceReconcileResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Rc'
        /// </summary>
        [Fact]
        public void RcTest()
        {
            // TODO unit test for the property 'Rc'
        }

        /// <summary>
        /// Test the property 'DryRun'
        /// </summary>
        [Fact]
        public void DryRunTest()
        {
            // TODO unit test for the property 'DryRun'
        }

        /// <summary>
        /// Test the property 'Memory'
        /// </summary>
        [Fact]
        public void MemoryTest()
        {
            // TODO unit test for the property 'Memory'
        }

        /// <summary>
        /// Test the property 'Kb'
        /// </summary>
        [Fact]
        public void KbTest()
        {
            // TODO unit test for the property 'Kb'
        }
    }
}
