/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AimeeKb.Model;
using AimeeKb.Client;
using System.Reflection;

namespace AimeeKb.Test.Model
{
    /// <summary>
    ///  Class for testing SearchHitCitationsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchHitCitationsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchHitCitationsInner
        //private SearchHitCitationsInner instance;

        public SearchHitCitationsInnerTests()
        {
            // TODO uncomment below to create an instance of SearchHitCitationsInner
            //instance = new SearchHitCitationsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchHitCitationsInner
        /// </summary>
        [Fact]
        public void SearchHitCitationsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchHitCitationsInner
            //Assert.IsType<SearchHitCitationsInner>(instance);
        }

        /// <summary>
        /// Test the property 'SourceKind'
        /// </summary>
        [Fact]
        public void SourceKindTest()
        {
            // TODO unit test for the property 'SourceKind'
        }

        /// <summary>
        /// Test the property 'SourceId'
        /// </summary>
        [Fact]
        public void SourceIdTest()
        {
            // TODO unit test for the property 'SourceId'
        }
    }
}
