/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AimeeKb.Model;
using AimeeKb.Client;
using System.Reflection;

namespace AimeeKb.Test.Model
{
    /// <summary>
    ///  Class for testing VersionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VersionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VersionResponse
        //private VersionResponse instance;

        public VersionResponseTests()
        {
            // TODO uncomment below to create an instance of VersionResponse
            //instance = new VersionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VersionResponse
        /// </summary>
        [Fact]
        public void VersionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" VersionResponse
            //Assert.IsType<VersionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Fact]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }
    }
}
