#!/usr/bin/env python3
"""Guard that the thin client's method -> /v1 route map is in sync with the
server registry.

The map is generated from src/server/server_http_routes.c by
scripts/gen-cli-v1-routes.py and lives inline in the thin-client TU
(src/cli_v1_routes*.c) between the @@GEN-CLI-V1-ROUTES BEGIN/END markers. This
check regenerates the block and diffs it against what's committed in the file, so
a registry change that isn't reflected in the committed map fails `make lint`
instead of silently leaving the client without its first-class /v1 route.
"""
import glob
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "scripts" / "gen-cli-v1-routes.py"
TARGET_GLOB = str(ROOT / "src" / "cli_v1_routes*.c")
MARK_BEGIN = "/* @@GEN-CLI-V1-ROUTES BEGIN — generated by scripts/gen-cli-v1-routes.py; DO NOT EDIT @@ */"
MARK_END = "/* @@GEN-CLI-V1-ROUTES END @@ */"


def committed_block():
    for f in sorted(glob.glob(TARGET_GLOB)):
        text = Path(f).read_text(encoding="utf-8")
        if MARK_BEGIN in text:
            return f, text.split(MARK_BEGIN, 1)[1].split(MARK_END, 1)[0].strip("\n")
    return None, None


def main() -> int:
    fname, committed = committed_block()
    if committed is None:
        print("check-cli-v1-routes: FAIL — @@GEN-CLI-V1-ROUTES markers not found in "
              "src/cli_v1_routes*.c; run scripts/gen-cli-v1-routes.py")
        return 1
    fresh = subprocess.run([sys.executable, str(GEN), "--stdout"],
                           check=True, capture_output=True, text=True).stdout.strip("\n")
    if committed != fresh:
        print("check-cli-v1-routes: FAIL — the generated /v1 route map is stale vs "
              "server_http_routes.c; run scripts/gen-cli-v1-routes.py and commit.")
        return 1
    n = sum(1 for ln in fresh.splitlines() if ln.lstrip().startswith('{"'))
    print(f"check-cli-v1-routes: ok ({n} client /v1 routes in sync)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
