# coding: utf-8

"""
    aimee-kb API

    Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aimee_kb.models.docs_manifest_response import DocsManifestResponse

class TestDocsManifestResponse(unittest.TestCase):
    """DocsManifestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocsManifestResponse:
        """Test DocsManifestResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocsManifestResponse`
        """
        model = DocsManifestResponse()
        if include_optional:
            return DocsManifestResponse(
                missing = [
                    aimee_kb.models.docs_manifest_response_missing_inner.DocsManifestResponse_missing_inner(
                        doc_key = '', 
                        content_hash = '', 
                        scope = '', )
                    ],
                total = 56,
                present = 56,
                missing_count = 56
            )
        else:
            return DocsManifestResponse(
                missing = [
                    aimee_kb.models.docs_manifest_response_missing_inner.DocsManifestResponse_missing_inner(
                        doc_key = '', 
                        content_hash = '', 
                        scope = '', )
                    ],
                total = 56,
                present = 56,
                missing_count = 56,
        )
        """

    def testDocsManifestResponse(self):
        """Test DocsManifestResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
