# coding: utf-8

"""
    aimee-kb API

    Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aimee_kb.models.maintenance_reconcile_response import MaintenanceReconcileResponse

class TestMaintenanceReconcileResponse(unittest.TestCase):
    """MaintenanceReconcileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MaintenanceReconcileResponse:
        """Test MaintenanceReconcileResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MaintenanceReconcileResponse`
        """
        model = MaintenanceReconcileResponse()
        if include_optional:
            return MaintenanceReconcileResponse(
                status = 'ok',
                rc = 56,
                dry_run = True,
                memory = aimee_kb.models.maintenance_reconcile_response_memory.MaintenanceReconcileResponse_memory(
                    kept = 56, 
                    pruned = 56, ),
                kb = aimee_kb.models.maintenance_reconcile_response_memory.MaintenanceReconcileResponse_memory(
                    kept = 56, 
                    pruned = 56, )
            )
        else:
            return MaintenanceReconcileResponse(
        )
        """

    def testMaintenanceReconcileResponse(self):
        """Test MaintenanceReconcileResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
