# coding: utf-8

"""
    aimee-kb API

    Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aimee_kb.models.artifact_response import ArtifactResponse

class TestArtifactResponse(unittest.TestCase):
    """ArtifactResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArtifactResponse:
        """Test ArtifactResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArtifactResponse`
        """
        model = ArtifactResponse()
        if include_optional:
            return ArtifactResponse(
                id = '',
                kind = '',
                state = '',
                scope_kind = '',
                scope_id = '',
                confidence = 1.337,
                payload = None,
                citations = [
                    aimee_kb.models.search_hit_citations_inner.SearchHit_citations_inner(
                        source_kind = '', 
                        source_id = '', )
                    ],
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ArtifactResponse(
        )
        """

    def testArtifactResponse(self):
        """Test ArtifactResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
