# coding: utf-8

"""
    aimee-kb API

    Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aimee_kb.models.ingest_status_response import IngestStatusResponse

class TestIngestStatusResponse(unittest.TestCase):
    """IngestStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IngestStatusResponse:
        """Test IngestStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IngestStatusResponse`
        """
        model = IngestStatusResponse()
        if include_optional:
            return IngestStatusResponse(
                status = 'ok',
                queue = aimee_kb.models.ingest_status_response_queue.IngestStatusResponse_queue(
                    pending = 56, 
                    running = 56, 
                    done_last_24h = 56, 
                    failed_last_24h = 56, ),
                workers = aimee_kb.models.ingest_status_response_workers.IngestStatusResponse_workers(
                    configured = 56, 
                    active = 56, ),
                recent = [
                    aimee_kb.models.ingest_status_response_recent_inner.IngestStatusResponse_recent_inner(
                        project = '', 
                        status = '', 
                        completed_at = '', 
                        files_indexed = 56, 
                        chunks_added = 56, 
                        error = '', )
                    ]
            )
        else:
            return IngestStatusResponse(
        )
        """

    def testIngestStatusResponse(self):
        """Test IngestStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
