/*
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CodeProjectLanguage;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CodeProjectStatsResponse
 */
class CodeProjectStatsResponseTest {
    private final CodeProjectStatsResponse model = new CodeProjectStatsResponse();

    /**
     * Model tests for CodeProjectStatsResponse
     */
    @Test
    void testCodeProjectStatsResponse() {
        // TODO: test CodeProjectStatsResponse
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'project'
     */
    @Test
    void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'files'
     */
    @Test
    void filesTest() {
        // TODO: test files
    }

    /**
     * Test the property 'definitions'
     */
    @Test
    void definitionsTest() {
        // TODO: test definitions
    }

    /**
     * Test the property 'langs'
     */
    @Test
    void langsTest() {
        // TODO: test langs
    }

}
