/*
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IngestRequest
 */
class IngestRequestTest {
    private final IngestRequest model = new IngestRequest();

    /**
     * Model tests for IngestRequest
     */
    @Test
    void testIngestRequest() {
        // TODO: test IngestRequest
    }

    /**
     * Test the property 'workspace'
     */
    @Test
    void workspaceTest() {
        // TODO: test workspace
    }

    /**
     * Test the property 'embeddingCommand'
     */
    @Test
    void embeddingCommandTest() {
        // TODO: test embeddingCommand
    }

    /**
     * Test the property 'force'
     */
    @Test
    void forceTest() {
        // TODO: test force
    }

}
