/*
 * aimee-kb API
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IngestStatusResponseWorkers
 */
class IngestStatusResponseWorkersTest {
    private final IngestStatusResponseWorkers model = new IngestStatusResponseWorkers();

    /**
     * Model tests for IngestStatusResponseWorkers
     */
    @Test
    void testIngestStatusResponseWorkers() {
        // TODO: test IngestStatusResponseWorkers
    }

    /**
     * Test the property 'configured'
     */
    @Test
    void configuredTest() {
        // TODO: test configured
    }

    /**
     * Test the property 'active'
     */
    @Test
    void activeTest() {
        // TODO: test active
    }

}
