/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeStructureResponse {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "definitions", skip_serializing_if = "Option::is_none")]
    pub definitions: Option<Vec<models::CodeDefinition>>,
}

impl CodeStructureResponse {
    pub fn new() -> CodeStructureResponse {
        CodeStructureResponse {
            status: None,
            definitions: None,
        }
    }
}

