/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateReleaseRequest {
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateReleaseRequest {
    pub fn new(name: String) -> CreateReleaseRequest {
        CreateReleaseRequest {
            name,
        }
    }
}

