/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocsManifestResponse {
    #[serde(rename = "missing")]
    pub missing: Vec<models::DocsManifestResponseMissingInner>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "present")]
    pub present: i32,
    #[serde(rename = "missing_count")]
    pub missing_count: i32,
}

impl DocsManifestResponse {
    pub fn new(missing: Vec<models::DocsManifestResponseMissingInner>, total: i32, present: i32, missing_count: i32) -> DocsManifestResponse {
        DocsManifestResponse {
            missing,
            total,
            present,
            missing_count,
        }
    }
}

