/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngestStatusResponseWorkers {
    #[serde(rename = "configured", skip_serializing_if = "Option::is_none")]
    pub configured: Option<i32>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<i32>,
}

impl IngestStatusResponseWorkers {
    pub fn new() -> IngestStatusResponseWorkers {
        IngestStatusResponseWorkers {
            configured: None,
            active: None,
        }
    }
}

