/*
 * aimee-kb API
 *
 * Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchRequest {
    #[serde(rename = "query")]
    pub query: String,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "scope_kind", skip_serializing_if = "Option::is_none")]
    pub scope_kind: Option<String>,
    #[serde(rename = "scope_id", skip_serializing_if = "Option::is_none")]
    pub scope_id: Option<String>,
    #[serde(rename = "max_results", skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i32>,
    #[serde(rename = "fusion_mode", skip_serializing_if = "Option::is_none")]
    pub fusion_mode: Option<String>,
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl SearchRequest {
    pub fn new(query: String) -> SearchRequest {
        SearchRequest {
            query,
            project: None,
            scope_kind: None,
            scope_id: None,
            max_results: None,
            fusion_mode: None,
            cursor: None,
        }
    }
}

