/* slop_detect.c: AI-slop pattern detection.
 *
 * All detection is line-by-line using conservative string matching.
 * No regex engine, no AST — designed to run in under 1ms on typical files
 * when called from a post-write hook.
 *
 * False-positive policy: when in doubt, do NOT flag.  These heuristics should
 * almost never fire on legitimate code comments.  A noisy detector will train
 * agents (and humans) to ignore it.
 */
#include "slop_detect.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ---------------------------------------------------------------------------
 * Internal helpers
 * --------------------------------------------------------------------------- */

/* Skip leading whitespace in s, return pointer to first non-space char. */
static const char *skip_ws(const char *s)
{
   while (*s && isspace((unsigned char)*s))
      s++;
   return s;
}

static const char *ifind(const char *haystack, const char *needle)
{
   size_t hlen = strlen(haystack);
   size_t nlen = strlen(needle);
   if (nlen == 0 || nlen > hlen)
      return NULL;
   for (size_t i = 0; i <= hlen - nlen; i++)
   {
      size_t j;
      for (j = 0; j < nlen; j++)
      {
         if (tolower((unsigned char)haystack[i + j]) != tolower((unsigned char)needle[j]))
            break;
      }
      if (j == nlen)
         return haystack + i;
   }
   return NULL;
}

/* Case-insensitive substring match. Returns 1 if needle is in haystack. */
static int icontains(const char *haystack, const char *needle)
{
   return ifind(haystack, needle) != NULL;
}

/* Store a finding if capacity remains. */
static int record(slop_finding_t *out, int max, int *count, slop_category_t cat, int lineno,
                  const char *line, size_t line_len)
{
   if (*count >= max)
      return 0;
   out[*count].category = cat;
   out[*count].line_number = lineno;
   size_t copy = line_len < SLOP_EXCERPT_LEN - 1 ? line_len : SLOP_EXCERPT_LEN - 1;
   /* Strip leading whitespace from excerpt for readability */
   const char *trimmed = skip_ws(line);
   size_t tlen = line_len - (size_t)(trimmed - line);
   copy = tlen < SLOP_EXCERPT_LEN - 1 ? tlen : SLOP_EXCERPT_LEN - 1;
   memcpy(out[*count].excerpt, trimmed, copy);
   out[*count].excerpt[copy] = '\0';
   (*count)++;
   return 1;
}

/* ---------------------------------------------------------------------------
 * Per-category checks
 * The functions below each take a line (not NUL-terminated, length given) and
 * return 1 if the pattern matches.
 * --------------------------------------------------------------------------- */

/* SLOP_ATTRIBUTION: attribution markers left in source.
 * Matches lines that contain phrases like:
 *   "generated by", "generated with", "co-authored-by: ai",
 *   "created by ai", "written by claude", etc.
 *
 * We specifically check for AI-tool attribution, not human co-author lines. */
static int check_attribution(const char *line, size_t len)
{
   /* Work on a NUL-terminated copy (up to 256 chars to bound stack use). */
   char buf[257];
   size_t n = len < 256 ? len : 256;
   memcpy(buf, line, n);
   buf[n] = '\0';

   /* Must be inside a comment; look for common comment delimiters */
   if (!icontains(buf, "//") && !icontains(buf, "#") && !icontains(buf, "*") &&
       !icontains(buf, "<!--") && !icontains(buf, "--"))
      return 0;

   static const char *phrases[] = {"generated by",
                                   "generated with",
                                   "co-authored-by",
                                   "co-authored by",
                                   "created by ai",
                                   "written by ai",
                                   "written by claude",
                                   "written by gpt",
                                   "written by copilot",
                                   "written by gemini",
                                   NULL};

   for (int i = 0; phrases[i]; i++)
   {
      if (icontains(buf, phrases[i]))
         return 1;
   }
   return 0;
}

/* SLOP_HOLLOW_TODO: a TODO or FIXME comment that carries no description.
 *
 * Matches:
 *   // TODO:
 *   // TODO
 *   # FIXME:
 *   // FIXME
 *
 * Does NOT match:
 *   // TODO: handle the case where the user is not authenticated
 *   # FIXME: off-by-one in line 42
 */
static int check_hollow_todo(const char *line, size_t len)
{
   char buf[257];
   size_t n = len < 256 ? len : 256;
   memcpy(buf, line, n);
   buf[n] = '\0';

   /* Find "TODO" or "FIXME" (case-insensitive) */
   const char *p = buf;
   while (*p)
   {
      if (strncasecmp(p, "TODO", 4) == 0 || strncasecmp(p, "FIXME", 5) == 0)
      {
         size_t keyword_len = strncasecmp(p, "TODO", 4) == 0 ? 4 : 5;
         const char *after = p + keyword_len;
         /* Skip optional colon and whitespace */
         if (*after == ':')
            after++;
         after = skip_ws(after);
         /* If nothing (or just comment closer) follows, it's hollow */
         if (*after == '\0' || *after == '*' || strcmp(after, "*/") == 0 ||
             strcmp(after, "-->") == 0)
            return 1;
         /* If only punctuation/symbols follow, it's also hollow */
         int has_word = 0;
         for (const char *q = after; *q; q++)
         {
            if (isalpha((unsigned char)*q))
            {
               has_word = 1;
               break;
            }
         }
         if (!has_word)
            return 1;
         /* Has a description — legitimate */
         return 0;
      }
      p++;
   }
   return 0;
}

/* SLOP_LINT_SUPPRESS: a lint suppression directive with no explanatory reason.
 *
 * Matches:
 *   // eslint-disable-next-line
 *   # noqa
 *   // nolint
 *   // #nosec
 *
 * Does NOT match when there is text after the directive (assumed to be a reason):
 *   // eslint-disable-next-line no-console — needed for debug output
 *   # noqa: E501 — URL cannot be shortened
 */
static int check_lint_suppress(const char *line, size_t len)
{
   char buf[257];
   size_t n = len < 256 ? len : 256;
   memcpy(buf, line, n);
   buf[n] = '\0';

   static const char *directives[] = {"eslint-disable-next-line",
                                      "eslint-disable ",
                                      "nolint",
                                      "#nosec",
                                      "noqa",
                                      "suppress(",
                                      "suppresswarnings(",
                                      NULL};

   for (int i = 0; directives[i]; i++)
   {
      const char *found = ifind(buf, directives[i]);
      if (!found)
         continue;

      const char *after = found + strlen(directives[i]);
      /* Trim any rule name / code that immediately follows (e.g. "nolint:godot") */
      if (*after == ':' || *after == '(')
      {
         /* Skip to end of the rule spec */
         while (*after && !isspace((unsigned char)*after) && *after != ')' && *after != ',')
            after++;
         if (*after == ')')
            after++;
      }
      after = skip_ws(after);

      /* If nothing follows, or only a closing comment marker, it's bare */
      if (*after == '\0' || strcmp(after, "*/") == 0 || strcmp(after, "--") == 0)
         return 1;

      /* If a dash or comma follows and there is text, assume it's a reason */
      if (*after == '-' || *after == ',')
         return 0;

      /* If only non-word characters follow, treat it as bare */
      int has_word = 0;
      for (const char *q = after; *q; q++)
      {
         if (isalpha((unsigned char)*q))
         {
            has_word = 1;
            break;
         }
      }
      if (!has_word)
         return 1;
   }
   return 0;
}

/* SLOP_TYPE_ANNOTATION: a comment whose entire content is a primitive type name.
 *
 * Matches:
 *   // string
 *   // int
 *   // bool
 *   // returns boolean
 *
 * Does NOT match:
 *   // returns the user's name as a string
 *   // string formatting helper
 */
static int check_type_annotation(const char *line, size_t len)
{
   char buf[257];
   size_t n = len < 256 ? len : 256;
   memcpy(buf, line, n);
   buf[n] = '\0';

   /* Find the comment start */
   const char *comment = NULL;
   const char *p = buf;

   /* Look for // */
   while (*p)
   {
      if (p[0] == '/' && p[1] == '/')
      {
         comment = p + 2;
         break;
      }
      /* Look for #-style comment (Python, shell, Ruby) — only when # is not
       * inside a string context (rough heuristic: # at start of trimmed line) */
      if (p == skip_ws(buf) && *p == '#')
      {
         comment = p + 1;
         break;
      }
      p++;
   }
   if (!comment)
      return 0;

   comment = skip_ws(comment);
   /* Strip trailing whitespace */
   char content[128];
   size_t clen = strlen(comment);
   if (clen == 0 || clen >= sizeof(content))
      return 0;
   memcpy(content, comment, clen + 1);
   while (clen > 0 && isspace((unsigned char)content[clen - 1]))
      content[--clen] = '\0';

   if (clen == 0)
      return 0;

   /* Optional leading "returns " or "type:" prefix */
   const char *text = content;
   if (strncasecmp(text, "returns ", 8) == 0)
      text += 8;
   else if (strncasecmp(text, "type:", 5) == 0)
      text = skip_ws(text + 5);
   else if (strncasecmp(text, "return type:", 12) == 0)
      text = skip_ws(text + 12);

   /* Now check if the remaining text is a bare primitive type */
   static const char *types[] = {
       "string", "int",   "integer", "float",  "double",  "bool",   "boolean", "void",     "null",
       "none",   "any",   "object",  "array",  "list",    "dict",   "map",     "number",   "char",
       "byte",   "bytes", "str",     "uint",   "uint8",   "uint16", "uint32",  "uint64",   "int8",
       "int16",  "int32", "int64",   "size_t", "ssize_t", "long",   "short",   "unsigned", NULL};

   for (int i = 0; types[i]; i++)
   {
      if (strcasecmp(text, types[i]) == 0)
         return 1;
   }
   return 0;
}

/* SLOP_PLACEHOLDER: a comment that is explicitly a placeholder or stub.
 *
 * Matches:
 *   // TODO: implement
 *   // placeholder
 *   # stub
 *   // not implemented
 *   // implement me
 *
 * Conservative: only flags very explicit stub markers, not general TODOs
 * (those are caught by check_hollow_todo with a description, which is fine). */
static int check_placeholder(const char *line, size_t len)
{
   char buf[257];
   size_t n = len < 256 ? len : 256;
   memcpy(buf, line, n);
   buf[n] = '\0';

   /* Only fire inside comment context (rough check) */
   if (!icontains(buf, "//") && !icontains(buf, "#") && !icontains(buf, "*"))
      return 0;

   static const char *markers[] = {"not implemented",
                                   "not yet implemented",
                                   "implement me",
                                   "implement this",
                                   "// placeholder",
                                   "# placeholder",
                                   "/* placeholder",
                                   "// stub",
                                   "# stub",
                                   "/* stub",
                                   "TODO: implement",
                                   "FIXME: implement",
                                   NULL};

   for (int i = 0; markers[i]; i++)
   {
      if (icontains(buf, markers[i]))
         return 1;
   }
   return 0;
}

/* ---------------------------------------------------------------------------
 * Public API
 * --------------------------------------------------------------------------- */

int slop_detect_buf(const char *content, size_t len, slop_finding_t *out, int max_findings)
{
   if (!content || !out || max_findings <= 0)
      return 0;
   if (len == 0)
      len = strlen(content);

   int count = 0;
   int lineno = 1;
   const char *p = content;
   const char *end = content + len;

   while (p < end && count < max_findings)
   {
      /* Find end of current line */
      const char *nl = p;
      while (nl < end && *nl != '\n')
         nl++;
      size_t line_len = (size_t)(nl - p);

      /* Run each check */
      if (check_attribution(p, line_len))
         record(out, max_findings, &count, SLOP_ATTRIBUTION, lineno, p, line_len);
      else if (check_hollow_todo(p, line_len))
         record(out, max_findings, &count, SLOP_HOLLOW_TODO, lineno, p, line_len);
      else if (check_lint_suppress(p, line_len))
         record(out, max_findings, &count, SLOP_LINT_SUPPRESS, lineno, p, line_len);
      else if (check_type_annotation(p, line_len))
         record(out, max_findings, &count, SLOP_TYPE_ANNOTATION, lineno, p, line_len);
      else if (check_placeholder(p, line_len))
         record(out, max_findings, &count, SLOP_PLACEHOLDER, lineno, p, line_len);

      p = nl < end ? nl + 1 : end;
      lineno++;
   }

   return count;
}

int slop_detect_file(const char *path, slop_finding_t *out, int max_findings)
{
   if (!path || !out || max_findings <= 0)
      return -1;

   FILE *fp = fopen(path, "r");
   if (!fp)
      return -1;

   /* Read the whole file into memory (up to 1MB — same limit as MAX_FILE_SIZE) */
   fseek(fp, 0, SEEK_END);
   long fsize = ftell(fp);
   rewind(fp);

   if (fsize <= 0 || fsize > 1024 * 1024)
   {
      fclose(fp);
      return fsize == 0 ? 0 : -1;
   }

   char *buf = malloc((size_t)fsize + 1);
   if (!buf)
   {
      fclose(fp);
      return -1;
   }

   size_t nread = fread(buf, 1, (size_t)fsize, fp);
   fclose(fp);
   buf[nread] = '\0';

   int n = slop_detect_buf(buf, nread, out, max_findings);
   free(buf);
   return n;
}

const char *slop_category_label(slop_category_t cat)
{
   switch (cat)
   {
   case SLOP_ATTRIBUTION:
      return "attribution";
   case SLOP_HOLLOW_TODO:
      return "hollow-todo";
   case SLOP_LINT_SUPPRESS:
      return "lint-suppression";
   case SLOP_TYPE_ANNOTATION:
      return "type-annotation";
   case SLOP_PLACEHOLDER:
      return "placeholder";
   default:
      return "unknown";
   }
}
