/*
aimee-kb API

Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aimeekb

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodeScanResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodeScanResponse{}

// CodeScanResponse struct for CodeScanResponse
type CodeScanResponse struct {
	Status string `json:"status"`
	Skipped bool `json:"skipped"`
	Project string `json:"project"`
	Files int32 `json:"files"`
	Inspected int32 `json:"inspected"`
}

type _CodeScanResponse CodeScanResponse

// NewCodeScanResponse instantiates a new CodeScanResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodeScanResponse(status string, skipped bool, project string, files int32, inspected int32) *CodeScanResponse {
	this := CodeScanResponse{}
	this.Status = status
	this.Skipped = skipped
	this.Project = project
	this.Files = files
	this.Inspected = inspected
	return &this
}

// NewCodeScanResponseWithDefaults instantiates a new CodeScanResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodeScanResponseWithDefaults() *CodeScanResponse {
	this := CodeScanResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *CodeScanResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CodeScanResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CodeScanResponse) SetStatus(v string) {
	o.Status = v
}

// GetSkipped returns the Skipped field value
func (o *CodeScanResponse) GetSkipped() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Skipped
}

// GetSkippedOk returns a tuple with the Skipped field value
// and a boolean to check if the value has been set.
func (o *CodeScanResponse) GetSkippedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Skipped, true
}

// SetSkipped sets field value
func (o *CodeScanResponse) SetSkipped(v bool) {
	o.Skipped = v
}

// GetProject returns the Project field value
func (o *CodeScanResponse) GetProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *CodeScanResponse) GetProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *CodeScanResponse) SetProject(v string) {
	o.Project = v
}

// GetFiles returns the Files field value
func (o *CodeScanResponse) GetFiles() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Files
}

// GetFilesOk returns a tuple with the Files field value
// and a boolean to check if the value has been set.
func (o *CodeScanResponse) GetFilesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Files, true
}

// SetFiles sets field value
func (o *CodeScanResponse) SetFiles(v int32) {
	o.Files = v
}

// GetInspected returns the Inspected field value
func (o *CodeScanResponse) GetInspected() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Inspected
}

// GetInspectedOk returns a tuple with the Inspected field value
// and a boolean to check if the value has been set.
func (o *CodeScanResponse) GetInspectedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Inspected, true
}

// SetInspected sets field value
func (o *CodeScanResponse) SetInspected(v int32) {
	o.Inspected = v
}

func (o CodeScanResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodeScanResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["skipped"] = o.Skipped
	toSerialize["project"] = o.Project
	toSerialize["files"] = o.Files
	toSerialize["inspected"] = o.Inspected
	return toSerialize, nil
}

func (o *CodeScanResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"skipped",
		"project",
		"files",
		"inspected",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodeScanResponse := _CodeScanResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodeScanResponse)

	if err != nil {
		return err
	}

	*o = CodeScanResponse(varCodeScanResponse)

	return err
}

type NullableCodeScanResponse struct {
	value *CodeScanResponse
	isSet bool
}

func (v NullableCodeScanResponse) Get() *CodeScanResponse {
	return v.value
}

func (v *NullableCodeScanResponse) Set(val *CodeScanResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodeScanResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodeScanResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodeScanResponse(val *CodeScanResponse) *NullableCodeScanResponse {
	return &NullableCodeScanResponse{value: val, isSet: true}
}

func (v NullableCodeScanResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodeScanResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


