/*
aimee-kb API

Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aimeekb

import (
	"encoding/json"
)

// checks if the CodeFindResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodeFindResponse{}

// CodeFindResponse struct for CodeFindResponse
type CodeFindResponse struct {
	Hits []CodeFindHit `json:"hits,omitempty"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// NewCodeFindResponse instantiates a new CodeFindResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodeFindResponse() *CodeFindResponse {
	this := CodeFindResponse{}
	return &this
}

// NewCodeFindResponseWithDefaults instantiates a new CodeFindResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodeFindResponseWithDefaults() *CodeFindResponse {
	this := CodeFindResponse{}
	return &this
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *CodeFindResponse) GetHits() []CodeFindHit {
	if o == nil || IsNil(o.Hits) {
		var ret []CodeFindHit
		return ret
	}
	return o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeFindResponse) GetHitsOk() ([]CodeFindHit, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *CodeFindResponse) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given []CodeFindHit and assigns it to the Hits field.
func (o *CodeFindResponse) SetHits(v []CodeFindHit) {
	o.Hits = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *CodeFindResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeFindResponse) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *CodeFindResponse) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *CodeFindResponse) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o CodeFindResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodeFindResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	if !IsNil(o.NextCursor) {
		toSerialize["next_cursor"] = o.NextCursor
	}
	return toSerialize, nil
}

type NullableCodeFindResponse struct {
	value *CodeFindResponse
	isSet bool
}

func (v NullableCodeFindResponse) Get() *CodeFindResponse {
	return v.value
}

func (v *NullableCodeFindResponse) Set(val *CodeFindResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodeFindResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodeFindResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodeFindResponse(val *CodeFindResponse) *NullableCodeFindResponse {
	return &NullableCodeFindResponse{value: val, isSet: true}
}

func (v NullableCodeFindResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodeFindResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


