/*
aimee-kb API

Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aimeekb

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateReleaseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateReleaseRequest{}

// CreateReleaseRequest struct for CreateReleaseRequest
type CreateReleaseRequest struct {
	Name string `json:"name"`
}

type _CreateReleaseRequest CreateReleaseRequest

// NewCreateReleaseRequest instantiates a new CreateReleaseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateReleaseRequest(name string) *CreateReleaseRequest {
	this := CreateReleaseRequest{}
	this.Name = name
	return &this
}

// NewCreateReleaseRequestWithDefaults instantiates a new CreateReleaseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateReleaseRequestWithDefaults() *CreateReleaseRequest {
	this := CreateReleaseRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateReleaseRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateReleaseRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateReleaseRequest) SetName(v string) {
	o.Name = v
}

func (o CreateReleaseRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateReleaseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateReleaseRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateReleaseRequest := _CreateReleaseRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateReleaseRequest)

	if err != nil {
		return err
	}

	*o = CreateReleaseRequest(varCreateReleaseRequest)

	return err
}

type NullableCreateReleaseRequest struct {
	value *CreateReleaseRequest
	isSet bool
}

func (v NullableCreateReleaseRequest) Get() *CreateReleaseRequest {
	return v.value
}

func (v *NullableCreateReleaseRequest) Set(val *CreateReleaseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateReleaseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateReleaseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateReleaseRequest(val *CreateReleaseRequest) *NullableCreateReleaseRequest {
	return &NullableCreateReleaseRequest{value: val, isSet: true}
}

func (v NullableCreateReleaseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateReleaseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


