/*
aimee-kb API

Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aimeekb

import (
	"encoding/json"
)

// checks if the MaintenanceReconcileResponseMemory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MaintenanceReconcileResponseMemory{}

// MaintenanceReconcileResponseMemory struct for MaintenanceReconcileResponseMemory
type MaintenanceReconcileResponseMemory struct {
	Kept *int64 `json:"kept,omitempty"`
	Pruned *int64 `json:"pruned,omitempty"`
}

// NewMaintenanceReconcileResponseMemory instantiates a new MaintenanceReconcileResponseMemory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMaintenanceReconcileResponseMemory() *MaintenanceReconcileResponseMemory {
	this := MaintenanceReconcileResponseMemory{}
	return &this
}

// NewMaintenanceReconcileResponseMemoryWithDefaults instantiates a new MaintenanceReconcileResponseMemory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMaintenanceReconcileResponseMemoryWithDefaults() *MaintenanceReconcileResponseMemory {
	this := MaintenanceReconcileResponseMemory{}
	return &this
}

// GetKept returns the Kept field value if set, zero value otherwise.
func (o *MaintenanceReconcileResponseMemory) GetKept() int64 {
	if o == nil || IsNil(o.Kept) {
		var ret int64
		return ret
	}
	return *o.Kept
}

// GetKeptOk returns a tuple with the Kept field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceReconcileResponseMemory) GetKeptOk() (*int64, bool) {
	if o == nil || IsNil(o.Kept) {
		return nil, false
	}
	return o.Kept, true
}

// HasKept returns a boolean if a field has been set.
func (o *MaintenanceReconcileResponseMemory) HasKept() bool {
	if o != nil && !IsNil(o.Kept) {
		return true
	}

	return false
}

// SetKept gets a reference to the given int64 and assigns it to the Kept field.
func (o *MaintenanceReconcileResponseMemory) SetKept(v int64) {
	o.Kept = &v
}

// GetPruned returns the Pruned field value if set, zero value otherwise.
func (o *MaintenanceReconcileResponseMemory) GetPruned() int64 {
	if o == nil || IsNil(o.Pruned) {
		var ret int64
		return ret
	}
	return *o.Pruned
}

// GetPrunedOk returns a tuple with the Pruned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceReconcileResponseMemory) GetPrunedOk() (*int64, bool) {
	if o == nil || IsNil(o.Pruned) {
		return nil, false
	}
	return o.Pruned, true
}

// HasPruned returns a boolean if a field has been set.
func (o *MaintenanceReconcileResponseMemory) HasPruned() bool {
	if o != nil && !IsNil(o.Pruned) {
		return true
	}

	return false
}

// SetPruned gets a reference to the given int64 and assigns it to the Pruned field.
func (o *MaintenanceReconcileResponseMemory) SetPruned(v int64) {
	o.Pruned = &v
}

func (o MaintenanceReconcileResponseMemory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MaintenanceReconcileResponseMemory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Kept) {
		toSerialize["kept"] = o.Kept
	}
	if !IsNil(o.Pruned) {
		toSerialize["pruned"] = o.Pruned
	}
	return toSerialize, nil
}

type NullableMaintenanceReconcileResponseMemory struct {
	value *MaintenanceReconcileResponseMemory
	isSet bool
}

func (v NullableMaintenanceReconcileResponseMemory) Get() *MaintenanceReconcileResponseMemory {
	return v.value
}

func (v *NullableMaintenanceReconcileResponseMemory) Set(val *MaintenanceReconcileResponseMemory) {
	v.value = val
	v.isSet = true
}

func (v NullableMaintenanceReconcileResponseMemory) IsSet() bool {
	return v.isSet
}

func (v *NullableMaintenanceReconcileResponseMemory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMaintenanceReconcileResponseMemory(val *MaintenanceReconcileResponseMemory) *NullableMaintenanceReconcileResponseMemory {
	return &NullableMaintenanceReconcileResponseMemory{value: val, isSet: true}
}

func (v NullableMaintenanceReconcileResponseMemory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMaintenanceReconcileResponseMemory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


