/*
aimee-kb API

Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aimeekb

import (
	"encoding/json"
)

// checks if the CodeStructureResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodeStructureResponse{}

// CodeStructureResponse struct for CodeStructureResponse
type CodeStructureResponse struct {
	Status *string `json:"status,omitempty"`
	Definitions []CodeDefinition `json:"definitions,omitempty"`
}

// NewCodeStructureResponse instantiates a new CodeStructureResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodeStructureResponse() *CodeStructureResponse {
	this := CodeStructureResponse{}
	return &this
}

// NewCodeStructureResponseWithDefaults instantiates a new CodeStructureResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodeStructureResponseWithDefaults() *CodeStructureResponse {
	this := CodeStructureResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CodeStructureResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeStructureResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CodeStructureResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CodeStructureResponse) SetStatus(v string) {
	o.Status = &v
}

// GetDefinitions returns the Definitions field value if set, zero value otherwise.
func (o *CodeStructureResponse) GetDefinitions() []CodeDefinition {
	if o == nil || IsNil(o.Definitions) {
		var ret []CodeDefinition
		return ret
	}
	return o.Definitions
}

// GetDefinitionsOk returns a tuple with the Definitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeStructureResponse) GetDefinitionsOk() ([]CodeDefinition, bool) {
	if o == nil || IsNil(o.Definitions) {
		return nil, false
	}
	return o.Definitions, true
}

// HasDefinitions returns a boolean if a field has been set.
func (o *CodeStructureResponse) HasDefinitions() bool {
	if o != nil && !IsNil(o.Definitions) {
		return true
	}

	return false
}

// SetDefinitions gets a reference to the given []CodeDefinition and assigns it to the Definitions field.
func (o *CodeStructureResponse) SetDefinitions(v []CodeDefinition) {
	o.Definitions = v
}

func (o CodeStructureResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodeStructureResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Definitions) {
		toSerialize["definitions"] = o.Definitions
	}
	return toSerialize, nil
}

type NullableCodeStructureResponse struct {
	value *CodeStructureResponse
	isSet bool
}

func (v NullableCodeStructureResponse) Get() *CodeStructureResponse {
	return v.value
}

func (v *NullableCodeStructureResponse) Set(val *CodeStructureResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodeStructureResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodeStructureResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodeStructureResponse(val *CodeStructureResponse) *NullableCodeStructureResponse {
	return &NullableCodeStructureResponse{value: val, isSet: true}
}

func (v NullableCodeStructureResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodeStructureResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


