/*
aimee-kb API

Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aimeekb

import (
	"encoding/json"
)

// checks if the IngestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IngestRequest{}

// IngestRequest struct for IngestRequest
type IngestRequest struct {
	// Workspace root, workspace name, or \"all\".
	Workspace *string `json:"workspace,omitempty"`
	EmbeddingCommand *string `json:"embedding_command,omitempty"`
	Force *bool `json:"force,omitempty"`
}

// NewIngestRequest instantiates a new IngestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngestRequest() *IngestRequest {
	this := IngestRequest{}
	var force bool = false
	this.Force = &force
	return &this
}

// NewIngestRequestWithDefaults instantiates a new IngestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngestRequestWithDefaults() *IngestRequest {
	this := IngestRequest{}
	var force bool = false
	this.Force = &force
	return &this
}

// GetWorkspace returns the Workspace field value if set, zero value otherwise.
func (o *IngestRequest) GetWorkspace() string {
	if o == nil || IsNil(o.Workspace) {
		var ret string
		return ret
	}
	return *o.Workspace
}

// GetWorkspaceOk returns a tuple with the Workspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngestRequest) GetWorkspaceOk() (*string, bool) {
	if o == nil || IsNil(o.Workspace) {
		return nil, false
	}
	return o.Workspace, true
}

// HasWorkspace returns a boolean if a field has been set.
func (o *IngestRequest) HasWorkspace() bool {
	if o != nil && !IsNil(o.Workspace) {
		return true
	}

	return false
}

// SetWorkspace gets a reference to the given string and assigns it to the Workspace field.
func (o *IngestRequest) SetWorkspace(v string) {
	o.Workspace = &v
}

// GetEmbeddingCommand returns the EmbeddingCommand field value if set, zero value otherwise.
func (o *IngestRequest) GetEmbeddingCommand() string {
	if o == nil || IsNil(o.EmbeddingCommand) {
		var ret string
		return ret
	}
	return *o.EmbeddingCommand
}

// GetEmbeddingCommandOk returns a tuple with the EmbeddingCommand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngestRequest) GetEmbeddingCommandOk() (*string, bool) {
	if o == nil || IsNil(o.EmbeddingCommand) {
		return nil, false
	}
	return o.EmbeddingCommand, true
}

// HasEmbeddingCommand returns a boolean if a field has been set.
func (o *IngestRequest) HasEmbeddingCommand() bool {
	if o != nil && !IsNil(o.EmbeddingCommand) {
		return true
	}

	return false
}

// SetEmbeddingCommand gets a reference to the given string and assigns it to the EmbeddingCommand field.
func (o *IngestRequest) SetEmbeddingCommand(v string) {
	o.EmbeddingCommand = &v
}

// GetForce returns the Force field value if set, zero value otherwise.
func (o *IngestRequest) GetForce() bool {
	if o == nil || IsNil(o.Force) {
		var ret bool
		return ret
	}
	return *o.Force
}

// GetForceOk returns a tuple with the Force field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngestRequest) GetForceOk() (*bool, bool) {
	if o == nil || IsNil(o.Force) {
		return nil, false
	}
	return o.Force, true
}

// HasForce returns a boolean if a field has been set.
func (o *IngestRequest) HasForce() bool {
	if o != nil && !IsNil(o.Force) {
		return true
	}

	return false
}

// SetForce gets a reference to the given bool and assigns it to the Force field.
func (o *IngestRequest) SetForce(v bool) {
	o.Force = &v
}

func (o IngestRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IngestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Workspace) {
		toSerialize["workspace"] = o.Workspace
	}
	if !IsNil(o.EmbeddingCommand) {
		toSerialize["embedding_command"] = o.EmbeddingCommand
	}
	if !IsNil(o.Force) {
		toSerialize["force"] = o.Force
	}
	return toSerialize, nil
}

type NullableIngestRequest struct {
	value *IngestRequest
	isSet bool
}

func (v NullableIngestRequest) Get() *IngestRequest {
	return v.value
}

func (v *NullableIngestRequest) Set(val *IngestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIngestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIngestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngestRequest(val *IngestRequest) *NullableIngestRequest {
	return &NullableIngestRequest{value: val, isSet: true}
}

func (v NullableIngestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


