/*
aimee-kb API

Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aimeekb

import (
	"encoding/json"
)

// checks if the SearchHitCitationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchHitCitationsInner{}

// SearchHitCitationsInner struct for SearchHitCitationsInner
type SearchHitCitationsInner struct {
	SourceKind *string `json:"source_kind,omitempty"`
	SourceId *string `json:"source_id,omitempty"`
}

// NewSearchHitCitationsInner instantiates a new SearchHitCitationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchHitCitationsInner() *SearchHitCitationsInner {
	this := SearchHitCitationsInner{}
	return &this
}

// NewSearchHitCitationsInnerWithDefaults instantiates a new SearchHitCitationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchHitCitationsInnerWithDefaults() *SearchHitCitationsInner {
	this := SearchHitCitationsInner{}
	return &this
}

// GetSourceKind returns the SourceKind field value if set, zero value otherwise.
func (o *SearchHitCitationsInner) GetSourceKind() string {
	if o == nil || IsNil(o.SourceKind) {
		var ret string
		return ret
	}
	return *o.SourceKind
}

// GetSourceKindOk returns a tuple with the SourceKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchHitCitationsInner) GetSourceKindOk() (*string, bool) {
	if o == nil || IsNil(o.SourceKind) {
		return nil, false
	}
	return o.SourceKind, true
}

// HasSourceKind returns a boolean if a field has been set.
func (o *SearchHitCitationsInner) HasSourceKind() bool {
	if o != nil && !IsNil(o.SourceKind) {
		return true
	}

	return false
}

// SetSourceKind gets a reference to the given string and assigns it to the SourceKind field.
func (o *SearchHitCitationsInner) SetSourceKind(v string) {
	o.SourceKind = &v
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *SearchHitCitationsInner) GetSourceId() string {
	if o == nil || IsNil(o.SourceId) {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchHitCitationsInner) GetSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *SearchHitCitationsInner) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *SearchHitCitationsInner) SetSourceId(v string) {
	o.SourceId = &v
}

func (o SearchHitCitationsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchHitCitationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SourceKind) {
		toSerialize["source_kind"] = o.SourceKind
	}
	if !IsNil(o.SourceId) {
		toSerialize["source_id"] = o.SourceId
	}
	return toSerialize, nil
}

type NullableSearchHitCitationsInner struct {
	value *SearchHitCitationsInner
	isSet bool
}

func (v NullableSearchHitCitationsInner) Get() *SearchHitCitationsInner {
	return v.value
}

func (v *NullableSearchHitCitationsInner) Set(val *SearchHitCitationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchHitCitationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchHitCitationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchHitCitationsInner(val *SearchHitCitationsInner) *NullableSearchHitCitationsInner {
	return &NullableSearchHitCitationsInner{value: val, isSet: true}
}

func (v NullableSearchHitCitationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchHitCitationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


