/*
aimee-kb API

Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aimeekb

import (
	"encoding/json"
)

// checks if the EntitySearchResponseEntitiesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntitySearchResponseEntitiesInner{}

// EntitySearchResponseEntitiesInner struct for EntitySearchResponseEntitiesInner
type EntitySearchResponseEntitiesInner struct {
	Entity *string `json:"entity,omitempty"`
	Kind *string `json:"kind,omitempty"`
	Summary *string `json:"summary,omitempty"`
	Score *float64 `json:"score,omitempty"`
}

// NewEntitySearchResponseEntitiesInner instantiates a new EntitySearchResponseEntitiesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitySearchResponseEntitiesInner() *EntitySearchResponseEntitiesInner {
	this := EntitySearchResponseEntitiesInner{}
	return &this
}

// NewEntitySearchResponseEntitiesInnerWithDefaults instantiates a new EntitySearchResponseEntitiesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitySearchResponseEntitiesInnerWithDefaults() *EntitySearchResponseEntitiesInner {
	this := EntitySearchResponseEntitiesInner{}
	return &this
}

// GetEntity returns the Entity field value if set, zero value otherwise.
func (o *EntitySearchResponseEntitiesInner) GetEntity() string {
	if o == nil || IsNil(o.Entity) {
		var ret string
		return ret
	}
	return *o.Entity
}

// GetEntityOk returns a tuple with the Entity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitySearchResponseEntitiesInner) GetEntityOk() (*string, bool) {
	if o == nil || IsNil(o.Entity) {
		return nil, false
	}
	return o.Entity, true
}

// HasEntity returns a boolean if a field has been set.
func (o *EntitySearchResponseEntitiesInner) HasEntity() bool {
	if o != nil && !IsNil(o.Entity) {
		return true
	}

	return false
}

// SetEntity gets a reference to the given string and assigns it to the Entity field.
func (o *EntitySearchResponseEntitiesInner) SetEntity(v string) {
	o.Entity = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *EntitySearchResponseEntitiesInner) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitySearchResponseEntitiesInner) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *EntitySearchResponseEntitiesInner) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *EntitySearchResponseEntitiesInner) SetKind(v string) {
	o.Kind = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *EntitySearchResponseEntitiesInner) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitySearchResponseEntitiesInner) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *EntitySearchResponseEntitiesInner) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *EntitySearchResponseEntitiesInner) SetSummary(v string) {
	o.Summary = &v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *EntitySearchResponseEntitiesInner) GetScore() float64 {
	if o == nil || IsNil(o.Score) {
		var ret float64
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitySearchResponseEntitiesInner) GetScoreOk() (*float64, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *EntitySearchResponseEntitiesInner) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float64 and assigns it to the Score field.
func (o *EntitySearchResponseEntitiesInner) SetScore(v float64) {
	o.Score = &v
}

func (o EntitySearchResponseEntitiesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntitySearchResponseEntitiesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entity) {
		toSerialize["entity"] = o.Entity
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	return toSerialize, nil
}

type NullableEntitySearchResponseEntitiesInner struct {
	value *EntitySearchResponseEntitiesInner
	isSet bool
}

func (v NullableEntitySearchResponseEntitiesInner) Get() *EntitySearchResponseEntitiesInner {
	return v.value
}

func (v *NullableEntitySearchResponseEntitiesInner) Set(val *EntitySearchResponseEntitiesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitySearchResponseEntitiesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitySearchResponseEntitiesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitySearchResponseEntitiesInner(val *EntitySearchResponseEntitiesInner) *NullableEntitySearchResponseEntitiesInner {
	return &NullableEntitySearchResponseEntitiesInner{value: val, isSet: true}
}

func (v NullableEntitySearchResponseEntitiesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitySearchResponseEntitiesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


