/*
aimee-kb API

Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aimeekb

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodeScanRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodeScanRequest{}

// CodeScanRequest struct for CodeScanRequest
type CodeScanRequest struct {
	Project string `json:"project"`
	RootPath string `json:"root_path"`
	Force *bool `json:"force,omitempty"`
}

type _CodeScanRequest CodeScanRequest

// NewCodeScanRequest instantiates a new CodeScanRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodeScanRequest(project string, rootPath string) *CodeScanRequest {
	this := CodeScanRequest{}
	this.Project = project
	this.RootPath = rootPath
	var force bool = false
	this.Force = &force
	return &this
}

// NewCodeScanRequestWithDefaults instantiates a new CodeScanRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodeScanRequestWithDefaults() *CodeScanRequest {
	this := CodeScanRequest{}
	var force bool = false
	this.Force = &force
	return &this
}

// GetProject returns the Project field value
func (o *CodeScanRequest) GetProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *CodeScanRequest) GetProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *CodeScanRequest) SetProject(v string) {
	o.Project = v
}

// GetRootPath returns the RootPath field value
func (o *CodeScanRequest) GetRootPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RootPath
}

// GetRootPathOk returns a tuple with the RootPath field value
// and a boolean to check if the value has been set.
func (o *CodeScanRequest) GetRootPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RootPath, true
}

// SetRootPath sets field value
func (o *CodeScanRequest) SetRootPath(v string) {
	o.RootPath = v
}

// GetForce returns the Force field value if set, zero value otherwise.
func (o *CodeScanRequest) GetForce() bool {
	if o == nil || IsNil(o.Force) {
		var ret bool
		return ret
	}
	return *o.Force
}

// GetForceOk returns a tuple with the Force field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeScanRequest) GetForceOk() (*bool, bool) {
	if o == nil || IsNil(o.Force) {
		return nil, false
	}
	return o.Force, true
}

// HasForce returns a boolean if a field has been set.
func (o *CodeScanRequest) HasForce() bool {
	if o != nil && !IsNil(o.Force) {
		return true
	}

	return false
}

// SetForce gets a reference to the given bool and assigns it to the Force field.
func (o *CodeScanRequest) SetForce(v bool) {
	o.Force = &v
}

func (o CodeScanRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodeScanRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project"] = o.Project
	toSerialize["root_path"] = o.RootPath
	if !IsNil(o.Force) {
		toSerialize["force"] = o.Force
	}
	return toSerialize, nil
}

func (o *CodeScanRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project",
		"root_path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodeScanRequest := _CodeScanRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodeScanRequest)

	if err != nil {
		return err
	}

	*o = CodeScanRequest(varCodeScanRequest)

	return err
}

type NullableCodeScanRequest struct {
	value *CodeScanRequest
	isSet bool
}

func (v NullableCodeScanRequest) Get() *CodeScanRequest {
	return v.value
}

func (v *NullableCodeScanRequest) Set(val *CodeScanRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCodeScanRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCodeScanRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodeScanRequest(val *CodeScanRequest) *NullableCodeScanRequest {
	return &NullableCodeScanRequest{value: val, isSet: true}
}

func (v NullableCodeScanRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodeScanRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


