/*
aimee-kb API

Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aimeekb

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocsManifestRequestDocsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocsManifestRequestDocsInner{}

// DocsManifestRequestDocsInner struct for DocsManifestRequestDocsInner
type DocsManifestRequestDocsInner struct {
	DocKey *string `json:"doc_key,omitempty"`
	Path *string `json:"path,omitempty"`
	ContentHash string `json:"content_hash"`
	Scope *string `json:"scope,omitempty"`
}

type _DocsManifestRequestDocsInner DocsManifestRequestDocsInner

// NewDocsManifestRequestDocsInner instantiates a new DocsManifestRequestDocsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocsManifestRequestDocsInner(contentHash string) *DocsManifestRequestDocsInner {
	this := DocsManifestRequestDocsInner{}
	this.ContentHash = contentHash
	return &this
}

// NewDocsManifestRequestDocsInnerWithDefaults instantiates a new DocsManifestRequestDocsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocsManifestRequestDocsInnerWithDefaults() *DocsManifestRequestDocsInner {
	this := DocsManifestRequestDocsInner{}
	return &this
}

// GetDocKey returns the DocKey field value if set, zero value otherwise.
func (o *DocsManifestRequestDocsInner) GetDocKey() string {
	if o == nil || IsNil(o.DocKey) {
		var ret string
		return ret
	}
	return *o.DocKey
}

// GetDocKeyOk returns a tuple with the DocKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocsManifestRequestDocsInner) GetDocKeyOk() (*string, bool) {
	if o == nil || IsNil(o.DocKey) {
		return nil, false
	}
	return o.DocKey, true
}

// HasDocKey returns a boolean if a field has been set.
func (o *DocsManifestRequestDocsInner) HasDocKey() bool {
	if o != nil && !IsNil(o.DocKey) {
		return true
	}

	return false
}

// SetDocKey gets a reference to the given string and assigns it to the DocKey field.
func (o *DocsManifestRequestDocsInner) SetDocKey(v string) {
	o.DocKey = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *DocsManifestRequestDocsInner) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocsManifestRequestDocsInner) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *DocsManifestRequestDocsInner) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *DocsManifestRequestDocsInner) SetPath(v string) {
	o.Path = &v
}

// GetContentHash returns the ContentHash field value
func (o *DocsManifestRequestDocsInner) GetContentHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentHash
}

// GetContentHashOk returns a tuple with the ContentHash field value
// and a boolean to check if the value has been set.
func (o *DocsManifestRequestDocsInner) GetContentHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentHash, true
}

// SetContentHash sets field value
func (o *DocsManifestRequestDocsInner) SetContentHash(v string) {
	o.ContentHash = v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *DocsManifestRequestDocsInner) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocsManifestRequestDocsInner) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *DocsManifestRequestDocsInner) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *DocsManifestRequestDocsInner) SetScope(v string) {
	o.Scope = &v
}

func (o DocsManifestRequestDocsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocsManifestRequestDocsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DocKey) {
		toSerialize["doc_key"] = o.DocKey
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	toSerialize["content_hash"] = o.ContentHash
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	return toSerialize, nil
}

func (o *DocsManifestRequestDocsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content_hash",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocsManifestRequestDocsInner := _DocsManifestRequestDocsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocsManifestRequestDocsInner)

	if err != nil {
		return err
	}

	*o = DocsManifestRequestDocsInner(varDocsManifestRequestDocsInner)

	return err
}

type NullableDocsManifestRequestDocsInner struct {
	value *DocsManifestRequestDocsInner
	isSet bool
}

func (v NullableDocsManifestRequestDocsInner) Get() *DocsManifestRequestDocsInner {
	return v.value
}

func (v *NullableDocsManifestRequestDocsInner) Set(val *DocsManifestRequestDocsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDocsManifestRequestDocsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDocsManifestRequestDocsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocsManifestRequestDocsInner(val *DocsManifestRequestDocsInner) *NullableDocsManifestRequestDocsInner {
	return &NullableDocsManifestRequestDocsInner{value: val, isSet: true}
}

func (v NullableDocsManifestRequestDocsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocsManifestRequestDocsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


