/*
aimee-kb API

Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aimeekb

import (
	"encoding/json"
)

// checks if the CodeBuildResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodeBuildResponse{}

// CodeBuildResponse struct for CodeBuildResponse
type CodeBuildResponse struct {
	Status *string `json:"status,omitempty"`
	Project *string `json:"project,omitempty"`
	FilesScanned *int32 `json:"files_scanned,omitempty"`
	FilesIndexed *int32 `json:"files_indexed,omitempty"`
	FilesSkipped *int32 `json:"files_skipped,omitempty"`
	FilesRemoved *int32 `json:"files_removed,omitempty"`
	ChunksAdded *int32 `json:"chunks_added,omitempty"`
	ChunksRemoved *int32 `json:"chunks_removed,omitempty"`
	EmbeddingsAdded *int32 `json:"embeddings_added,omitempty"`
}

// NewCodeBuildResponse instantiates a new CodeBuildResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodeBuildResponse() *CodeBuildResponse {
	this := CodeBuildResponse{}
	return &this
}

// NewCodeBuildResponseWithDefaults instantiates a new CodeBuildResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodeBuildResponseWithDefaults() *CodeBuildResponse {
	this := CodeBuildResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CodeBuildResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeBuildResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CodeBuildResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CodeBuildResponse) SetStatus(v string) {
	o.Status = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *CodeBuildResponse) GetProject() string {
	if o == nil || IsNil(o.Project) {
		var ret string
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeBuildResponse) GetProjectOk() (*string, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *CodeBuildResponse) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given string and assigns it to the Project field.
func (o *CodeBuildResponse) SetProject(v string) {
	o.Project = &v
}

// GetFilesScanned returns the FilesScanned field value if set, zero value otherwise.
func (o *CodeBuildResponse) GetFilesScanned() int32 {
	if o == nil || IsNil(o.FilesScanned) {
		var ret int32
		return ret
	}
	return *o.FilesScanned
}

// GetFilesScannedOk returns a tuple with the FilesScanned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeBuildResponse) GetFilesScannedOk() (*int32, bool) {
	if o == nil || IsNil(o.FilesScanned) {
		return nil, false
	}
	return o.FilesScanned, true
}

// HasFilesScanned returns a boolean if a field has been set.
func (o *CodeBuildResponse) HasFilesScanned() bool {
	if o != nil && !IsNil(o.FilesScanned) {
		return true
	}

	return false
}

// SetFilesScanned gets a reference to the given int32 and assigns it to the FilesScanned field.
func (o *CodeBuildResponse) SetFilesScanned(v int32) {
	o.FilesScanned = &v
}

// GetFilesIndexed returns the FilesIndexed field value if set, zero value otherwise.
func (o *CodeBuildResponse) GetFilesIndexed() int32 {
	if o == nil || IsNil(o.FilesIndexed) {
		var ret int32
		return ret
	}
	return *o.FilesIndexed
}

// GetFilesIndexedOk returns a tuple with the FilesIndexed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeBuildResponse) GetFilesIndexedOk() (*int32, bool) {
	if o == nil || IsNil(o.FilesIndexed) {
		return nil, false
	}
	return o.FilesIndexed, true
}

// HasFilesIndexed returns a boolean if a field has been set.
func (o *CodeBuildResponse) HasFilesIndexed() bool {
	if o != nil && !IsNil(o.FilesIndexed) {
		return true
	}

	return false
}

// SetFilesIndexed gets a reference to the given int32 and assigns it to the FilesIndexed field.
func (o *CodeBuildResponse) SetFilesIndexed(v int32) {
	o.FilesIndexed = &v
}

// GetFilesSkipped returns the FilesSkipped field value if set, zero value otherwise.
func (o *CodeBuildResponse) GetFilesSkipped() int32 {
	if o == nil || IsNil(o.FilesSkipped) {
		var ret int32
		return ret
	}
	return *o.FilesSkipped
}

// GetFilesSkippedOk returns a tuple with the FilesSkipped field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeBuildResponse) GetFilesSkippedOk() (*int32, bool) {
	if o == nil || IsNil(o.FilesSkipped) {
		return nil, false
	}
	return o.FilesSkipped, true
}

// HasFilesSkipped returns a boolean if a field has been set.
func (o *CodeBuildResponse) HasFilesSkipped() bool {
	if o != nil && !IsNil(o.FilesSkipped) {
		return true
	}

	return false
}

// SetFilesSkipped gets a reference to the given int32 and assigns it to the FilesSkipped field.
func (o *CodeBuildResponse) SetFilesSkipped(v int32) {
	o.FilesSkipped = &v
}

// GetFilesRemoved returns the FilesRemoved field value if set, zero value otherwise.
func (o *CodeBuildResponse) GetFilesRemoved() int32 {
	if o == nil || IsNil(o.FilesRemoved) {
		var ret int32
		return ret
	}
	return *o.FilesRemoved
}

// GetFilesRemovedOk returns a tuple with the FilesRemoved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeBuildResponse) GetFilesRemovedOk() (*int32, bool) {
	if o == nil || IsNil(o.FilesRemoved) {
		return nil, false
	}
	return o.FilesRemoved, true
}

// HasFilesRemoved returns a boolean if a field has been set.
func (o *CodeBuildResponse) HasFilesRemoved() bool {
	if o != nil && !IsNil(o.FilesRemoved) {
		return true
	}

	return false
}

// SetFilesRemoved gets a reference to the given int32 and assigns it to the FilesRemoved field.
func (o *CodeBuildResponse) SetFilesRemoved(v int32) {
	o.FilesRemoved = &v
}

// GetChunksAdded returns the ChunksAdded field value if set, zero value otherwise.
func (o *CodeBuildResponse) GetChunksAdded() int32 {
	if o == nil || IsNil(o.ChunksAdded) {
		var ret int32
		return ret
	}
	return *o.ChunksAdded
}

// GetChunksAddedOk returns a tuple with the ChunksAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeBuildResponse) GetChunksAddedOk() (*int32, bool) {
	if o == nil || IsNil(o.ChunksAdded) {
		return nil, false
	}
	return o.ChunksAdded, true
}

// HasChunksAdded returns a boolean if a field has been set.
func (o *CodeBuildResponse) HasChunksAdded() bool {
	if o != nil && !IsNil(o.ChunksAdded) {
		return true
	}

	return false
}

// SetChunksAdded gets a reference to the given int32 and assigns it to the ChunksAdded field.
func (o *CodeBuildResponse) SetChunksAdded(v int32) {
	o.ChunksAdded = &v
}

// GetChunksRemoved returns the ChunksRemoved field value if set, zero value otherwise.
func (o *CodeBuildResponse) GetChunksRemoved() int32 {
	if o == nil || IsNil(o.ChunksRemoved) {
		var ret int32
		return ret
	}
	return *o.ChunksRemoved
}

// GetChunksRemovedOk returns a tuple with the ChunksRemoved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeBuildResponse) GetChunksRemovedOk() (*int32, bool) {
	if o == nil || IsNil(o.ChunksRemoved) {
		return nil, false
	}
	return o.ChunksRemoved, true
}

// HasChunksRemoved returns a boolean if a field has been set.
func (o *CodeBuildResponse) HasChunksRemoved() bool {
	if o != nil && !IsNil(o.ChunksRemoved) {
		return true
	}

	return false
}

// SetChunksRemoved gets a reference to the given int32 and assigns it to the ChunksRemoved field.
func (o *CodeBuildResponse) SetChunksRemoved(v int32) {
	o.ChunksRemoved = &v
}

// GetEmbeddingsAdded returns the EmbeddingsAdded field value if set, zero value otherwise.
func (o *CodeBuildResponse) GetEmbeddingsAdded() int32 {
	if o == nil || IsNil(o.EmbeddingsAdded) {
		var ret int32
		return ret
	}
	return *o.EmbeddingsAdded
}

// GetEmbeddingsAddedOk returns a tuple with the EmbeddingsAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeBuildResponse) GetEmbeddingsAddedOk() (*int32, bool) {
	if o == nil || IsNil(o.EmbeddingsAdded) {
		return nil, false
	}
	return o.EmbeddingsAdded, true
}

// HasEmbeddingsAdded returns a boolean if a field has been set.
func (o *CodeBuildResponse) HasEmbeddingsAdded() bool {
	if o != nil && !IsNil(o.EmbeddingsAdded) {
		return true
	}

	return false
}

// SetEmbeddingsAdded gets a reference to the given int32 and assigns it to the EmbeddingsAdded field.
func (o *CodeBuildResponse) SetEmbeddingsAdded(v int32) {
	o.EmbeddingsAdded = &v
}

func (o CodeBuildResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodeBuildResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.FilesScanned) {
		toSerialize["files_scanned"] = o.FilesScanned
	}
	if !IsNil(o.FilesIndexed) {
		toSerialize["files_indexed"] = o.FilesIndexed
	}
	if !IsNil(o.FilesSkipped) {
		toSerialize["files_skipped"] = o.FilesSkipped
	}
	if !IsNil(o.FilesRemoved) {
		toSerialize["files_removed"] = o.FilesRemoved
	}
	if !IsNil(o.ChunksAdded) {
		toSerialize["chunks_added"] = o.ChunksAdded
	}
	if !IsNil(o.ChunksRemoved) {
		toSerialize["chunks_removed"] = o.ChunksRemoved
	}
	if !IsNil(o.EmbeddingsAdded) {
		toSerialize["embeddings_added"] = o.EmbeddingsAdded
	}
	return toSerialize, nil
}

type NullableCodeBuildResponse struct {
	value *CodeBuildResponse
	isSet bool
}

func (v NullableCodeBuildResponse) Get() *CodeBuildResponse {
	return v.value
}

func (v *NullableCodeBuildResponse) Set(val *CodeBuildResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodeBuildResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodeBuildResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodeBuildResponse(val *CodeBuildResponse) *NullableCodeBuildResponse {
	return &NullableCodeBuildResponse{value: val, isSet: true}
}

func (v NullableCodeBuildResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodeBuildResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


