/*
aimee-kb API

Public HTTP API for the aimee knowledge-base sidecar (aimee-kb). Enabled by setting kb.api.http_port in aimee config. Optional bearer-token auth via kb.api.bearer_token. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aimeekb

import (
	"encoding/json"
)

// checks if the BlastRadiusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlastRadiusResponse{}

// BlastRadiusResponse struct for BlastRadiusResponse
type BlastRadiusResponse struct {
	File *string `json:"file,omitempty"`
	Dependents []string `json:"dependents,omitempty"`
	DependentCount *int32 `json:"dependent_count,omitempty"`
	Dependencies []string `json:"dependencies,omitempty"`
	DependencyCount *int32 `json:"dependency_count,omitempty"`
}

// NewBlastRadiusResponse instantiates a new BlastRadiusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlastRadiusResponse() *BlastRadiusResponse {
	this := BlastRadiusResponse{}
	return &this
}

// NewBlastRadiusResponseWithDefaults instantiates a new BlastRadiusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlastRadiusResponseWithDefaults() *BlastRadiusResponse {
	this := BlastRadiusResponse{}
	return &this
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *BlastRadiusResponse) GetFile() string {
	if o == nil || IsNil(o.File) {
		var ret string
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlastRadiusResponse) GetFileOk() (*string, bool) {
	if o == nil || IsNil(o.File) {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *BlastRadiusResponse) HasFile() bool {
	if o != nil && !IsNil(o.File) {
		return true
	}

	return false
}

// SetFile gets a reference to the given string and assigns it to the File field.
func (o *BlastRadiusResponse) SetFile(v string) {
	o.File = &v
}

// GetDependents returns the Dependents field value if set, zero value otherwise.
func (o *BlastRadiusResponse) GetDependents() []string {
	if o == nil || IsNil(o.Dependents) {
		var ret []string
		return ret
	}
	return o.Dependents
}

// GetDependentsOk returns a tuple with the Dependents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlastRadiusResponse) GetDependentsOk() ([]string, bool) {
	if o == nil || IsNil(o.Dependents) {
		return nil, false
	}
	return o.Dependents, true
}

// HasDependents returns a boolean if a field has been set.
func (o *BlastRadiusResponse) HasDependents() bool {
	if o != nil && !IsNil(o.Dependents) {
		return true
	}

	return false
}

// SetDependents gets a reference to the given []string and assigns it to the Dependents field.
func (o *BlastRadiusResponse) SetDependents(v []string) {
	o.Dependents = v
}

// GetDependentCount returns the DependentCount field value if set, zero value otherwise.
func (o *BlastRadiusResponse) GetDependentCount() int32 {
	if o == nil || IsNil(o.DependentCount) {
		var ret int32
		return ret
	}
	return *o.DependentCount
}

// GetDependentCountOk returns a tuple with the DependentCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlastRadiusResponse) GetDependentCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DependentCount) {
		return nil, false
	}
	return o.DependentCount, true
}

// HasDependentCount returns a boolean if a field has been set.
func (o *BlastRadiusResponse) HasDependentCount() bool {
	if o != nil && !IsNil(o.DependentCount) {
		return true
	}

	return false
}

// SetDependentCount gets a reference to the given int32 and assigns it to the DependentCount field.
func (o *BlastRadiusResponse) SetDependentCount(v int32) {
	o.DependentCount = &v
}

// GetDependencies returns the Dependencies field value if set, zero value otherwise.
func (o *BlastRadiusResponse) GetDependencies() []string {
	if o == nil || IsNil(o.Dependencies) {
		var ret []string
		return ret
	}
	return o.Dependencies
}

// GetDependenciesOk returns a tuple with the Dependencies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlastRadiusResponse) GetDependenciesOk() ([]string, bool) {
	if o == nil || IsNil(o.Dependencies) {
		return nil, false
	}
	return o.Dependencies, true
}

// HasDependencies returns a boolean if a field has been set.
func (o *BlastRadiusResponse) HasDependencies() bool {
	if o != nil && !IsNil(o.Dependencies) {
		return true
	}

	return false
}

// SetDependencies gets a reference to the given []string and assigns it to the Dependencies field.
func (o *BlastRadiusResponse) SetDependencies(v []string) {
	o.Dependencies = v
}

// GetDependencyCount returns the DependencyCount field value if set, zero value otherwise.
func (o *BlastRadiusResponse) GetDependencyCount() int32 {
	if o == nil || IsNil(o.DependencyCount) {
		var ret int32
		return ret
	}
	return *o.DependencyCount
}

// GetDependencyCountOk returns a tuple with the DependencyCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlastRadiusResponse) GetDependencyCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DependencyCount) {
		return nil, false
	}
	return o.DependencyCount, true
}

// HasDependencyCount returns a boolean if a field has been set.
func (o *BlastRadiusResponse) HasDependencyCount() bool {
	if o != nil && !IsNil(o.DependencyCount) {
		return true
	}

	return false
}

// SetDependencyCount gets a reference to the given int32 and assigns it to the DependencyCount field.
func (o *BlastRadiusResponse) SetDependencyCount(v int32) {
	o.DependencyCount = &v
}

func (o BlastRadiusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlastRadiusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.File) {
		toSerialize["file"] = o.File
	}
	if !IsNil(o.Dependents) {
		toSerialize["dependents"] = o.Dependents
	}
	if !IsNil(o.DependentCount) {
		toSerialize["dependent_count"] = o.DependentCount
	}
	if !IsNil(o.Dependencies) {
		toSerialize["dependencies"] = o.Dependencies
	}
	if !IsNil(o.DependencyCount) {
		toSerialize["dependency_count"] = o.DependencyCount
	}
	return toSerialize, nil
}

type NullableBlastRadiusResponse struct {
	value *BlastRadiusResponse
	isSet bool
}

func (v NullableBlastRadiusResponse) Get() *BlastRadiusResponse {
	return v.value
}

func (v *NullableBlastRadiusResponse) Set(val *BlastRadiusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBlastRadiusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBlastRadiusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlastRadiusResponse(val *BlastRadiusResponse) *NullableBlastRadiusResponse {
	return &NullableBlastRadiusResponse{value: val, isSet: true}
}

func (v NullableBlastRadiusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlastRadiusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


